import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { lmMaps,lmF,lmJ,lmR,lmDelta,lmLocal,lmBound,lmNorm,lmSub,lmScale,lmAdd,lmDot,lmMV,lmMM,lmRotation,lmBasis,lmG,lmJG,lmChain,lmCurveCoefficients,lmCurve,lmVelocity,lmMVT,lmQuadratic,lmCounterexample,lmNumber,lmCSV } from '../src/linear-math.js';
import { linearDefaults,parseLinearState,serializeLinearState,lmChooseColumn,lmSetLength } from '../src/linear-state.js';
import { lmProofs,lmQuestions,lmEscape,linearPage } from '../src/linear-content.js';
import { lmInputSVG,lmOutputSVG,lmErrorSVG,lmChainSVG,lmCurveSVG,lmCompassSVG,lmShadowSVG } from '../src/linear-plots.js';
import { parseState,serializeState,defaults } from '../src/state.js';
const eps=(x,y,t=1e-10)=>assert.ok(Math.abs(x-y)<=t*Math.max(1,Math.abs(x),Math.abs(y)),`${x} vs ${y}`);
const vec=(a,b,t)=>a.forEach((x,i)=>eps(x,b[i],t));
const mats=(A,B,t)=>A.forEach((r,i)=>vec(r,B[i],t));
const ps=[[0,0],[.6,.2],[-.7,1.1],[1.4,-1.2]],hs=[[.2,.3],[-.4,.1],[0,.4],[.5,0],[-.01,-.02]];
for(const id of Object.keys(lmMaps)){
 test(`${id}: Jacobian agrees with independent centered coordinate derivatives`,()=>{for(const p of ps)for(let j=0;j<2;j++){const h=[0,0];h[j]=1e-5;const d=lmScale(lmSub(lmF(id,lmAdd(p,h)),lmF(id,lmSub(p,h))),1/(2e-5));vec(d,lmJ(id,p).map(r=>r[j]),2e-8);}});
 test(`${id}: stable polynomial increment equals independent endpoint difference`,()=>{for(const p of ps)for(const h of hs)vec(lmDelta(id,p,h),lmSub(lmF(id,lmAdd(p,h)),lmF(id,p)));});
 test(`${id}: exact residual formula gives Delta = Jh+R`,()=>{for(const p of ps)for(const h of hs){const x=lmLocal(id,p,h);vec(lmSub(x.truth,x.pred),lmR(id,p,h));eps(x.ratio,x.error/lmNorm(h));}});
 test(`${id}: all-direction remainder bound survives varied angles and radii`,()=>{for(const p of ps)for(const r of [1.2,.5,.05,1e-4])for(let k=0;k<72;k++){const h=[r*Math.cos(k),r*Math.sin(k)],x=lmLocal(id,p,h);assert.ok(x.ratio<=lmBound(id,p,r)*(1+1e-12)+1e-14);}assert.ok(lmBound(id,ps[1],1e-7)<=1e-6);});
 test(`${id}: columns equal action on standard basis; rho factor not omitted`,()=>{const p=ps[1],A=lmJ(id,p);for(let j=0;j<2;j++){const e=[0,0];e[j]=1;const col=A.map(r=>r[j]);vec(lmMV(A,e),col);vec(lmMV(A,lmScale(e,.1)),lmScale(col,.1));}});
 test(`${id}: change of input basis preserves the physical output`,()=>{for(const deg of [-90,-37,0,23,90]){const b=lmBasis(id,ps[1],hs[0],deg);vec(lmMV(b.B,b.coords),hs[0]);vec(b.physical,lmMV(b.A,hs[0]));}});
 for(const outer of ['bend','mix']){
  test(`${id}/${outer}: composed prediction and stable composite remainder`,()=>{for(const p of ps)for(const h of hs){const k=lmChain(id,outer,p,h);vec(k.two,k.one);vec(k.truth,lmSub(lmG(outer,lmF(id,lmAdd(p,h))),lmG(outer,lmF(id,p))));vec(lmSub(k.truth,k.one),k.R);assert.ok(k.ratio<=k.bound*(1+1e-10)+1e-12);}});
  test(`${id}/${outer}: chain evaluates outer derivative at F(p)`,()=>{const p=ps[1],h=[.3,-.2],k=lmChain(id,outer,p,h),B=lmJG(outer,lmF(id,p));mats(k.B,B);mats(k.product,lmMM(B,lmJ(id,p)));for(let j=0;j<2;j++){const d=[0,0];d[j]=1e-5;const plus=lmG(outer,lmF(id,lmAdd(p,d))),minus=lmG(outer,lmF(id,lmSub(p,d)));vec(lmScale(lmSub(plus,minus),5e4),k.product.map(row=>row[j]),2e-8);}});
 }
 test(`${id}: curve coefficients are independent expansion of F along input segment`,()=>{for(const p of ps)for(const y of ps){const C=lmCurveCoefficients(id,p,y);for(const t of [0,.17,.5,.9,1]){const z=lmAdd(p,lmScale(lmSub(y,p),t));vec(lmCurve(C,t),lmF(id,z));vec(lmVelocity(C,t),lmMV(lmJ(id,z),lmSub(y,p)));}}});
 test(`${id}: algebraic MVT candidates are interior and satisfy projected equality`,()=>{for(const p of ps)for(const y of ps){if(lmNorm(lmSub(y,p))===0)continue;for(const angle of [0,13,45,90,137,180,231,270,359]){const m=lmMVT(id,p,y,angle);assert.ok(m.all||m.roots.length>=1,JSON.stringify({id,p,y,angle,m}));for(const root of m.all?[.23,.51,.87]:m.roots){assert.ok(root>0&&root<1);const v=lmMVT(id,p,y,angle,root);eps(v.slope,v.chord,1e-8);}}}});
}
test('At h=0 the ratio and bound-readout are undefined, not silently zero',()=>{for(const id of Object.keys(lmMaps)){const x=lmLocal(id,[.3,.2],[0,0]);assert.equal(x.ratio,null);assert.equal(x.bound,null);assert.equal(lmChain(id,'bend',[.3,.2],[0,0]).ratio,null);vec(x.truth,[0,0]);}});
test('Small nonzero remainders are computed algebraically rather than cancelled to zero',()=>{const x=lmLocal('cubic',[1,.2],[1e-10,0]);eps(x.R[0],1e-20,1e-24);assert.ok(x.error>0);assert.ok(x.ratio>0);});
test('A singular Jacobian does not invalidate differentiability',()=>{mats(lmJ('cubic',[0,0]),[[0,-1],[0,1]]);assert.ok(lmLocal('cubic',[0,0],[1e-3,0]).ratio<.002);});
test('Composing linear maps supports non-square dimensions',()=>{const A=[[1,2],[0,1],[3,0]],B=[[1,0,0],[0,1,0],[0,0,1],[1,1,1]],h=[.7,-.2];const BA=lmMM(B,A);assert.equal(BA.length,4);assert.equal(BA[0].length,2);vec(lmMV(BA,h),lmMV(B,lmMV(A,h)));});
test('The default maps do not commute; a reversed-order demonstration is real',()=>{const s=linearDefaults(),c=lmChain(s.map,s.outer,[s.px,s.py],[s.hx,s.hy]);assert.ok(lmNorm(lmSub(c.one,c.wrong))>.05);});
test('Counterexample has disjoint coordinate MVT solution sets',()=>{const c=lmCounterexample(),e1=lmMVT('cubic',c.p,c.y,0),e2=lmMVT('cubic',c.p,c.y,90);vec(e1.D,[0,2]);vec(e1.roots,c.first);vec(e2.roots,c.second);for(const a of e1.roots)for(const b of e2.roots)assert.ok(Math.abs(a-b)>.2);});
test('Reversing a keeps the same MVT candidates but changes both projection signs',()=>{for(const angle of [0,23,90,127]){const a=lmMVT('cubic',[-1,0],[1,0],angle,.3),b=lmMVT('cubic',[-1,0],[1,0],angle+180,.3);vec(a.roots,b.roots);eps(a.scalar,-b.scalar);eps(a.chord,-b.chord);}});
test('Quadratic positive example shares its midpoint for both coordinates',()=>{for(const angle of [0,39,90,139,270]){const m=lmMVT('quadratic',[-1,.4],[1,-.6],angle,.5);eps(m.slope,m.chord);}});
test('Affine example has an entire interval of valid MVT points',()=>{const m=lmMVT('affine',[-1,0],[1,.8],30);assert.equal(m.all,true);});
test('Coincident endpoints are marked degenerate instead of using a nontrivial MVT',()=>{assert.equal(lmMVT('cubic',[.5,0],[.5,0],30).distinct,false);});
test('Quadratic solver handles linear, repeated, constant and impossible cases',()=>{vec(lmQuadratic(0,2,-1).roots,[.5]);vec(lmQuadratic(1,-2,1).roots,[1]);assert.equal(lmQuadratic(0,0,0).all,true);assert.deepEqual(lmQuadratic(0,0,1).roots,[]);assert.deepEqual(lmQuadratic(1,0,1).roots,[]);});
test('Global route and defaults mount the linear lab without changing existing routes',()=>{assert.equal(defaults('linear').lab,'linear');assert.equal(parseState('#lab=linear').map,'cubic');for(const id of ['limits','differentiability','fields','completeness','taylor','series','uniform'])assert.equal(parseState('#lab='+id).lab,id);});
test('New state roundtrips while retaining fractional direction and all four stations',()=>{for(const step of ['local','columns','chain','projection']){const s={...linearDefaults(),step,basis:23,normalized:false,wrong:true,merged:true};const t=parseState(serializeState(s));for(const k of Object.keys(s)){if(typeof s[k]==='number')eps(s[k],t[k],1e-6);else assert.equal(s[k],t[k]);}}});
test('Malformed URLs cannot inject HTML or invalid math into the new state',()=>{const s=parseLinearState(new URLSearchParams('map=%3Cscript%3E&outer=X&screen=X&step=X&px=Infinity&py=-99&hx=100&hy=100&lambda=2&basis=NaN&angle=-1&proofStep=99'));assert.equal(s.map,'cubic');assert.equal(s.screen,'explore');assert.equal(s.py,-1.5);assert.ok(lmNorm([s.hx,s.hy])<=1.2+1e-12);assert.equal(s.lambda,1);assert.equal(s.proofStep,3);assert.ok(!linearPage(s).includes('<script>'));});
test('Basis column selection scales by current rho and preserves physical direction when shrinking',()=>{const s={...linearDefaults(),basis:37},r=lmNorm([s.hx,s.hy]);lmChooseColumn(s,2);vec([s.hx,s.hy],lmScale(lmMV(lmRotation(37),[0,1]),r));lmSetLength(s,.001);eps(lmNorm([s.hx,s.hy]),.001);});
test('Proofs explicitly retain normalized error, chain basepoint, and quantifier ordering',()=>{assert.equal(Object.keys(lmProofs).length,4);for(const p of Object.values(lmProofs)){assert.equal(p.steps.length,4);assert.ok(p.given.length>40);for(const step of p.steps)assert.equal(step.length,3);}assert.match(JSON.stringify(lmProofs),/∀a ∃z/);assert.match(JSON.stringify(lmProofs),/不要求.*可逆/);assert.match(JSON.stringify(lmProofs),/o\(‖h‖\)/);});
test('Every learning station and proof is a filled page rather than a stub',()=>{for(const step of ['local','columns','chain','projection'])for(const screen of ['explore','proof','challenge']){const t=linearPage({...linearDefaults(),step,screen});assert.ok(t.includes('lm-journey'));assert.ok(!/TODO|PLACEHOLDER|coming soon/.test(t));assert.ok(t.length>3500);}});
test('Quiz keys are valid, varied, and include reasons',()=>{assert.equal(lmQuestions.length,8);const answers=new Set();for(const q of lmQuestions){assert.ok(q.correct>=0&&q.correct<q.options.length);answers.add(q.correct);assert.ok(q.why.length>25);assert.equal(new Set(q.options).size,q.options.length);}assert.equal(answers.size,3);});
test('SVG output is finite across edge and ordinary states; ratios at zero do not become NaN',()=>{for(const map of Object.keys(lmMaps))for(const h of [[0,0],[.001,0],[-.7,.1]])for(const step of ['local','columns','chain','projection']){const s={...linearDefaults(),map,step,hx:h[0],hy:h[1],normalized:true};for(const fn of [lmInputSVG,lmOutputSVG,lmErrorSVG,lmCurveSVG,lmCompassSVG,lmShadowSVG]){const svg=fn(s);assert.ok(svg.startsWith('<svg'));assert.ok(!/NaN|Infinity|undefined/.test(svg));}for(const j of [0,1,2])assert.ok(!/NaN|Infinity/.test(lmChainSVG(s,j)));}});
test('Dynamic mathematical text is escaped; error and CSV retain tiny scientific notation',()=>{assert.equal(lmEscape('x<y & "z"'),'x&lt;y &amp; &quot;z&quot;');assert.equal(lmNumber(null),'未定义');assert.match(lmNumber(1e-16),/e-16/);const csv=lmCSV(linearDefaults());assert.ok(csv.includes('proved_upper_bound'));assert.ok(csv.includes('interior_roots='));assert.equal(csv.split('\n').filter(x=>/^\d/.test(x)).length,33);});
test('New modules participate in the real build and navigation, not an isolated demo',async()=>{const script=await readFile(new URL('../scripts/standalone.mjs',import.meta.url),'utf8');for(const x of ['linear-math','linear-state','linear-content','linear-plots','linear-lab'])assert.ok(script.includes(`'${x}'`));const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('id="nav-linear"'));assert.ok(index.includes('styles/linear.css'));});
