import { completenessNodes, completenessEdges, completenessTargets, cpNode, cpEdge, cpTarget, implicationPath } from './completeness-math.js';
import { completenessGraph } from './completeness-plots.js';
import { icon } from './icons.js';
export const cpDefinitions = {
 sup:{tag:'集合 → 最小上界',claim:'K 的每个非空、有上界的子集 A，都有属于 K 的上确界。',formula:'s = sup A ∈ K',detail:'s 是上界：∀x∈A，x≤s；s 最小：∀ε>0，存在 x∈A 使 s−ε<x。上确界不必属于 A，但必须属于数系 K。',connection:'把一串数看成一个集合，就从“最小上界”走向“单调序列的终点”。'},
 mono:{tag:'单调 + 有界 → 域内极限',claim:'K 中每个单调递增且有上界的数列，都收敛到 K 中的一个数。递减且有下界的情形同理。',formula:'a₀ ≤ a₁ ≤ ⋯ ≤ M  ⇒  aₙ → ℓ ∈ K',detail:'这里的递增允许相等。有界仅是不会越过某道界线，不是已经证明有终点。极限必须仍在 K 内。',connection:'一组闭区间套的左端点恰好单调递增，并被第一个右端点挡住。'},
 nested:{tag:'非空闭有界区间 + 嵌套 + 长度趋零',claim:'若非空闭有界区间 Iₙ=[aₙ,bₙ]ₖ 满足 Iₙ₊₁⊆Iₙ 且 bₙ−aₙ→0，则它们的交集在 K 中恰有一个点。',formula:'⋂ₙ₌₀^∞ [aₙ,bₙ]ₖ = {ℓ},  ℓ ∈ K',detail:'[a,b]ₖ 表示 {x∈K:a≤x≤b}。本图采用“长度趋零、交点唯一”的版本。在 ℝ 中，不要求长度趋零也能保证非空，但未必唯一。',connection:'对有界数列反复二分，保留含无限多个项的半区间，再从每层选一个更晚的项。'},
 bw:{tag:'有界序列 → 一条收敛子列',claim:'K 中每个有界数列，都有一个收敛到 K 中某点的子列。',formula:'n₁ < n₂ < ⋯ ,   xₙₖ → ℓ ∈ K',detail:'子列只能删项，不能重排；要求保留严格递增的原始下标。不要求原数列收敛。“无限多个项”指无限多个下标，数值可以重复。',connection:'Cauchy 性先给出有界，再把收敛子列的终点传给整条尾部。'},
 cauchy:{tag:'尾部彼此靠近 → 域内极限',claim:'K 中每个 Cauchy 数列，都收敛到 K 中的一个数。',formula:'∀ε>0 ∃N ∀m,n≥N : |xₘ−xₙ|<ε',detail:'Cauchy 条件不预设终点。m 与 n 独立，允许相隔任意远；只看相邻差趋于零远远不够。收敛 ⇒ Cauchy 不需要完备性；反向才需要。',connection:'二分“不是上界”和“是上界”的端点，得到 Cauchy 数列，再找回上确界。'}
};
export function cpEscape(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\"','&quot;');}
const eq=x=>`<div class="cp-equation">${cpEscape(x)}</div>`;
export const cpProofs = {
 'sup-mono':{title:'把数列的值域，交给上确界。',given:'只假设上确界原理；使用单调性与极限的定义。',intro:'给定任意单调递增、有上界的数列 (xₙ)。不是先假定它有极限，而是先为这个值域找一个最小上界。',steps:[
 ['制造集合','令 A={xₙ:n≥0}。它非空，且由题设有上界。上确界原理给出 s=sup A∈K。','A≠∅，A 有上界 ⇒ s=sup A∈K'],
 ['用“最小”挤出一项','给定任意 ε>0，s−ε 不可能仍是 A 的上界；否则 s 不是最小上界。因此有某个 N 使 x_N>s−ε。','s−ε < x_N ≤ s'],
 ['单调性管住整个尾部','对每个 n≥N，单调性给出 x_N≤xₙ，而 s 是上界给出 xₙ≤s。故 |xₙ−s|<ε。','∀n≥N：s−ε < x_N ≤ xₙ ≤ s'],
 ['结论与反向入口','ε 任意，因此 xₙ→s。非增且有下界的数列对 −xₙ 使用同一论证。要反向推出上确界，可沿图继续走完其余四条箭头。','xₙ → sup{x₀,x₁,…} ∈ K']
 ],avoid:'图上的若干 aₙ 只是正例。这里证明的是任意单调有界数列；没有用动画“看起来变平”代替量词。'},
 'mono-nested':{title:'追踪左端点，把极限留在每一层。',given:'只假设单调有界定理；使用保序的极限法则及长度趋零条件。',intro:'给定任意符合条件的 Iₙ=[aₙ,bₙ]ₖ。先确保一个点存在，再单独证明它唯一。',steps:[
 ['左端点单调而有界','嵌套给出 aₙ≤aₙ₊₁≤bₙ₊₁≤bₙ。特别地，(aₙ) 单调递增，且每项都不超过 b₀。','a₀ ≤ a₁ ≤ ⋯ ≤ b₀'],
 ['从数列拿到一个域内点','单调有界定理给出 aₙ→ℓ∈K。固定任意 j，对 n≥j 有 aⱼ≤aₙ≤bⱼ。取极限后 aⱼ≤ℓ≤bⱼ。','∀j：ℓ ∈ [aⱼ,bⱼ]ₖ'],
 ['长度趋零负责唯一性','若 ℓ、r 都属于全部区间，则对每个 n 都有 |ℓ−r|≤bₙ−aₙ。若两点不同，取 ε=|ℓ−r|/2 就与长度趋零矛盾。','0 ≤ |ℓ−r| ≤ bₙ−aₙ → 0'],
 ['分清两个条件的作用','所以交集恰为 {ℓ}。在此证明中，闭性使极限不跑出区间；长度趋零用于唯一性。恒定区间 [0,1] 的交集非空，却不是单点。','⋂ₙ Iₙ = {ℓ}']
 ],avoid:'对每个有限 n，Iₙ 非空，不能单靠这一句话交换量词，推出存在同一个点属于全部 Iₙ。'},
 'nested-bw':{title:'每次保留无限多项，而非屏幕上的多数。',given:'只假设长度趋零的闭区间套定理；阿基米德性保证二分长度趋零。',intro:'给定任意有界数列 (xⱼ)。下面不是在有限散点里猜哪里密集，而是对无限下标集合做存在性论证。',steps:[
 ['把整列放进第一个盒子','有界性让我们选择闭有界区间 I₀=[a,b]，a<b，包含所有项。将它分成两个闭半区间。至少有一个含无限多个项的下标。','无限集合 = 两个有限集合的并？不可能。'],
 ['无限次二分，保留嵌套','在选中的半区间中继续二分，每次选一个含无限多个下标的半区间 Iₖ。于是 Iₖ₊₁⊆Iₖ，长度为 (b−a)2⁻ᵏ→0。','|Iₖ| = (b−a)/2ᵏ → 0'],
 ['先有公共点，再选更晚的项','闭区间套定理给出唯一 ℓ∈⋂Iₖ。递归选 nₖ>nₖ₋₁ 且 xₙₖ∈Iₖ；因为 Iₖ 含无限多个下标，任何有限下标之后仍有可选项。','n₁<n₂<⋯，xₙₖ∈Iₖ，ℓ∈Iₖ'],
 ['区间长度就是误差界','两点同属 Iₖ，所以 |xₙₖ−ℓ|≤|Iₖ|→0。于是得到域内收敛子列。数值相同也可能有无限多个下标，例如常数列。','|xₙₖ−ℓ| ≤ (b−a)2⁻ᵏ → 0']
 ],avoid:'有限点图不能判定“含无限多个项”。本实验的偶数子列由公式明确指定，不声称实现任意无限序列的自动抽取算法。'},
 'bw-cauchy':{title:'一条子列到达后，整个尾部都跟上。',given:'只假设 Bolzano–Weierstrass；其余来自 Cauchy 定义与三角不等式。',intro:'给定任意 Cauchy 数列 (xₙ)。先证明有界，才能调用 BW；不能一开始就把未知终点写进定义。',steps:[
 ['Cauchy 先保证有界','在 Cauchy 条件里取 ε=1，得到 N。对 n≥N，有 |xₙ|≤|x_N|+1。前 N 项有限，与这个尾部界一起给出全列的一个界。','|xₙ| ≤ max{|x₀|,…,|x_N|}+1'],
 ['BW 提供一个终点','由 BW，存在严格递增下标 nₖ，使 xₙₖ→ℓ∈K。到这里，我们只知道子列收敛，还不能省去下一步。','xₙₖ → ℓ ∈ K'],
 ['用 ε/2 连起两段距离','给定 ε>0。先选 N 使所有 m,n≥N 时 |xₘ−xₙ|<ε/2，再选 k 使 nₖ≥N 且 |xₙₖ−ℓ|<ε/2。','|xₙ−ℓ| ≤ |xₙ−xₙₖ| + |xₙₖ−ℓ| < ε'],
 ['固定的那一项，管住所有晚项','上式对每个 n≥N 都成立，所以 xₙ→ℓ。若删去 Cauchy 条件，(−1)ⁿ 就是“子列收敛、全列不收敛”的反例。','∀ε>0 ∃N ∀n≥N：|xₙ−ℓ|<ε']
 ],avoid:'“有一条收敛子列”不等于“全列收敛”。实验中 zⱼ=(−1)ʲaⱼ 不是 Cauchy；这一箭头须应用于 Cauchy 的 aₙ，而不是 zⱼ。'},
 'cauchy-sup':{title:'不先借用上确界，二分构造它。',given:'只假设 Cauchy 完备性；阿基米德性保证二分长度趋零。',intro:'给定任意非空有上界的 A⊆K。整个过程中不能先写 s=sup A；那个 s 正是我们需要证明存在的对象。',steps:[
 ['一个不是上界，一个是上界','取 x₀∈A，令 a₀=x₀−1，则 a₀ 不是上界；取任一上界 b₀。二分中点 m：若 m 是上界，保留 [aₙ,m]；否则保留 [m,bₙ]。','aₙ 不是上界；bₙ 是上界'],
 ['只靠宽度，证明 Cauchy','不变量在二分中保持，且 bₙ−aₙ=(b₀−a₀)2⁻ⁿ。所有 m,n≥N 的 aₘ,aₙ 都落在 [a_N,b_N]，所以二者距离至多为该宽度。','|aₘ−aₙ| ≤ (b₀−a₀)2⁻ᴺ → 0'],
 ['完备性给点，再验证它是上界','Cauchy 完备性给 aₙ→s∈K，宽度趋零又给 bₙ→s。每个 x∈A 都满足 x≤bₙ，取极限得 x≤s。因此 s 是上界。','∀x∈A：x≤bₙ ⇒ x≤s'],
 ['验证最小性，闭合证明环','若 c<s，由 aₙ→s 可取 n 使 aₙ>c。因 aₙ 不是上界，存在 x∈A 使 x>aₙ>c；所以 c 不是上界。故 s=sup A。','c<s ⇒ ∃x∈A：c<aₙ<x ⇒ s=sup A']
 ],avoid:'一般集合中“m 是否为上界”是含全称量词的逻辑判定，不一定有计算算法。演示的二次不等式是可精确判定的特例。有理终点刚好命中时，上界构造把等号归入上界侧；展示区间为统一保留宽度把等号归入左侧，二者不可混称。'}
};
export const cpQuestions = [
 {id:'domain',title:'同一条逼近 √2 的有理数列，切换数系后哪句话正确？',options:['在 ℚ 中它就不再是 Cauchy 数列。','它在两边都满足 Cauchy 条件，但只在 ℝ 中有极限。','多计算一些项，就会精确得到一个有理终点。'],correct:1,reason:'尾部距离不因环境从 ℝ 换成 ℚ 而改变。不同的是极限必须属于所讨论的数系；精确有理运算不会突然生成 √2。'},
 {id:'quantifiers',title:'每个 [aₙ,bₙ]∩ℚ 都非空。能直接推出它们的无限交集非空吗？',options:['能，因为可以每次选一个有理数。','不能；∀n∃qₙ 与 ∃q∀n 不是同一个量词顺序。','只有当每个区间含无限多个有理数时才一定能。'],correct:1,reason:'在 √2 的构造中，任意有限交集都含无限多个有理数，而无限交集在 ℚ 内为空。区间长度趋零且闭、嵌套仍不能替代数系的完备性。'},
 {id:'bw',title:'zⱼ=(−1)ʲaⱼ 有界。在 ℝ 中，BW 究竟保证什么？',options:['整列都收敛。','至少一条按原下标递增选出的子列收敛。','每一条子列都收敛，而且极限相同。'],correct:1,reason:'偶数项趋于 √2，奇数项趋于 −√2。BW 只承诺存在一条域内收敛子列。没有 Cauchy 条件，不能把这个终点传给全列。'},
 {id:'increments',title:'换一个新序列：Hₙ=1+1/2+⋯+1/n。相邻差趋零，是否 Cauchy？',options:['是，Hₙ₊₁−Hₙ→0 就够了。','不是，因为 H₂ₙ−Hₙ≥1/2。','仅凭这两个解析式无法判断。'],correct:1,reason:'H₂ₙ−Hₙ=∑ⱼ₌ₙ₊₁²ⁿ 1/j≥n·1/(2n)=1/2。任意晚的尾部仍能找出相距至少 1/2 的两项；m,n 必须允许独立且相隔很远。'},
 {id:'intervals',title:'想改动闭区间套的条件，哪组结论准确？',options:['(0,1/n) 的交集是 {0}；[0,1] 的恒定套交集只有一个点。','(0,1/n) 交集为空；[0,1] 的恒定套交集非空但不唯一。','只要长度趋零，闭性和嵌套都不重要。'],correct:1,reason:'0 不属于任何开区间 (0,1/n)，正数最终也被排除。恒定套 [0,1] 的交集仍为 [0,1]。闭性与长度趋零扮演不同角色。'},
 {id:'normal',title:'把目标改成 3/2，在 ℚ 中也得到上确界和极限。这说明什么？',options:['ℚ 其实也完备。','本例成功，但不能证明“每一个”都成功；√2 仍是反例。','只要集合都是有理数，最小上界就必须是无理数。'],correct:1,reason:'一个正例只能说明一个构造成立；一个符合前提而违反结论的反例，已经足以否定普遍命题。图中 ℚ 的五个节点不会因这个正例变为成立。'}
];
function cpJourney(s){const step=s.screen==='map'?0:s.screen==='proof'?3:s.screen==='challenge'?4:s.domain==='Q'?2:1;return `<nav class="cp-journey" aria-label="完备性学习路径">${['看见等价','同一构造','切换数系','闭合证明','自己判断'].map((t,i)=>`<button data-cp-stage="${i}"${i===step?' aria-current="step"':''}><span>0${i+1}</span><strong>${t}</strong><i aria-hidden="true">${i===4?'✓':'→'}</i></button>`).join('')}</nav>`;}
function cpContext(s){return `<div class="cp-context"><div><span class="cp-context-label">数系 K</span><div class="segmented" aria-label="选择数系"><button data-cp-domain="R" aria-pressed="${s.domain==='R'}">ℝ 实数</button><button data-cp-domain="Q" aria-pressed="${s.domain==='Q'}">ℚ 有理数</button></div></div><label>共同的构造目标 <select id="cp-target">${Object.values(completenessTargets).map(t=>`<option value="${t.id}"${s.target===t.id?' selected':''}>${t.label} · ${t.description}</option>`).join('')}</select></label><span class="cp-continuity-note">切换视角，不重置你的第 <b id="cp-context-n">${s.n}</b> 次二分。</span></div>`;}
export function completenessHeader(s){const title=s.screen==='map'?'五种定理，同一个终点。':s.screen==='proof'?'走完一圈，才叫等价。':s.screen==='challenge'?'最后一程，由你判断。':cpNode(s.node).question;return `<section class="page-heading cp-heading"><div><div class="breadcrumb">实验室 <span>/</span> 实数基础 <span>/</span> 完备性</div><span class="eyebrow">EXPERIMENT 04 <span>—</span> ONE COMPLETENESS, FIVE PERSPECTIVES</span><h1 id="cp-title" tabindex="-1">${title}</h1><p class="page-subtitle">每一步都在数系里，终点却未必在。沿着同一个构造，把五条命题连成一件事。</p></div><div class="heading-actions"><button class="button subtle" data-cp-action="reset">${icon('reset')} 重置</button><button class="button subtle" data-action="share">${icon('share')} 分享实验</button></div></section>${cpJourney(s)}${cpContext(s)}`;}
function cpAssumptions(){return `<details class="cp-assumptions"><summary>这张等价图的共同前提，为什么不能省？</summary><p>在经典数学的<strong>阿基米德有序域 K</strong>中讨论：它具有与有理数相容的次序、四则运算，并满足 ∀x∈K，∃n∈ℕ，n>x。由此，对任意 ε>0，充分大的 n 都有 2⁻ⁿ&lt;ε。</p><p>ℝ 与 ℚ 都满足这些基础条件。此图没有把“任何有序域”都当成实数系：特别是“Cauchy 完备 ⇒ 上确界原理”不能随意删去阿基米德假设。箭头给的是逻辑蕴含，不是计算流程。</p><p>本图的闭区间套使用“非空、闭、有界、嵌套、长度趋零 → 唯一交点”的版本；不趋零的非空交集版本另在该节点说明。所有极限、上确界与交点都要求属于 <em>K 本身</em>。</p></details>`;}
function mapPage(s){return `<div class="cp-map-layout"><section class="card cp-map-card"><div class="cp-card-head"><div><span class="eyebrow">EQUIVALENCE, NOT A LIST</span><h2>任一出发，都能回到起点。</h2></div><span class="cp-legend"><i></i> 单向证明 · 绕环得到所有方向</span></div><div id="cp-graph">${completenessGraph(s)}</div><div class="cp-map-foot">点击<strong>节点</strong>进入同一个实验的不同视角；点击<strong>箭头</strong>检查“为什么能推出”。绿色箭头在 ℚ 下仍是条件蕴含，不表示五个前提在那里成立。</div>${cpAssumptions()}</section><aside class="card cp-map-inspector"><span class="eyebrow">ONE QUESTION TO START</span><h2>能逼近，<br>就一定能到达吗？</h2><p>从 [1,2] 开始，每次只比较一个<strong>有理数的平方</strong>，保留目标所在的半区间。</p><div class="cp-mini-construction" id="cp-map-mini"></div><div class="cp-map-outcome" id="cp-map-outcome"></div><button class="button primary full-width" data-cp-action="start">从一次二分开始 <span>→</span></button><div class="cp-route-builder"><span class="eyebrow">CHOOSE YOUR PROOF ROUTE</span><label>从 <select id="cp-from">${completenessNodes.map(n=>`<option value="${n.id}"${s.from===n.id?' selected':''}>${n.short}</option>`).join('')}</select></label><label>到 <select id="cp-to">${completenessNodes.map(n=>`<option value="${n.id}"${s.to===n.id?' selected':''}>${n.short}</option>`).join('')}</select></label><div id="cp-route-description"></div><button class="text-button" data-cp-action="route">沿这条路径检查 →</button></div></aside></div><div class="cp-start-note"><strong>一个反例，五种读法。</strong><p>√2 的缺失同时击中最小上界、序列终点、区间交点、子列终点与 Cauchy 终点；3/2 的正例提醒你：一个构造成功，不等于整个数系完备。</p></div>`;}
function lenses(s){return `<nav class="cp-lenses" aria-label="同一个构造的五个视角">${completenessNodes.map((n,i)=>`<button data-cp-node="${n.id}" aria-current="${s.node===n.id?'true':'false'}"><small>0${i+1} · ${n.code}</small><strong>${n.short}</strong></button>`).join('')}</nav>`;}
function controls(s){return `<aside class="card cp-controls"><span class="eyebrow">KEEP THE SAME CONSTRUCTION</span><h2>不是五个例子，是同一件事。</h2><p class="cp-muted">a₀=1，b₀=2。若中点 m²≤d，更新左端；否则更新右端。等号放左侧，宽度始终减半。</p><div class="slider-block"><label class="control-label" for="cp-depth">二分层数 n <output id="cp-depth-value">${s.n}</output></label><input id="cp-depth" type="range" min="0" max="32" step="1" value="${s.n}"><div class="slider-endpoints"><span>0 · [1,2]</span><span>32 · 精确分数</span></div></div><div class="cp-play-controls"><button class="button" data-cp-action="prev" aria-label="退回上一次二分">−</button><button class="button primary" data-cp-action="play" aria-pressed="false">▷ 逐次二分</button><button class="button" data-cp-action="next" aria-label="再二分一次">+</button></div>${s.node==='nested'?'<label class="cp-checkbox"><input id="cp-zoom" type="checkbox"'+(s.zoom?' checked':'')+'> 放大最后几层（横轴重标）</label>':''}${s.node!=='cauchy'?'<label class="cp-checkbox"><input id="cp-reference" type="checkbox"'+(s.reference?' checked':'')+'> 显示 ℝ 中的目标参照点</label>':''}<div class="cp-exact-note">BigInt 整数交叉相乘判定。分数是精确值；小数与像素仅作近似显示。</div>${s.node==='sup'?`<div class="cp-special-control"><h3>挑战一个“最小上界”</h3><p>A={x∈K:0≤x，x²&lt;d}。给出一个有理候选，检查它。</p><form id="cp-upper-form"><label for="cp-candidate">有理候选（整数、有限小数或 p/q）</label><div><input id="cp-candidate" type="text" value="${s.candidate}" maxlength="24" autocomplete="off" spellcheck="false"><button class="button" type="submit">检查</button></div></form><div id="cp-upper-feedback" role="status"></div></div>`:''}${s.node==='bw'?`<div class="cp-special-control"><h3>在来回跳动中，保留一条路</h3><p>zⱼ=(−1)ʲaⱼ，j≥0。保留原始下标，不能重排。</p><div class="segmented"><button data-cp-parity="all" aria-pressed="${s.parity==='all'}">整列</button><button data-cp-parity="even" aria-pressed="${s.parity==='even'}">偶数项</button><button data-cp-parity="odd" aria-pressed="${s.parity==='odd'}">奇数项</button></div></div>`:''}${s.node==='cauchy'?`<div class="cp-special-control"><h3>尾部的两项，可以相隔很远</h3><div class="slider-block"><label class="control-label" for="cp-epsilon">ε=2⁻ᵉ <output id="cp-epsilon-value"></output></label><input id="cp-epsilon" type="range" min="0" max="20" step="1" value="${s.epsilon}"></div><div class="slider-block"><label class="control-label" for="cp-m">m=N+ <output id="cp-m-value"></output></label><input id="cp-m" type="range" min="0" max="120" value="${s.m}"></div><div class="slider-block"><label class="control-label" for="cp-k">j=N+ <output id="cp-k-value"></output></label><input id="cp-k" type="range" min="0" max="180" value="${s.k}"></div><p>N 就是上方的 n。证书约束所有 m,j≥N，不只是画出的两项。</p><button class="button full-width" data-cp-action="certify">跳到可保证的 N</button></div>`:''}<button class="text-button" data-cp-action="export">导出精确构造 CSV ↗</button></aside>`;}
function exampleProof(s){const t=cpTarget(s.target);return `<details class="cp-proof-detail"><summary>这一构造的无限过程：解析证明，而非动画判断</summary><div><h3>先构造，不先借用 √d。</h3><p>对 d=${t.parameter}，从 [1,2] 逐次二分，整数交叉相乘保证对每个 n 都有</p>${eq('1 ≤ aₙ ≤ aₙ₊₁ < bₙ₊₁ ≤ bₙ ≤ 2，  bₙ−aₙ=2⁻ⁿ，  aₙ²≤d<bₙ²。')}<p>所以 0≤d−aₙ²&lt;(bₙ−aₙ)(bₙ+aₙ)≤4·2⁻ⁿ。每项都是有理数；所有晚于 N 的项都在 [a_N,b_N]，从而 |aₘ−aⱼ|≤2⁻ᴺ。由阿基米德性，这给出 Cauchy 条件。</p><h3>在 ℝ 中，完备性让这个终点存在。</h3><p>可用图中的任一等价性质拿到极限 α∈ℝ。由 aₙ²→d 得 α²=d，且 α≥1。这才可以把它识别为 ${t.label}。图上提前显示的 √d 是已知实数系中的参照，不是构造算法调用的预言机。</p><h3>在 ℚ 中，检查同一个终点是否可用。</h3>${t.rational?`<p>d=9/4 时，n≥1 的 aₙ=3/2，bₙ=3/2+2⁻ⁿ；序列在 ℚ 内也收敛，区间交集为 {3/2}。A 的上确界是 3/2，即使它不属于严格不等式定义的 A。这个正例不证明 ℚ 完备。</p>`:`<p>若存在有理极限 q，则平方的连续性与上述残差界给 q²=${t.parameter}。把 q=p/r 写成最简分数：p²=${t.parameter}r² 蕴含素数 ${t.parameter} 整除 p，继而也整除 r，矛盾。故域内极限不存在。</p><p>若有 q∈⋂([aₙ,bₙ]∩ℚ)，同样由 aₙ²≤q²≤bₙ² 与长度趋零得到 q²=${t.parameter}，矛盾。任一有限交集仍是一个非退化有理端点区间，在 ℚ 中含无限多个点。</p>`}<h3>BW：不要把整列与子列混淆。</h3><p>zⱼ=(−1)ʲaⱼ 有界，偶数子列 z₂ₖ=a₂ₖ→α，奇数子列 z₂ₖ₊₁=−a₂ₖ₊₁→−α，因此整列在 ℝ 中也不收敛。${t.rational?'两条子列在 ℚ 中同样收敛到 ±3/2。':'若任一子列在 ℚ 中收敛到 q，则其平方也收敛到 q²；但由残差界，该平方必趋于 d，因此又要求 q²=d，不可能。'}</p><h3>上确界：排除所有错误的候选。</h3><p>设 q≥0 为有理候选。若 q²&lt;d，令 h=min{1,(d−q²)/[2(2q+1)]}，则 q+h>q 且 (q+h)²&lt;d，故 q 不是上界。若 q²>d，令 r=(q+d/q)/2，则 0&lt;r&lt;q 且 r²−d=(q²−d)²/(4q²)>0，故 q 不是最小上界。q&lt;0 时 0∈A 已经反驳它。只有 q²=d 才可能成为上确界。</p><p class="cp-proof-caveat">这些公式覆盖所有 n 或候选 q。屏幕上显示的有限分数、散点和动画，均不作为一般定理的证明。</p></div></details>`;}
function explorePage(s){const d=cpDefinitions[s.node];return `${lenses(s)}<section class="cp-definition"><span class="eyebrow">${cpNode(s.node).code} · ${d.tag}</span><h2>${cpEscape(d.claim)}</h2>${eq(d.formula)}<p>${cpEscape(d.detail)}</p></section><div class="cp-workspace">${controls(s)}<div class="cp-visual-column"><section class="card cp-visual"><div class="cp-card-head"><div><span class="eyebrow">ONE EXACT CONSTRUCTION · FIVE READINGS</span><h2 id="cp-plot-title"></h2></div><span class="cp-finite-badge">有限示意 ≠ 无限证明</span></div><div class="cp-mobile-quick"><div class="slider-block"><label class="control-label" for="cp-depth-mobile">二分层数 n <output id="cp-depth-mobile-value">${s.n}</output></label><input id="cp-depth-mobile" type="range" min="0" max="32" step="1" value="${s.n}"></div><div><button class="button" data-cp-action="prev" aria-label="移动端：退回上一步">−</button><button class="button primary" data-cp-action="play" aria-pressed="false">▷ 逐次二分</button><button class="button" data-cp-action="next" aria-label="移动端：再二分一步">+</button></div></div><div id="cp-primary-plot"></div><div class="cp-live" id="cp-live"></div><div class="cp-interpretation" id="cp-interpretation" aria-live="polite"></div></section><section class="card cp-comparison"><div class="cp-card-head"><div><span class="eyebrow">THE SAME TERMS, A DIFFERENT AMBIENT FIELD</span><h2>没有换数列。只问终点属于谁。</h2></div></div><div id="cp-domain-comparison"></div><p class="cp-density-note">ℚ 在 ℝ 中稠密；这里的“缺失”不是画得出的正宽度裂缝。空心目标只标记它不属于 ℚ，数轴仍是借用的 ℝ 坐标背景。</p></section></div></div>${exampleProof(s)}<details class="cp-ledger"><summary>打开精确分数账本 · 每一层到底留下了什么？</summary><div id="cp-ledger"></div></details><div class="cp-next-banner"><div><span class="eyebrow">KEEP THE THREAD</span><h2>${d.connection}</h2></div><button class="button primary" data-cp-action="next-lens">继续到下一个视角 →</button><button class="button" data-cp-action="outgoing-proof">这条箭头为什么成立？</button></div>`;}
function proofPage(s){const e=cpEdge(s.edge),p=cpProofs[e.id];return `<div class="cp-proof-context"><button class="text-button" data-cp-action="map">← 返回等价关系图</button><strong>${cpNode(e.from).short} <span>→</span> ${cpNode(e.to).short}</strong><span>只借用起点，不预设终点</span></div><div class="cp-proof-layout"><article class="card cp-proof-article"><span class="eyebrow">A LINK IN THE CYCLE</span><h2>${p.title}</h2><p class="cp-proof-intro">${p.intro}</p><div class="cp-proof-given"><strong>允许使用</strong> ${p.given}</div><nav class="cp-proof-steps" aria-label="证明的四个步骤">${p.steps.map((step,i)=>`<button data-cp-proof-step="${i}" aria-current="${s.proofStep===i?'step':'false'}"><span>0${i+1}</span>${step[0]}</button>`).join('')}</nav><section id="cp-proof-current" aria-live="polite"></section><div class="cp-proof-step-actions"><button class="button" data-cp-action="proof-prev">← 上一步</button><button class="button primary" data-cp-action="proof-next">下一步 →</button></div><details class="cp-proof-full"><summary>一次读完整条证明</summary>${p.steps.map((st,i)=>`<section><h3>${i+1}. ${st[0]}</h3><p>${cpEscape(st[1])}</p>${eq(st[2])}</section>`).join('')}</details><div class="cp-proof-caveat">${p.avoid}</div></article><aside class="cp-proof-side"><section class="card"><span class="eyebrow">RETURN TO THE SAME EXAMPLE</span><h3>证明一般命题，<br>再回到同一条逼近。</h3><div id="cp-proof-visual"></div><p>这是第 ${s.n} 层的有限示例，用于对应构造，不是上面任意对象证明的替代。</p><button class="button full-width" data-cp-action="proof-explore">带着参数回到实验 →</button></section><section class="card"><span class="eyebrow">FIVE LINKS CLOSE THE CYCLE</span><div class="cp-proof-ring">${completenessEdges.map(edge=>`<button data-cp-edge="${edge.id}" aria-current="${s.edge===edge.id?'step':'false'}"><span>${cpNode(edge.from).short}</span> → <span>${cpNode(edge.to).short}</span></button>`).join('')}</div><p>有向环里，从任何节点都能走到其余节点。无需把 20 条方向全部画出来，也不把反向箭头当成“显然”。</p></section></aside></div>${cpAssumptions()}<div class="cp-next-banner"><div><span class="eyebrow">CONTINUE THE PROOF CYCLE</span><h2>这一条完成后，继续下一条。</h2></div><button class="button primary" data-cp-action="next-edge">${cpNode(e.to).short} → ${cpNode(cpEdge(completenessEdges[(completenessEdges.indexOf(e)+1)%5].id).to).short}</button></div>`;}
function challengePage(){return `<div class="cp-challenge-intro"><span class="eyebrow">TRANSFER, NOT RECALL</span><h2>改变一个条件，结论还在吗？</h2><p>先提交判断，再看解析理由。可以随时回到同一个实验；已选答案仅留在当前页面会话中，不写入分享链接。</p></div><form id="cp-quiz"><div class="cp-question-grid">${cpQuestions.map((q,i)=>`<fieldset class="card cp-question"><legend><span>0${i+1}</span>${q.title}</legend>${q.options.map((o,j)=>`<label><input required type="radio" name="cp-${q.id}" value="${j}"><span>${o}</span></label>`).join('')}<div class="cp-feedback" id="cp-feedback-${q.id}" hidden></div></fieldset>`).join('')}</div><div class="cp-quiz-actions"><button class="button primary" type="submit">核对判断与理由</button><output id="cp-quiz-score" aria-live="polite"></output><button class="text-button" type="button" data-cp-action="quiz-reset">清空作答</button><button class="text-button" type="button" data-cp-action="start">带着问题回实验 →</button></div></form><div class="cp-takeaway"><span class="eyebrow">THE ONE IDEA TO KEEP</span><h2>完备，不是每次都到达。<br>是满足条件时，永远不会缺一个终点。</h2><p>上确界、单调极限、区间交点、子列极限与 Cauchy 极限，是“终点仍在数系中”的五种精确表达。</p></div>`;}
export function completenessPage(s){return completenessHeader(s)+({map:mapPage,explore:explorePage,proof:proofPage,challenge:challengePage}[s.screen])(s);}
