import { ipCurves, ipSurfaces } from './implicit-math.js';
import { ipSteps } from './implicit-state.js';
import { icon } from './icons.js';
import { pageGuide } from './page-guide.js';
export function ipEscape(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export const ipStages={
 curve:{name:'补回误差',title:'只动 x，为什么还要动 y？',task:'先拖橙色手柄改变自由变量。播放三步：离开约束、抵消一阶误差、补上高阶修正。蓝色切线预测不是绿色曲线本身。',next:'什么时候，y 无法有效修正？'},
 condition:{name:'选对依赖变量',title:'曲线没坏，可能只是“解谁”选错了。',task:'把圆上的工作点拖到最右端，观察 F_y 变成 0；再交换自由与依赖变量。然后试试条件失败却仍有光滑隐函数的例子。',next:'现在，同时改变两个自由变量。'},
 surface:{name:'曲面上的修正',title:'两项输入变化，补回一段高度。',task:'在右侧输入平面拖动 (dx,dy)，看它如何在曲面上制造误差；由 dz 修正。切平面同时预测所有方向，不只是当前截线。',next:'如果有两个约束、两个修正变量呢？'},
 vector:{name:'解一台线性机器',title:'Dg：把自由变化，译成依赖修正。',task:'左侧改变两个自由变量；右侧是依赖变量的变化。下方的约束空间里，D_yF 把修正送回去抵消误差。把 λ 降到 0，看看哪一种能力丢失了。',next:'我能自己区分 g、Dg 与 DF 了吗？'}
};
export const ipProofs={
 curve:{title:'先保证 g 存在，再对恒等式求导。',given:'F 在 (a,b) 的开邻域内 C¹，F(a,b)=0，F_y(a,b)≠0。标量隐函数定理给出邻域 U、V 和唯一 C¹ 函数 g:U→V，且 g(a)=b。唯一性只在 U×V 内。',steps:[
 ['自由改变产生误差','把 x 从 a 改成 a+h，y 暂时不动。真实误差是 F(a+h,b)，其一阶项为 F_x(a,b)h。F 的值是约束空间中的数，不是 y 坐标。','F(a+h,b)=F_x(a,b)h+o(|h|)'],
 ['依赖改变补回一阶误差','若同时改变 y 一个 k，一阶约束变化是 F_x h+F_y k。要求它为 0。F_y≠0 使任意小的一阶误差都有唯一的线性修正。','F_x h+F_y k=0 ⇒ k=−(F_x/F_y)h'],
 ['链式法则读出真正的导数','已由定理得到 F(x,g(x))≡0。对 x 求导，得到 F_x(x,g(x))+F_y(x,g(x))g′(x)=0。公式中的两个偏导在约束曲线上的同一点取值。','g′(x)=−F_x(x,g(x))/F_y(x,g(x))'],
 ['一阶修正不是精确回到曲线','由 g 可微，g(a+h)−g(a)=g′(a)h+o(|h|)。图中的切线点还可能有残余约束。圆例中若 k=−a h/b，则残余恰为 h²+k²；缩小 h 才让它高阶消失。','F(a+h,b+k)=h²+k²（圆上、一阶抵消之后）']
 ],warning:'只把 F_x+F_y g′=0 解出来，并没有证明 g 存在。有限动画不是存在性证明；“存在且唯一”是局部结论，不是整个零集只有一支。'},
 condition:{title:'足够条件，不是必要条件。',given:'检验的是“当前选定依赖变量的偏导”。∇F≠0 表示至少有一个坐标方向可用，但不保证每个方向都能作为依赖变量。',steps:[
 ['圆的最右端无法解成 y=g(x)','在 (1,0)，F_y=0。任意小的左侧 x<1 都有靠近 0 的正负两个 y，而右侧 x>1 无实数解。因此整个零集不能在该点的开邻域内成为 y 的唯一图像。','y=±√(1−x²)；x>1 时无解'],
 ['交换角色可以救回图像','在同一点 F_x=2≠0，所以把 y 当自由变量、x 当依赖变量，可得到 x=√(1−y²)。曲线本身光滑；是之前的投影方向发生折叠。','dx/dy=−F_y/F_x=0（在 (1,0)）'],
 ['零偏导也不必导致失败','F=(y−x)³ 在零集上梯度为零，但 F=0 等价于 y=x。g(x)=x 是唯一光滑隐函数，g′=1；偏导比值是 0/0，不能拿来计算。','F_y=0 ⇏ “不存在隐函数”'],
 ['不同失败，不能混为一种','F=y³−x 在原点有唯一连续解 y=∛x，但差商 |h|^(−2/3) 发散，没有有限导数。F=y²−x² 有两支交叉；选一支 y=x 是光滑的，却不能代表全部邻近零集。','唯一性、可微性、判别条件，是三件不同的事']
 ],warning:'数值接近 0 不是等于 0。实验把精确奇异的预设与小而非零的偏导区分；小分母可能使修正敏感，并不自动否定局部定理。'},
 surface:{title:'把标量修正，接到两维输入后面。',given:'F:U⊂ℝ³→ℝ 在 (a,b,c) 附近 C¹，F(a,b,c)=0，F_z(a,b,c)≠0。把前两个坐标组成自由变量 X=(x,y)，依赖变量是 z。',steps:[
 ['自由变化来自两个方向','只改变 (x,y)，线性约束误差是 F_x dx+F_y dy。它是一个数；两个输入对同一个约束的贡献相加。','D_XF=(F_x  F_y)，尺寸 1×2'],
 ['高度变化仍只修正一个约束','高度变化 dz 对约束的一阶贡献是 F_z dz。令总和为 0，即可为每个输入向量求出一个高度修正。','dz=−(F_x/F_z)dx−(F_y/F_z)dy'],
 ['这行数字就是 Dg','局部 z=g(x,y)。Dg(a,b):ℝ²→ℝ 是导数线性映射；它的标准坐标矩阵是一行两列，而 g 的值只是一段高度。','Dg=(−F_x/F_z  −F_y/F_z)，dz≈Dg·(dx,dy)ᵀ'],
 ['梯度与切平面说的是同一件事','切向量是 (dx,dy,Dg·(dx,dy))，与 ∇F 正交。对二次曲面 z=x²+xy+y²，真实高度与切平面之差是 dx²+dx·dy+dy²，绝对值≤(3/2)‖(dx,dy)‖²。','∇F·(dx,dy,dz)=0；归一化高度误差≤(3/2)‖(dx,dy)‖']
 ],warning:'F_z≠0 在基点处保证某个邻域，不保证任意大的输入步长都可用。球面例子中目标越出圆盘时，当前上半球参考高度未定义；不能继续外推成真实解。'},
 vector:{title:'一般公式，是“误差传入—修正传回”。',given:'F:U⊂ℝⁿ×ℝᵐ→ℝᵐ 为 C¹，(a,b)∈U，F(a,b)=0。记 A=D_xF(a,b) 为 m×n，B=D_yF(a,b) 为 m×m，并假设 B 可逆。以下存在性证明以逆函数定理为前提。',steps:[
 ['把约束值当成新坐标','构造 H(x,y)=(x,F(x,y))。它的导数是分块矩阵 [[I,0],[A,B]]，行列式为 det B≠0，因此逆函数定理给出 (a,b) 附近的 C¹ 局部逆。','DH(a,b)=[[I_n,0],[A,B]]'],
 ['局部逆真正保证存在和唯一','在像空间取足够小的 (x,0)，局部逆返回 (x,g(x))。缩小为乘积邻域后，附近零集恰好是这张图像。这一步保证 g 存在，而不只是猜一个导数公式。','F(x,g(x))=0，g(a)=b，g 在邻域内 C¹'],
 ['链式法则给出一个矩阵方程','对 x 求导：A+B Dg=0。注意 B 左乘 Dg，因为先由 Dg 把 dx 变成 dy，再由 B 把 dy 变成约束变化。','A_(m×n)+B_(m×m) Dg_(m×n)=0'],
 ['解这个线性系统，读出 Dg','左乘 B⁻¹，得到 Dg=−B⁻¹A。输入 dx 经 A 产生约束误差，取负后经 B⁻¹ 返回依赖空间。逆只作用于方阵 B；整个 DF=[A B] 通常不是方阵。','dx → A dx → −A dx → dy=−B⁻¹A dx']
 ],warning:'可逆 B 保证唯一的一阶修正和局部 C¹ 图像；它不是“牛顿法从任何初值都收敛”的保证。线性修正、有限步精确解、导数本身，必须分开。'}
};
export const ipQuestions=[
 {id:'meaning',q:'g:ℝ²→ℝ³。Dg 是什么？',options:['一个三维位置','一个 3×2 矩阵表示的线性映射，把 dx 变成一阶 dy','约束函数 F 本身'],correct:1,why:'g(a) 是依赖变量的位置；Dg(a) 作用于小输入变化，输出依赖变量的一阶变化。'},
 {id:'base',q:'F_y≠0 就能直接在任意点套用零约束的隐函数定理吗？',options:['能，不需要其他条件','还要 C¹ 邻域、基点 F=0 等前提','只要画面上接近曲线即可'],correct:1,why:'本模块使用标准 C¹ 隐函数定理，并在满足约束的基点线性化。非零水平集也可研究，但要先将方程改为 F−c=0。'},
 {id:'circle',q:'圆在 (1,0) 处，哪个说法对？',options:['整条圆不光滑','应改为局部解 x=g(y)，不能唯一局部解 y=g(x)','所有方向都能解'],correct:1,why:'F_x=2，F_y=0。竖直切线妨碍用 x 参数化，却不妨碍用 y 参数化。'},
 {id:'flat',q:'(y−x)³=0 的 F_y=0，说明什么？',options:['不存在隐函数','g 必不可微','这个判据不适用；直接化简仍得 g(x)=x'],correct:2,why:'判据是充分条件，不是必要条件；0/0 不能被当作 g′ 的数值。'},
 {id:'residual',q:'一阶修正满足 A dx+B dy=0，有限步后的 F 一定为 0 吗？',options:['一定','不一定，还可能剩高阶余项','只有 dx=1 才一定'],correct:1,why:'被抵消的是线性化的约束变化。真实非线性函数仍可能有高阶项。'},
 {id:'surface',q:'z=g(x,y) 时，Dg 的形状是什么？',options:['1×2，输入两维位移，输出一维高度变化','2×1，输入高度，输出两个坐标','3×3，等于 DF'],correct:0,why:'Dg=(g_x,g_y)。它不是三维位置，也不是 F:ℝ³→ℝ 的完整梯度。'},
 {id:'singular',q:'B 奇异时，线性修正方程 B dy=−A dx 会怎样？',options:['任何误差都无解','可能无解，也可能有无穷多解；不再对任意误差唯一可解','总有一个最好的解，所以定理仍直接适用'],correct:1,why:'误差在像空间外时无解；在像空间内时有解但因非零核不唯一。选最小范数解不是隐函数定理的唯一性。'},
 {id:'order',q:'哪个是一般隐函数导数的公式？',options:['Dg=−A B⁻¹','Dg=−B⁻¹ A','Dg=−(DF)⁻¹'],correct:1,why:'A:自由空间→约束空间；B⁻¹:约束空间→依赖空间。顺序由映射的输入输出决定。DF 通常是矩形矩阵。'}
];
const eq = t=>`<div class="ip-equation">${t}</div>`;
export function ipMatrixHTML(A,label){if(A===null)return `<span class="ip-undefined">${label} 未定义</span>`;return `<span class="ip-matrix-wrap"><span>${label}</span><span class="ip-matrix" style="--ip-cols:${A[0].length}">${A.flat().map(x=>`<span>${ipEscape(typeof x==='string'?x:Number(x.toFixed(4)))}</span>`).join('')}</span></span>`;}
function range(id,label,min,max,step,value){return `<div class="slider-block"><label class="control-label" for="ip-${id}">${label}<output id="ip-${id}-value"></output></label><input id="ip-${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;}
function controls(s){const curve=['curve','condition'].includes(s.step);return `<aside class="card ip-controls"><span class="eyebrow">YOUR TURN · 改变，然后补回</span><h2>保持约束，需要怎样的修正？</h2><div class="ip-phase-buttons">${['只动自由变量','一阶修正','精确分支对照'].map((t,i)=>`<button data-ip-phase="${i+1}"><small>0${i+1}</small>${t}</button>`).join('')}</div>${range('progress','过程进度',0,3,.01,s.progress)}<button class="button primary full-width" data-ip-action="play" aria-pressed="false">${icon('play')} 播放误差 → 修正</button><p class="ip-small" id="ip-phase-description"></p><div class="ip-control-divider"></div>${curve?`
 <label class="ip-label" for="ip-curve">零约束与对照</label><select id="ip-curve">${Object.entries(ipCurves).map(([k,v])=>`<option value="${k}" ${s.curve===k?'selected':''}>${v.name}</option>`).join('')}</select><div class="ip-role"><button data-ip-dep="y" aria-pressed="${s.dep==='y'}">自由 x → 依赖 y</button><button data-ip-dep="x" aria-pressed="${s.dep==='x'}">自由 y → 依赖 x</button></div>
 ${s.curve==='circle'?range('theta','圆上工作点 θ',0,360,1,s.theta):range('t',s.curve==='cusp'?'工作点参数 t：p=(t³,t)':'工作点参数 t',-1.1,1.1,.01,s.t)}${range('delta','自由变量的步长 h',-.65,.65,.005,s.delta)}<div class="ip-row"><button class="button subtle" data-ip-action="half">步长减半</button><button class="button subtle" data-ip-action="zero">h = 0</button><button class="button subtle" data-ip-action="singular">看临界点</button></div>`:s.step==='surface'?`
 <label class="ip-label" for="ip-surface">曲面</label><select id="ip-surface">${Object.entries(ipSurfaces).map(([k,v])=>`<option value="${k}" ${s.surface===k?'selected':''}>${v.name}</option>`).join('')}</select>${range('sx','基点 x',-1,1,.01,s.sx)}${range('sy','基点 y',-1,1,.01,s.sy)}${range('hx','自由变化 dx',-.65,.65,.005,s.hx)}${range('hy','自由变化 dy',-.65,.65,.005,s.hy)}<div class="ip-row"><button class="button subtle" data-ip-axis="0">只动 x</button><button class="button subtle" data-ip-axis="1">只动 y</button><button class="button subtle" data-ip-action="half">步长减半</button></div>${range('camera','旋转视角（也可拖图）',-180,180,1,s.camera)}`:`
 <label class="ip-label" for="ip-coupling">修正矩阵的参数 λ</label><select id="ip-coupling">${[[1,'1 · 正常可逆'],[.1,'0.1 · 修正敏感'],[.02,'0.02 · 更敏感'],[0,'0 · 精确奇异'],...([0,.02,.1,1].includes(s.coupling)?[]:[[s.coupling,String(s.coupling)+' · 分享参数']])].map(([k,v])=>`<option value="${k}" ${s.coupling===k?'selected':''}>${v}</option>`).join('')}</select><p class="ip-small">B=[[1,1],[1,1+λ]]。λ=0 时两列重合，丢失一个修正方向。</p>${range('vx','基点 x₁',-.7,.7,.01,s.vx)}${range('vy','基点 x₂',-.7,.7,.01,s.vy)}${range('vhx','自由变化 dx₁',-.65,.65,.005,s.vhx)}${range('vhy','自由变化 dx₂',-.65,.65,.005,s.vhy)}<div class="ip-row"><button class="button subtle" data-ip-action="half">步长减半</button><button class="button subtle" data-ip-action="reachable">同向误差</button><button class="button subtle" data-ip-action="unreachable">不同向误差</button></div>`}<div class="ip-read" id="ip-control-read"></div><div class="ip-control-divider"></div><button class="text-button" data-ip-screen="proof">${icon('book')} 为什么这个修正存在？</button><button class="text-button" data-ip-action="export">${icon('download')} 导出当前误差数据</button><p class="ip-small">使用已核对的解析例子；绘图采样与动画不构成证明。</p></aside>`;}
function explore(s){const curve=['curve','condition'].includes(s.step),meta=ipStages[s.step];return `<section class="ip-question"><span>0${ipSteps.indexOf(s.step)+1}</span><div><h2>${meta.title}</h2><p>${meta.task}</p></div></section><div class="ip-workbench"><div class="ip-main"><section class="card ip-stage-card"><div class="ip-card-head"><div><span class="eyebrow">VARIABLE SPACE · 先看变量怎样动</span><h2 id="ip-scene-title"></h2></div><span class="ip-tag" id="ip-condition-badge"></span></div><div id="ip-scene" class="${curve?'ip-single-scene':'ip-double-scene'}">${curve?'<div id="ip-curve-plot"></div>':s.step==='surface'?'<div id="ip-surface-plot"></div><div class="ip-input-box"><span>自由变量平面 · 拖动橙点</span><div id="ip-input-plot"></div></div>':'<div class="ip-input-box"><span>自由变量 x · 位置与位移</span><div id="ip-input-plot"></div></div><div class="ip-input-box"><span>依赖变量 y · 一阶变化与真实变化</span><div id="ip-dependent-plot"></div></div>'}</div><div class="ip-legend"><span><i class="ip-orange"></i>自由变化 / 约束误差</span><span><i class="ip-blue"></i>一阶修正 / 切线预测</span><span><i class="ip-green"></i>精确分支参考</span></div><div class="ip-phase-live" id="ip-motion-read"></div></section>
 <section class="card ip-mechanism"><div class="ip-card-head"><div><span class="eyebrow">CONSTRAINT SPACE · 再看误差怎样抵消</span><h2>不是回到原位置，而是回到 F=0。</h2></div></div><div id="ip-constraint-plot"></div><div id="ip-cancel-equation"></div><div class="ip-dg" id="ip-dg"></div></section>
 <div class="ip-metrics" id="ip-metrics"></div><section class="ip-conclusion" id="ip-observation"></section>
 <details class="card ip-details" ${s.step==='condition'?'open':''}><summary>条件边界与精确解释</summary><div id="ip-analysis"></div></details>
 <details class="card ip-details"><summary>缩小输入，真正检验的是哪一种误差？</summary><div id="ip-error-plot"></div><p class="ip-small">纵轴：‖g(a+h)−g(a)−Dg(a)h‖ / ‖h‖。只是当前方向的数值曲线；全方向控制见证明。步长为 0、导数未确定或所选分支未定义时，不画伪造的 0。</p></details>
 <section class="ip-next"><p>${meta.next}</p><button class="button primary" data-ip-action="next">${s.step==='vector'?'自己判断':'继续下一步'} →</button></section></div>${controls(s)}</div>`;}
function proof(s){const P=ipProofs[s.step];return `<section class="ip-proof-grid"><article class="card ip-proof"><span class="eyebrow">FROM INTUITION TO PROOF</span><h2>${P.title}</h2><p class="ip-given">${ipEscape(P.given)}</p><nav class="ip-proof-nav" aria-label="证明步骤">${P.steps.map((_,i)=>`<button data-ip-proof="${i}" ${i===s.proofStep?'aria-current="step"':''}>${i+1}</button>`).join('')}</nav><div id="ip-proof-current"></div><div class="ip-row"><button class="button" data-ip-action="proof-back">← 上一步</button><button class="button" data-ip-action="proof-next">下一步 →</button></div><details class="ip-details"><summary>展开完整推导</summary>${P.steps.map((p,i)=>`<section><h3>${i+1}. ${p[0]}</h3><p>${ipEscape(p[1])}</p>${eq(ipEscape(p[2]))}</section>`).join('')}</details><p class="ip-warning">${ipEscape(P.warning)}</p></article><aside class="card ip-proof-aside"><span class="eyebrow">一直记住这三个对象</span><h3>g 不是 Dg。Dg 也不是 DF。</h3><dl><dt>g(a)</dt><dd>约束面上的依赖变量位置，属于 ℝᵐ。</dd><dt>Dg(a)</dt><dd>从自由变化到依赖变化的线性映射 ℝⁿ→ℝᵐ，矩阵尺寸 m×n。</dd><dt>DF(a,b)=[A B]</dt><dd>从全部变量的变化，到约束变化；尺寸 m×(n+m)。</dd></dl><div class="ip-equation">dy ≈ Dg(a) dx<br>Dg(a)=−B⁻¹A</div><p class="ip-small">这里的 ≈ 表示一阶近似。Dg 的公式本身是精确的导数等式。</p><button class="button full-width" data-ip-screen="explore">带着当前参数回到实验</button><p class="ip-small">数学依据：Jiří Lebl, Basic Analysis, §8.5。推导与具体反例均可离线阅读。</p></aside></section>`;}
function challenge(){return `<section class="card ip-quiz"><span class="eyebrow">TRANSFER THE IDEA · 不背公式，判断修正</span><h2>能写出公式，更要知道它在修什么。</h2><form id="ip-quiz-form">${ipQuestions.map((q,i)=>`<fieldset><legend>${i+1}. ${ipEscape(q.q)}</legend>${q.options.map((v,j)=>`<label><input type="radio" required name="ip-question-${q.id}" value="${j}"><span>${String.fromCharCode(65+j)}. ${ipEscape(v)}</span></label>`).join('')}<div class="ip-feedback" id="ip-feedback-${q.id}" hidden></div></fieldset>`).join('')}<div class="ip-row"><button class="button primary" type="submit">核对我的理由</button><button class="button" type="button" data-ip-action="clear-quiz">重新判断</button></div><p id="ip-quiz-score" role="status"></p></form></section>`;}
export function implicitPage(s){return `<div class="ip-root"><header class="page-heading ip-heading"><div><div class="breadcrumb">MA Playground <span>/</span> 09 · Implicit Function Theorem</div><span class="eyebrow">HOLD THE CONSTRAINT. READ THE CHANGE.</span><h1>保持约束，读出变化。</h1><p class="page-subtitle">自由变量制造误差，依赖变量负责修正。隐函数的导数，就藏在这次补偿里。</p></div><div class="heading-actions"><button class="button subtle" data-action="share">${icon('link')} 分享实验</button><button class="button subtle" data-ip-action="reset">${icon('reset')} 重置</button></div></header>
 ${pageGuide('implicit',{screen:s.screen})}<nav class="ip-journey" aria-label="连续学习路径">${ipSteps.map((k,i)=>`<button data-ip-step="${k}" ${s.step===k?'aria-current="step"':''}><small>0${i+1}</small><strong>${ipStages[k].name}</strong><span>→</span></button>`).join('')}</nav><div class="ip-context"><span class="ip-context-symbol">F=0</span><div><strong id="ip-function-formula"></strong><small id="ip-function-note"></small></div><div class="ip-dimension" id="ip-dimension"></div></div><nav class="ip-views" aria-label="实验与证明">${[['explore','动手发现'],['proof','为什么成立'],['challenge','自己判断']].map(([k,t])=>`<button data-ip-screen="${k}" ${s.screen===k?'aria-current="page"':''}>${t}</button>`).join('')}<span>直觉不代替存在性证明</span></nav>${s.screen==='proof'?proof(s):s.screen==='challenge'?challenge():explore(s)}</div>`;}
