import { ipCurves, ipSurfaces, ipEvaluate, ipMotion, ipNum, ipVec, ipNorm, ipMV, ipScale, ipAdd, ipSub, ipClamp, ipCSV } from './implicit-math.js';
import { implicitDefaults, ipNormalize, ipSteps, ipLimitVector } from './implicit-state.js';
import { ipStages, ipProofs, ipQuestions, ipMatrixHTML, ipEscape } from './implicit-content.js';
import { ipCurveSVG, ipInputSVG, ipDependentSVG, ipConstraintSVG, ipSurfaceSVG, ipErrorSVG } from './implicit-plots.js';
import { icon } from './icons.js';
const ipDraft={};let ipScored=false;
export function mountImplicitLab(root,getState,changed,toast){const abort=new AbortController(),signal=abort.signal,$=id=>root.querySelector('#'+id);let playing=false,raf=null,start=0,initial=0,dead=false,drag=null,last=0;
 const html=(id,value)=>{const el=$(id);if(el)el.innerHTML=value;},text=(id,value)=>{const el=$(id);if(el)el.textContent=value;};
 const slider=(k,v,label)=>{const el=$('ip-'+k);if(!el)return;el.value=String(v);el.style.setProperty('--fill',`${100*(v-Number(el.min))/(Number(el.max)-Number(el.min))}%`);el.setAttribute('aria-valuetext',label??ipNum(v));text('ip-'+k+'-value',label??ipNum(v));};
 function stop(){playing=false;if(raf!==null)cancelAnimationFrame(raf);raf=null;const b=root.querySelector('[data-ip-action="play"]');if(b){b.innerHTML=icon('play')+' 播放误差 → 修正';b.setAttribute('aria-pressed','false');}}
 function navigate(screen,step){stop();const s=getState();s.screen=screen;if(step){s.step=step;s.progress=0;s.proofStep=0;}changed(true);root.querySelector('h1')?.scrollIntoView({block:'start'});}
 function formula(s){if(s.step==='vector'){text('ip-function-formula','F(x,y) = Bλ y − H(x) = 0');text('ip-function-note','H(x)=(x₁+x₂², x₁²+x₂)；Bλ=[[1,1],[1,1+λ]]。y=(y₁,y₂) 是一组依赖变量。');html('ip-dimension','自由 ℝ² → 依赖 ℝ²<br>约束 ℝ² · Dg 为 2×2');}
 else if(s.step==='surface'){text('ip-function-formula',ipSurfaces[s.surface].formula+' = 0');text('ip-function-note','这里 (x,y) 整体是自由变量，z 是依赖变量；一般公式中的 x、y 则表示两个变量块。');html('ip-dimension','自由 ℝ² → 依赖 ℝ<br>Dg 为 1×2');}
 else {text('ip-function-formula',ipCurves[s.curve].formula+' = 0');text('ip-function-note',ipCurves[s.curve].note);html('ip-dimension',s.dep==='y'?'自由 x → 依赖 y<br>y=g(x) · Dg 为 1×1':'自由 y → 依赖 x<br>x=g(y) · Dg 为 1×1');}}
 function card(label,value,small=''){return `<div><span>${label}</span><strong>${value}</strong>${small?`<small>${small}</small>`:''}</div>`;}
 function live(s,m){const v=m.kind==='vector',surface=m.kind==='surface',motion=ipMotion(s,m),norm=r=>v?ipNorm(r):r,kn=v?ipVec(m.k):ipNum(m.k),real=v?ipVec(m.realK===undefined?null:m.realK):ipNum(m.realK);let phase=s.progress<=1?'自由改变：制造约束误差':s.progress<=2?'一阶修正：沿切线 / 切平面走':s.progress<3?'高阶修正：朝解析分支补回':'精确分支参考（使用已知解析式）';if(s.progress>=1&&m.Dg===null)phase='修正公式不可用：未定义的预测不会被补成 0';if(s.progress>=3&&m.exact===null)phase='无可用的唯一精确分支；当前点不是约束解';
 text('ip-phase-description',phase);html('ip-motion-read',`<span>${phase}</span><strong>当前真实约束${v?'向量':''} F ≈ ${v?ipVec(motion.residual):ipNum(motion.residual)}</strong><small>这是动画当前点的值，不是只计算 A dx+B dy。</small>`);
 html('ip-metrics',card(m.explicitDerivative?'一阶依赖变化 · 显式 g 的导数':s.dep==='x'&&m.kind==='curve'?'一阶依赖变化 · Dg dy':'一阶依赖变化 · Dg dx',kn,'不是隐函数 g 的位置')+card('真实分支变化 · Δg',real,'已知解析分支作对照')+card('‖Δg − Dg dx‖ / ‖dx‖',ipNum(m.ratio),'h=0 或公式不可用时未定义'));
 const info=!m.guarantee?'定理条件未满足':m.exact===null?'基点可用 · 本步越出分支':'C¹ + 基点满足约束 + 依赖块可逆';text('ip-condition-badge',info);$('ip-condition-badge')?.classList.toggle('ip-bad',!m.guarantee||m.exact===null);
 const values=`<div class="ip-residuals"><div><span>只改变自由变量</span><b>${v?'‖F‖':'F'} ≈ ${ipNum(norm(m.trialResidual))}</b></div><div><span>一阶修正之后</span><b>${v?'‖F‖':'F'} ≈ ${ipNum(norm(m.predResidual))}</b></div><div><span>解析分支对照</span><b>${v?'‖F‖':'F'} ≈ ${ipNum(norm(m.exactResidual))}</b></div></div>`;
 let heading,explanation;if(!m.guarantee){heading=v?'修正方向不够了，不是所有误差都能补回。':m.reason;explanation=v?(m.compatible?'这个目标的两个约束要求相同，有无穷多个修正。它不是一个在开邻域上唯一的隐函数。':'两个约束对 y₁+y₂ 提出不同要求，所以这个目标没有解。'):'不能把“判据不给保证”改写成“隐函数不存在”。下方逐个给出解析理由。';}
 else if(m.exact===null){heading='局部保证，不是任意步长的通行证。';explanation='工作点满足定理条件，但当前目标已经离开所选实数分支。请缩小步长；切线外推的点不能当成真实约束解。';}
 else {heading='蓝色修正抵消一阶误差；绿色分支补齐高阶部分。';explanation=v?'A dx+B(Dg dx)=0 是精确的线性代数等式。非线性残余由 H 的二次项产生；下面同时显示实际 F，避免把这两个等式混淆。':surface?'切平面给的是所有小方向的一阶修正，不是曲面本身。缩小自由位移，可以检查高度误差相对输入长度如何变化。':'Dg 决定补偿的斜率，不直接给出有限步的精确终点。试着把步长减半，再比较一阶修正与真实分支变化。';}
 html('ip-observation',`<span class="eyebrow">WHAT THE EXPERIMENT SAYS</span><h3>${heading}</h3><p>${explanation}</p>${values}<p class="ip-small">解析分支的残差在数学上为 0；浮点计算可能留有舍入量。条件与导数由公式判断，不由图形采样判断。</p>`);
 }
 function mechanism(s,m){const v=m.kind==='vector',surface=m.kind==='surface';let A=v?m.A:surface?m.A:[[m.A]],B=v?m.B:[[m.B]],D=v||surface?m.Dg:(m.Dg===null?null:[[m.Dg]]);
 const aLabel=v?'A = DₓF':surface?'A = (Fₓ Fᵧ)':s.dep==='y'?'A = Fₓ':'A = Fᵧ',bLabel=v?'B = DᵧF':surface?'B = F_z':s.dep==='y'?'B = Fᵧ':'B = Fₓ',freeName=m.kind==='curve'&&s.dep==='x'?'dy':'dx',dependentName=surface?'dz':m.kind==='curve'&&s.dep==='x'?'dx':'dy';
 html('ip-cancel-equation',`<div class="ip-block-matrices">${ipMatrixHTML(A,aLabel)}${ipMatrixHTML(B,bLabel)}</div><div class="ip-equation"><span class="ip-ink-orange">A ${freeName}</span> + <span class="ip-ink-blue">B ${dependentName}</span> = 0<span class="ip-eq-note">${surface?'本步的 dx 表示 (dx,dy)，一般公式的依赖块 y 在这里叫 z。':'这条等式针对线性化约束。'}</span></div>`);
 const shape=v?'2×2':surface?'1×2':'1×1';html('ip-dg',`<div class="ip-dg-label"><span class="eyebrow">WHAT IS Dg?</span><h3>它接收变化，不是返回位置。</h3></div><div class="ip-dg-formula">${ipMatrixHTML(D,m.explicitDerivative?'Dg =（显式解求导）':!m.guarantee?'−B⁻¹A 公式':'Dg = −B⁻¹A')}<p>${shape} Jacobian · 自由变化 → 依赖变化</p></div><p class="ip-small">${m.explicitDerivative?'由 g(x)=x 直接得到 Dg=1；原约束的 −B⁻¹A 仍是未定义，不能算 0/0。':m.guarantee?`${dependentName} ≈ Dg(a) ${freeName}；g(a) 是基点位置，Dg(a) 是这一点的局部线性规则。`:'依赖块不可逆，不能使用这个公式。不得把未定义的逆或 0/0 填成 0。'}</p>`);
 }
 function analysis(s,m){if(m.kind==='vector'){html('ip-analysis',`<h3>一个 4 维变量系统，分成两个 2 维变量视图。</h3><p>上方左图是自由空间 x；右图显示依赖增量 dy，不是 y 的绝对位置。下方才是二维约束空间；不能把它当成变量空间。各图分别标明坐标并自动缩放。</p><div class="ip-equation">det B = λ = ${ipNum(s.coupling)}<br>κ∞(B) = ${ipNum(m.condition)}${s.coupling!==0?' = (2+λ)²/λ':''}</div>${m.guarantee?`<p>λ 小而非零：仍可逆，但误差的某些方向被 B⁻¹ 放大。敏感不等于定理失效。</p><p>本例的解析解为 g(x)=B⁻¹H(x)。由 H 的二次项直接得到：</p><div class="ip-equation">g(a+h)−g(a)−Dg(a)h = B⁻¹(h₂²,h₁²)ᵀ</div><p>因此固定非零 λ 时，该余项除以 ‖h‖ 趋于 0。放大系数随 λ 改变，所以不能把 λ→0 与 h→0 任意混在一起。</p>`:`<p>λ=0 时，两行约束都要求同一个 y₁+y₂。基点固定在 (x,y)=(0,0)。有限目标的可解条件是：</p><div class="ip-equation">H₁(x)−H₂(x)=(x₁−x₂)(1−x₁−x₂)=0</div><p>${m.compatible?'当前目标满足条件，解为 (y₁,y₂)=(H₁(x)−t,t)，t 任意，所以不唯一。':'当前目标不满足条件，两个等式要求同一个数同时等于两个不同值，无解。'}</p><p>线性层面的可解条件是 dx₁=dx₂；这与有限步的非线性条件不同。奇异矩阵不再对任意误差提供唯一修正。</p>`}`);return;}
 if(m.kind==='surface'){html('ip-analysis',s.surface==='bowl'?`<h3>全局正常例子：一行 Jacobian，所有方向同时成立。</h3><div class="ip-equation">g(x,y)=x²+xy+y²<br>Dg=(2x+y, x+2y)</div><p>在基点 (a,b)，真实高度与切平面的差为 dx²+dx·dy+dy²。由 2|dx·dy|≤dx²+dy²，可得绝对值≤(3/2)‖(dx,dy)‖²。这是全方向的解析界，不是方向网格的最大值。</p>`:`<h3>球面只在 F_z≠0 处保证 z 的局部图像。</h3><div class="ip-equation">z=g(x,y)=√(1−x²−y²)，Dg=(−x/z,−y/z)</div><p>基点保持在半径 0.94 的输入圆盘内，因而 z>0。目标点仍可能越出单位圆盘；此时当前上半球高度未定义。这个人为的显示范围不是隐函数定理给出的最大邻域。</p><p>切平面方程是 ∇F(p)·(dx,dy,dz)=0。梯度箭头按方向缩放；它不是一个新的切向量。</p>`);return;}
 let t='';switch(s.curve){case 'circle':t=`<h3>圆上的条件与方向。</h3><div class="ip-equation">F_x=2x，F_y=2y；∇F=${ipVec(m.gradient)}</div><p>解 y 时 g′=−x/y；解 x 时相应导数为 −y/x。最右端 (1,0) 有 F_y=0、F_x=2，故可以交换角色。当前曲线上的工作点满足圆方程，浮点读数可能有舍入。</p><p>整个圆有上下两支；定理只在选定基点附近给出唯一支。蓝色切线在有限步后一般还留下 dx²+dy² 的约束残差。浅绿色参考点沿基点的同号分支计算；临界点的分支选择不是唯一性断言。</p>`;break;
 case 'parabola':t='<h3>同一条抛物线，也有不同的解题方向。</h3><p>解 y 时 F_y=1，g(x)=x² 全局光滑，有限步高阶修正就是 h²。反过来解 x，在 x≠0 处可沿同号平方根分支；顶点附近则是两支与无解的边界。</p>';break;
 case 'flat':t='<h3>零集没变，约束表达式却“压平”了。</h3><div class="ip-equation">(y−x)³=0 ⇔ y=x</div><p>两个偏导在整条线上都为 0，但 g(x)=x，Dg=1（直接从显式解求得）。把约束立方之后，一阶误差读数都消失了，实际有限误差却可能非零。因此不应在此显示 −0/0 或用它证明不存在 g。</p>';break;
 case 'cusp':t='<h3>唯一，并不保证可微。</h3><p>解 y 时 g(x)=∛x。原点的差商为 |h|^(−2/3)，无有限极限；F_y=0，所以公式未定义。反过来解 x，则 x=y³，F_x=−1，导数为 3y²，原点也正常。</p>';break;
 case 'cross':t='<h3>有一条光滑分支，不代表附近全部零集是一张图。</h3><div class="ip-equation">y²−x²=(y−x)(y+x)=0</div><p>y=x 和 y=−x 两支在原点交叉。当前参考点沿 y=x 计算，这是明确选定的分支。非原点附近可选唯一局部分支；原点附近两个解始终靠近，不能满足唯一性。</p>';break;}
 html('ip-analysis',t);}
 function proofUpdate(){const s=getState(),P=ipProofs[s.step],step=P.steps[s.proofStep];html('ip-proof-current',`<span class="ip-tag">STEP ${s.proofStep+1} / 4</span><h3>${step[0]}</h3><p>${ipEscape(step[1])}</p><div class="ip-equation">${ipEscape(step[2])}</div>`);root.querySelectorAll('[data-ip-proof]').forEach(b=>{if(Number(b.dataset.ipProof)===s.proofStep)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});root.querySelector('[data-ip-action="proof-back"]').disabled=s.proofStep===0;root.querySelector('[data-ip-action="proof-next"]').disabled=s.proofStep===3;}
 function quizUpdate(){for(const q of ipQuestions){const value=ipDraft[q.id];if(value!==undefined){const el=root.querySelector(`input[name="ip-question-${q.id}"][value="${value}"]`);if(el)el.checked=true;}if(ipScored){const ok=value===q.correct,el=$('ip-feedback-'+q.id);el.hidden=false;el.classList.toggle('correct',ok);el.innerHTML=`<strong>${ok?'✓ 正确':'再想一层'} · ${String.fromCharCode(65+q.correct)}</strong><p>${ipEscape(q.why)}</p>`;}}if(ipScored)text('ip-quiz-score',`${ipQuestions.filter(q=>ipDraft[q.id]===q.correct).length} / ${ipQuestions.length} 正确；请检查解释，不只记住答案。`);}
 function update(){if(dead)return;const s=getState();ipNormalize(s);formula(s);if(s.screen==='proof'){proofUpdate();return;}if(s.screen==='challenge'){quizUpdate();return;}const m=ipEvaluate(s);
 for(const k of ['theta','t','delta','sx','sy','hx','hy','vx','vy','vhx','vhy','progress','camera'])slider(k,s[k]);if(m.kind==='vector'){for(const k of ['vx','vy'])$('ip-'+k).disabled=s.coupling===0;}
 root.querySelectorAll('[data-ip-phase]').forEach(b=>{const phase=Number(b.dataset.ipPhase);b.setAttribute('aria-pressed',String(Math.abs(phase-s.progress)<.01));b.disabled=phase===2&&m.Dg===null||phase===3&&m.exact===null;});
 if(m.kind==='curve'){text('ip-scene-title',s.dep==='y'?'x 制造误差，y 补回高度。':'y 制造误差，x 横向补回。');html('ip-curve-plot',ipCurveSVG(s,m));text('ip-control-read',`基点 p = ${ipVec(m.p)}\n依赖偏导 B = ${ipNum(m.B)}\n当前自由步长 h = ${ipNum(m.h)}`);}
 else if(m.kind==='surface'){text('ip-scene-title','(dx,dy) 到 dz：切平面给出补偿规则。');html('ip-surface-plot',ipSurfaceSVG(s,m));html('ip-input-plot',ipInputSVG(s,m));text('ip-control-read',`基点 p = ${ipVec(m.p)}\nF_z(p) = ${ipNum(m.B)}\n自由位移 = ${ipVec(m.h)}`);}
 else {text('ip-scene-title','四维变量，拆成自由与依赖两张图。');html('ip-input-plot',ipInputSVG(s,m));html('ip-dependent-plot',ipDependentSVG(s,m));text('ip-control-read',`自由基点 a = ${ipVec(m.x)}\n依赖基点 g(a) = ${ipVec(m.y)}\ndet B = ${ipNum(m.det)}\nκ∞(B) = ${ipNum(m.condition)}`);}
 html('ip-constraint-plot',ipConstraintSVG(s,m));mechanism(s,m);live(s,m);analysis(s,m);html('ip-error-plot',ipErrorSVG(s));}
 function play(){if(playing){stop();changed();return;}const s=getState(),m=ipEvaluate(s),max=m.Dg===null?1:m.exact===null?2:3;if(s.progress>=max-.001)s.progress=0;if(matchMedia('(prefers-reduced-motion: reduce)').matches){s.progress=Math.min(max,Math.floor(s.progress)+1);update();changed();toast('减少动态效果已启用：按阶段前进。');return;}
 playing=true;initial=s.progress;start=0;last=0;const b=root.querySelector('[data-ip-action="play"]');b.innerHTML=icon('pause')+' 暂停修正过程';b.setAttribute('aria-pressed','true');const tick=now=>{if(!playing||dead)return;if(!start)start=now;if(now-last>45){last=now;s.progress=Math.min(max,initial+(now-start)/1900);update();changed();if(s.progress>=max){stop();if(max<3)toast(max===1?'依赖块不可逆：停在误差，不伪造修正。':'目标越出分支：停在线性预测，不伪造精确解。');return;}}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);}
 root.addEventListener('click',e=>{const s=getState(),stage=e.target.closest('[data-ip-step]'),screen=e.target.closest('[data-ip-screen]'),phase=e.target.closest('[data-ip-phase]'),role=e.target.closest('[data-ip-dep]'),pr=e.target.closest('[data-ip-proof]'),ax=e.target.closest('[data-ip-axis]'),button=e.target.closest('[data-ip-action]');
 if(stage){navigate(s.screen==='challenge'?'explore':s.screen,stage.dataset.ipStep);return;}if(screen){navigate(screen.dataset.ipScreen);return;}if(phase){stop();s.progress=Number(phase.dataset.ipPhase);update();changed();return;}if(role){stop();s.dep=role.dataset.ipDep;s.progress=0;changed(true);return;}if(pr){s.proofStep=Number(pr.dataset.ipProof);update();changed();return;}if(ax){stop();const r=ipNorm([s.hx,s.hy])||.3;s.hx=ax.dataset.ipAxis==='0'?r:0;s.hy=ax.dataset.ipAxis==='1'?r:0;s.progress=1;update();changed();return;}if(!button)return;const a=button.dataset.ipAction;if(a==='play'){play();return;}stop();switch(a){
 case 'reset':Object.assign(s,implicitDefaults());changed(true);toast('恢复隐函数实验的起点。');return;
 case 'half':if(s.step==='surface'){s.hx/=2;s.hy/=2;}else if(s.step==='vector'){s.vhx/=2;s.vhy/=2;}else s.delta/=2;s.progress=2;break;
 case 'zero':s.delta=0;s.progress=2;break;
 case 'singular':s.theta=0;s.t=0;s.progress=0;break;
 case 'reachable':s.vhx=.3;s.vhy=.3;s.progress=1;break;
 case 'unreachable':s.vhx=.3;s.vhy=0;s.progress=1;break;
 case 'next':{const i=ipSteps.indexOf(s.step);navigate(i===3?'challenge':'explore',i===3?undefined:ipSteps[i+1]);return;}
 case 'proof-back':s.proofStep=Math.max(0,s.proofStep-1);break;
 case 'proof-next':s.proofStep=Math.min(3,s.proofStep+1);break;
 case 'clear-quiz':for(const k in ipDraft)delete ipDraft[k];ipScored=false;changed(true);return;
 case 'export':{const url=URL.createObjectURL(new Blob(['\ufeff'+ipCSV(s)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ma-implicit-function-data.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1800);toast('已导出沿当前方向的误差读数及参数；有限数值不是证明。');return;}
 }update();changed();},{signal});
 root.addEventListener('input',e=>{const s=getState(),el=e.target;if(el.name?.startsWith('ip-question-')){ipDraft[el.name.slice(12)]=Number(el.value);ipScored=false;return;}if(!el.id?.startsWith('ip-'))return;const key=el.id.slice(3);if(!['theta','t','delta','sx','sy','hx','hy','vx','vy','vhx','vhy','progress','camera'].includes(key))return;stop();s[key]=Number(el.value);if(['delta','hx','hy','vhx','vhy'].includes(key))s.progress=1;update();changed();},{signal});
 root.addEventListener('change',e=>{const s=getState(),id=e.target.id;if(!['ip-curve','ip-surface','ip-coupling'].includes(id))return;stop();if(id==='ip-curve'){s.curve=e.target.value;s.t=0;s.theta=s.step==='condition'?0:55;}if(id==='ip-surface'){s.surface=e.target.value;ipNormalize(s);}if(id==='ip-coupling'){s.coupling=Number(e.target.value);ipNormalize(s);}s.progress=0;changed(true);},{signal});
 root.addEventListener('submit',e=>{if(e.target.id!=='ip-quiz-form')return;e.preventDefault();const data=new FormData(e.target);for(const q of ipQuestions){const v=data.get('ip-question-'+q.id);if(v!==null)ipDraft[q.id]=Number(v);}ipScored=true;quizUpdate();toast('逐题解释已展开。');},{signal});
 function applyPoint(key,p){const s=getState();if(key==='curve-base'){if(s.curve==='circle')s.theta=(Math.atan2(p[1],p[0])*180/Math.PI+360)%360;else s.t=ipClamp(s.curve==='cusp'?p[1]:p[0],-1.1,1.1);}
 else if(key==='curve-h'){const m=ipEvaluate(s);s.delta=ipClamp(p[m.i]-m.p[m.i],-.65,.65);s.progress=1;}
 else if(key==='input-base'){if(s.step==='surface'){s.sx=ipClamp(p[0],-1,1);s.sy=ipClamp(p[1],-1,1);}else if(s.coupling!==0){s.vx=ipClamp(p[0],-.7,.7);s.vy=ipClamp(p[1],-.7,.7);}}
 else if(key==='input-h'){if(s.step==='surface')[s.hx,s.hy]=ipLimitVector(ipSub(p,[s.sx,s.sy]));else [s.vhx,s.vhy]=ipLimitVector(ipSub(p,s.coupling===0?[0,0]:[s.vx,s.vy]));s.progress=1;}ipNormalize(s);}
 root.addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-ip-handle]'),orbit=e.target.closest('[data-ip-orbit]');if(!handle&&!orbit)return;stop();if(handle){const svg=handle.closest('svg'),mat=svg.getScreenCTM()?.inverse();if(!mat)return;drag={type:'handle',key:handle.dataset.ipHandle,m:{a:mat.a,b:mat.b,c:mat.c,d:mat.d,e:mat.e,f:mat.f},cx:Number(svg.dataset.ipCx),cy:Number(svg.dataset.ipCy),unit:Number(svg.dataset.ipUnit),pointer:e.pointerId};}else drag={type:'orbit',x:e.clientX,camera:getState().camera,pointer:e.pointerId};root.setPointerCapture(e.pointerId);e.preventDefault();},{signal});
 root.addEventListener('pointermove',e=>{if(!drag)return;if(drag.type==='orbit')getState().camera=ipClamp(drag.camera+(e.clientX-drag.x)*.6,-180,180);else {const m=drag.m,x=m.a*e.clientX+m.c*e.clientY+m.e,y=m.b*e.clientX+m.d*e.clientY+m.f;applyPoint(drag.key,[(x-drag.cx)/drag.unit,(drag.cy-y)/drag.unit]);}update();changed();},{signal});
 const end=()=>{if(drag){try{root.releasePointerCapture(drag.pointer);}catch{}drag=null;changed();}};root.addEventListener('pointerup',end,{signal});root.addEventListener('pointercancel',end,{signal});
 root.addEventListener('keydown',e=>{const h=e.target.closest('[data-ip-handle]');if(!h||!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();stop();const s=getState(),key=h.dataset.ipHandle,id=h.id,m=ipEvaluate(s),d=e.shiftKey?.1:.025;
 if(e.key==='Home'){if(key==='curve-base'){s.theta=55;s.t=.5;}if(key==='curve-h')s.delta=.24;if(key==='input-base'){s.sx=.25;s.sy=.15;s.vx=.35;s.vy=.25;}if(key==='input-h'){s.hx=.32;s.hy=.2;s.vhx=.22;s.vhy=-.12;}}
 else if(key==='curve-base'&&s.curve==='circle')s.theta=(s.theta+(['ArrowRight','ArrowUp'].includes(e.key)?4:-4)+360)%360;
 else {let pos=key==='curve-base'?m.p:key==='curve-h'?m.trial:key==='input-base'?(m.a||m.x):ipAdd(m.a||m.x,m.h);pos=ipAdd(pos,[e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0,e.key==='ArrowUp'?d:e.key==='ArrowDown'?-d:0]);applyPoint(key,pos);}update();changed();$(id)?.focus({preventScroll:true});},{signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();},{signal});update();return {destroy(){dead=true;stop();abort.abort();drag=null;}};
}
