import { lmF, lmJ, lmDelta, lmLocal, lmChain, lmBound, lmBasis, lmMV, lmScale, lmAdd, lmSub, lmNorm, lmUnit, lmRotation, lmCurveDelta, lmVelocity, lmMVT, lmDot, lmNumber, lmVector } from './linear-math.js';
const C={green:'#246853',orange:'#b9633d',blue:'#487ba0',red:'#aa554e',muted:'#70816b',grid:'#e5ecdf',ink:'#23382e'};
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function defs(id){return `<defs>${['green','orange','blue','red'].map(k=>`<marker id="${id}-${k}" viewBox="0 0 10 10" refX="8.5" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="${C[k]}"/></marker>`).join('')}</defs>`;}
function plane(id,span=3,W=420,H=326){const cx=W/2,cy=H/2,k=Math.min((W-84)/2,(H-62)/2)/span;
 const pt=v=>[cx+k*v[0],cy-k*v[1]],step=span>12?5:span>6?2:span>2.2?1:.5;let grid='';
 for(let v=Math.ceil(-span/step)*step;v<=span+.001;v+=step){const x=pt([v,0])[0],y=pt([0,v])[1],b=Math.abs(v)<1e-9;grid+=`<path d="M${x} ${cy-k*span}V${cy+k*span}M${cx-k*span} ${y}H${cx+k*span}" stroke="${b?'#b9c6af':C.grid}" stroke-width="${b?1.25:1}"/>`;if(v!==0&&Math.abs(v)<span-.05)grid+=`<text x="${x}" y="${cy+k*span+18}" text-anchor="middle" class="lm-tick">${lmNumber(v,1)}</text>`;}
 const svgStart=`<svg xmlns="http://www.w3.org/2000/svg" id="${id}" viewBox="0 0 ${W} ${H}" data-lm-cx="${cx}" data-lm-cy="${cy}" data-lm-unit="${k}" class="lm-svg" role="img">${defs(id)}<rect x="8" y="8" width="${W-16}" height="${H-16}" rx="12" fill="#f8faf3"/>${grid}`;
 return {id,W,H,cx,cy,k,pt,start:svgStart,end:'</svg>'};}
function line(f,a,b,color='green',dash='',width=2.4,arrow=false,opacity=1){const A=f.pt(a),B=f.pt(b);return `<path d="M${A[0]} ${A[1]}L${B[0]} ${B[1]}" fill="none" stroke="${C[color]||color}" stroke-width="${width}"${dash?` stroke-dasharray="${dash}"`:''}${arrow&&lmNorm(lmSub(a,b))>1e-10?` marker-end="url(#${f.id}-${color})"`:''} opacity="${opacity}"/>`;}
function path(f,points,color='green',dash='',width=1.4,opacity=1){return `<path d="${points.map((v,i)=>{const p=f.pt(v);return `${i?'L':'M'}${p[0].toFixed(3)} ${p[1].toFixed(3)}`;}).join('')}" fill="none" stroke="${C[color]||color}" stroke-width="${width}"${dash?` stroke-dasharray="${dash}"`:''} opacity="${opacity}"/>`;}
function dot(f,p,color='green',r=4,fill=true){const a=f.pt(p);return `<circle cx="${a[0]}" cy="${a[1]}" r="${r}" stroke="${C[color]}" stroke-width="2" fill="${fill?C[color]:'#fff'}"/>`;}
function text(f,p,t,color=C.ink,dx=8,dy=-10){const a=f.pt(p);return `<text x="${a[0]+dx}" y="${a[1]+dy}" fill="${color}" class="lm-plot-label">${esc(t)}</text>`;}
function handle(f,p,key,label,color='green'){const [x,y]=f.pt(p);return `<g id="lm-handle-${key}" data-lm-handle="${key}" tabindex="0" role="button" aria-label="${esc(label)}；方向键移动，Home 复位" class="lm-drag-handle"><circle cx="${x}" cy="${y}" r="18" fill="transparent"/><circle cx="${x}" cy="${y}" r="8" fill="#fff" stroke="${C[color]}" stroke-width="3"/><circle cx="${x}" cy="${y}" r="3" fill="${C[color]}"/></g>`;}
function gridImage(f,fn,color,dash='',opacity=.55){let html='';for(const a of [-1,-.5,0,.5,1]){html+=path(f,Array.from({length:25},(_,i)=>fn([a,-1+i/12])),color,dash,Math.abs(a)===1?1.8:1,opacity);html+=path(f,Array.from({length:25},(_,i)=>fn([-1+i/12,a])),color,dash,Math.abs(a)===1?1.8:1,opacity);}return html;}
export function lmInputSVG(s){const f=plane('lm-input-svg',s.step==='projection'?1.8:3),p=[s.px,s.py],h=[s.hx,s.hy],rho=lmNorm(h);let html=f.start+'<title>输入空间：工作点与小位移</title>';
 if(s.step==='projection'){const y=[s.yx,s.yy],z=lmAdd(p,lmScale(lmSub(y,p),s.lambda));html+=line(f,p,y,'orange','',2.3,true)+dot(f,z,'blue',5)+text(f,z,'γ(λ)',C.blue,8,18)+handle(f,p,'p','输入起点 p '+lmVector(p),'green')+handle(f,y,'y','输入终点 y '+lmVector(y),'orange')+text(f,p,'p',C.green,-19,-14)+text(f,y,'y',C.orange,12,-12);}
 else {const B=lmRotation(s.step==='columns'?s.basis:0);if(rho>0)html+=gridImage(f,v=>lmAdd(p,lmScale(lmMV(B,v),rho)),'green','',.35);
   const dir1=lmMV(B,[1,0]),dir2=lmMV(B,[0,1]);html+=line(f,p,lmAdd(p,lmScale(dir1,.42)),'orange','',2,true)+line(f,p,lmAdd(p,lmScale(dir2,.42)),'blue','',2,true);
   html+=line(f,p,lmAdd(p,h),'orange','',2.8,true)+handle(f,p,'p','工作点 p '+lmVector(p))+handle(f,lmAdd(p,h),'h','位移 h 的端点 '+lmVector(h),'orange')+text(f,p,'p',C.green,-18,-13)+text(f,lmAdd(p,h),'p+h',C.orange,12,-12);
 }
 html+=`<text x="${f.W-27}" y="${f.cy-8}" class="lm-tick">u</text><text x="${f.cx+9}" y="24" class="lm-tick">v</text><text x="24" y="${f.H-13}" class="lm-tick">横纵坐标等比例 · 位置与位移不同</text>`;return html+f.end;}
export function lmOutputSVG(s){const p=[s.px,s.py],h=[s.hx,s.hy],L=lmLocal(s.map,p,h),rho=L.rho,div=s.normalized&&rho>0?rho:1,ref=Math.max(rho,.8),B=lmRotation(s.step==='columns'?s.basis:0);let max=1.3;
 for(const x of [-1,0,1])for(const y of [-1,0,1]){const t=lmMV(B,[x,y]),v=lmDelta(s.map,p,lmScale(t,ref));for(const val of v)max=Math.max(max,Math.abs(val)/(s.normalized?ref:1)*1.16);}
 const f=plane('lm-output-svg',max),pred=lmScale(L.pred,1/div),actual=lmScale(L.truth,1/div);let html=f.start+'<title>局部真实映射与线性预测的比较</title>';
 if(rho>0){html+=gridImage(f,v=>lmScale(lmDelta(s.map,p,lmScale(lmMV(B,v),rho)),1/div),'green','',.5)+gridImage(f,v=>lmScale(lmMV(L.A,lmScale(lmMV(B,v),rho)),1/div),'orange','5 4',.62);}
 html+=line(f,[0,0],actual,'green','',3,true)+line(f,[0,0],pred,'orange','7 4',2.3,true)+line(f,pred,actual,'blue','',2.5)+dot(f,actual,'green',5)+dot(f,pred,'orange',4,false)+dot(f,[0,0],'green',3);
 html+=`<text x="24" y="${f.H-13}" class="lm-tick">${s.normalized&&rho>0?'显示 ΔF/ρ 与 JF(p)h/ρ · 原始数值在下方':'显示原始输出位移 ΔF 与 JF(p)h'}</text>`;
 if(rho===0)html+=`<text x="${f.cx}" y="60" text-anchor="middle" class="lm-plot-label">h=0：比值未定义；请恢复一个非零位移</text>`;
 return html+f.end;}
export function lmErrorSVG(s){const W=900,H=230,x0=63,x1=860,y0=25,y1=179,p=[s.px,s.py],h=[s.hx,s.hy],rho=lmNorm(h),dir=rho?lmScale(h,1/rho):[1,0],chain=s.step==='chain';
 const rows=Array.from({length:121},(_,i)=>{const q=-Math.log10(1.2)+(4+Math.log10(1.2))*i/120,r=10**-q,L=chain?lmChain(s.map,s.outer,p,lmScale(dir,r)):lmLocal(s.map,p,lmScale(dir,r));return {q,r,val:L.ratio,bound:L.bound};});
 const ymax=Math.max(.08,...rows.map(o=>o.bound))*1.08,x=q=>x0+(q+Math.log10(1.2))/(4+Math.log10(1.2))*(x1-x0),y=v=>y1-v/ymax*(y1-y0);
 const series=k=>rows.map((o,i)=>`${i?'L':'M'}${x(o.q).toFixed(2)} ${y(o[k]).toFixed(2)}`).join('');let html=`<svg xmlns="http://www.w3.org/2000/svg" id="lm-error-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="当前方向归一化误差和所有方向的已证明上界，随 rho 缩小"><path d="M${x0} ${y0}V${y1}H${x1}" fill="none" stroke="#b9c6af"/>`;
 for(const q of [0,1,2,3,4])html+=`<path d="M${x(q)} ${y0}V${y1}" stroke="${C.grid}"/><text x="${x(q)}" y="${y1+22}" text-anchor="middle" class="lm-tick">${q===0?'1':`10⁻${q}`}</text>`;
 for(const v of [0,ymax/2,ymax])html+=`<text x="${x0-8}" y="${y(v)+4}" text-anchor="end" class="lm-tick">${lmNumber(v,2)}</text>`;
 html+=`<path d="${series('bound')}" fill="none" stroke="${C.orange}" stroke-width="2" stroke-dasharray="7 4"/><path d="${series('val')}" fill="none" stroke="${C.green}" stroke-width="2.8"/>`;
 if(rho>0){const q=-Math.log10(rho),L=chain?lmChain(s.map,s.outer,p,h):lmLocal(s.map,p,h);html+=`<path d="M${x(q)} ${y0}V${y1}" stroke="${C.blue}" stroke-dasharray="3 4"/><circle cx="${x(q)}" cy="${y(L.ratio)}" r="5" fill="${C.green}"/>`;}
 html+=`<text x="${x0+5}" y="17" class="lm-tick">‖R‖ / ρ</text><text x="${x1}" y="${H-7}" text-anchor="end" class="lm-tick">ρ → 0（对数横轴）</text><text x="${W/2}" y="22" text-anchor="middle" class="lm-tick">实线：当前方向；虚线：已证明的全方向上界，不是采样最大值</text></svg>`;return html;}
export function lmChainSVG(s,index){const p=[s.px,s.py],h=[s.hx,s.hy],K=lmChain(s.map,s.outer,p,h),rho=K.rho,div=s.normalized&&rho?rho:1,I=[[1,0],[0,1]],mats=[I,K.A,K.product],ref=Math.max(.8,rho),coords=[h,K.pred,K.one],truth=[h,K.pred,K.truth];truth[1]=lmDelta(s.map,p,h);
 let max=1.4;for(const mat of mats)for(const a of [-1,1])for(const b of [-1,1])for(const v of lmMV(mat,[a,b]))max=Math.max(max,Math.abs(v)*(s.normalized?1:ref)*1.16);for(const v of [...K.truth,...K.wrong])max=Math.max(max,Math.abs(v)/div*1.16);
 const f=plane('lm-chain-'+index+'-svg',max,340,298);let html=f.start+`<title>${['输入位移','经过第一台线性机器','经过第二台线性机器'][index]}</title>`;
 if(rho)html+=gridImage(f,v=>lmScale(lmMV(mats[index],lmScale(v,rho)),1/div),'green','',.52);
 html+=line(f,[0,0],lmScale(coords[index],1/div),'green','',3,true)+dot(f,lmScale(coords[index],1/div),'green',4);
 if(index>0){html+=line(f,[0,0],lmScale(truth[index],1/div),'orange','6 4',2,true)+dot(f,lmScale(truth[index],1/div),'orange',4,false);}
 if(index===2&&s.wrong)html+=line(f,[0,0],lmScale(K.wrong,1/div),'red','3 5',2,true)+text(f,lmScale(K.wrong,1/div),'ABh',C.red,7,-8);
 const tip=f.pt(lmScale(coords[index],1/div));html+=`<circle id="lm-flow-dot-${index}" cx="${f.cx}" cy="${f.cy}" r="6" fill="${C.blue}" stroke="white" stroke-width="2" data-ox="${f.cx}" data-oy="${f.cy}" data-tx="${tip[0]}" data-ty="${tip[1]}" opacity="0" aria-hidden="true"/><text x="${f.W/2}" y="${f.H-10}" text-anchor="middle" class="lm-tick">${s.normalized&&rho?'图中箭头均除以 ρ':'原始位移；未归一化'}</text>`;return html+f.end;}
export function lmCurveSVG(s){const M=lmMVT(s.map,[s.px,s.py],[s.yx,s.yy],s.angle,s.lambda),points=Array.from({length:101},(_,i)=>lmCurveDelta(M.C,i/100));let max=Math.max(1.3,...points.flat().map(Math.abs))*1.2;const f=plane('lm-curve-svg',max),shadow=lmScale(M.a,M.scalar);let html=f.start+'<title>输出曲线及 a 方向的有向投影</title>';
 html+=line(f,lmScale(M.a,-max*.9),lmScale(M.a,max*.9),'blue','',1.3,false,.45)+path(f,points,'green','',2.8)+line(f,[0,0],M.D,'orange','6 4',2,true)+line(f,M.relative,shadow,'blue','3 4',1.5)+dot(f,shadow,'blue',5,false);
 const speed=lmNorm(M.V);if(speed>0){const v=lmScale(M.V,max*.2/speed);html+=line(f,lmSub(M.relative,v),lmAdd(M.relative,v),'green','',1.4,false,.65);}
 html+=dot(f,[0,0],'green',4)+dot(f,M.D,'orange',4)+dot(f,M.relative,'green',6)+text(f,[0,0],'F(p)',C.green,-37,18)+text(f,M.D,'F(y)',C.orange,9,-8)+text(f,lmScale(M.a,max*.88),'a',C.blue,8,-8);
 html+=`<text x="24" y="${f.H-13}" class="lm-tick">以 F(p) 为原点显示位移 · 短线只示意切线方向</text>`;return html+f.end;}
export function lmCompassSVG(s){const f=plane('lm-compass-svg',1.25,220,185),a=lmUnit(s.angle);return f.start+'<title>拖动单位投影方向 a</title>'+`<circle cx="${f.cx}" cy="${f.cy}" r="${f.k}" fill="none" stroke="#d5dfcd"/>`+line(f,[0,0],a,'blue','',2.5,true)+handle(f,a,'a','单位投影方向 a','blue')+`<text x="${f.cx}" y="${f.H-10}" class="lm-tick" text-anchor="middle">‖a‖=1 · 拖动转向</text>`+f.end;}
export function lmShadowSVG(s){const M=lmMVT(s.map,[s.px,s.py],[s.yx,s.yy],s.angle,s.lambda),W=900,H=280,x0=65,x1=850,y0=28,y1=232,vals=Array.from({length:161},(_,i)=>{const t=i/160;return [t,lmDot(M.a,lmCurveDelta(M.C,t))];}),bound=Math.max(.6,...vals.map(v=>Math.abs(v[1])),Math.abs(M.chord))*1.3;
 const x=t=>x0+(x1-x0)*t,y=q=>(y0+y1)/2-q/(2*bound)*(y1-y0),data=vals.map((v,i)=>`${i?'L':'M'}${x(v[0])} ${y(v[1])}`).join('');let html=`<svg xmlns="http://www.w3.org/2000/svg" id="lm-shadow-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="标量函数 phi 的割线与切线"><defs><clipPath id="lm-shadow-clip"><rect x="${x0}" y="${y0}" width="${x1-x0}" height="${y1-y0}"/></clipPath></defs>`;
 for(const t of [0,.25,.5,.75,1])html+=`<path d="M${x(t)} ${y0}V${y1}" stroke="${C.grid}"/><text x="${x(t)}" y="${y1+22}" class="lm-tick" text-anchor="middle">${t}</text>`;
 for(const q of [-bound/2,0,bound/2])html+=`<path d="M${x0} ${y(q)}H${x1}" stroke="${q===0?'#b9c6af':C.grid}"/><text x="${x0-9}" y="${y(q)+4}" text-anchor="end" class="lm-tick">${lmNumber(q,2)}</text>`;
 html+=`<g clip-path="url(#lm-shadow-clip)"><path d="M${x(0)} ${y(0)}L${x(1)} ${y(M.chord)}" stroke="${C.orange}" stroke-dasharray="6 4" stroke-width="2" fill="none"/><path d="${data}" stroke="${C.green}" fill="none" stroke-width="2.8"/>`;
 const left=s.lambda-.17,right=s.lambda+.17;html+=`<path d="M${x(left)} ${y(M.scalar+M.slope*(left-s.lambda))}L${x(right)} ${y(M.scalar+M.slope*(right-s.lambda))}" stroke="${C.blue}" stroke-width="2.4"/><path d="M${x(s.lambda)} ${y0}V${y1}" stroke="${C.blue}" stroke-dasharray="3 5" opacity=".45"/></g>`;
 for(const r of M.all?[.5]:M.roots){const val=lmDot(M.a,lmCurveDelta(M.C,r));html+=`<g data-lm-root="${r}" role="button" tabindex="0" aria-label="选择中值点 lambda 约 ${lmNumber(r)}" class="lm-root-point"><circle cx="${x(r)}" cy="${y(val)}" r="16" fill="transparent"/><circle cx="${x(r)}" cy="${y(val)}" r="6" fill="#fff" stroke="${C.green}" stroke-width="2.5"/></g>`;}
 html+=`<circle cx="${x(s.lambda)}" cy="${y(M.scalar)}" r="4" fill="${C.blue}"/><text x="${x1}" y="${H-7}" text-anchor="end" class="lm-tick">λ（参数，不是输出空间的位置）</text><text x="${x0+6}" y="18" class="lm-tick">φ(λ)</text><text x="${(x0+x1)/2}" y="18" text-anchor="middle" class="lm-tick">橙色割线斜率 = φ(1)−φ(0)；蓝色切线斜率 = φ′(λ)</text></svg>`;return html;}
