import { lmMaps, lmOuters } from './linear-math.js';
import { lmSteps } from './linear-state.js';
import { icon } from './icons.js';
import { pageGuide } from './page-guide.js';
export function lmEscape(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export const lmStageInfo={
 local:{name:'缩小位移',title:'先给函数一个小箭头。',question:'不用重新计算整个函数，能预测输出往哪里走吗？',task:'拖动橙色端点改变 h；再缩小 ρ。看真实变化的弯曲网格，怎样靠近线性预测的平行四边形。',next:'这个线性规则，为什么是一张矩阵？'},
 columns:{name:'读懂两列',title:'一列，就是一个输入方向的输出速度。',question:'矩阵里为什么恰好装着偏导数？',task:'点第 1 列或第 2 列，只沿一个坐标方向移动。再自由拖动 h：任意方向都是两列的线性组合。',next:'两台局部线性机器接起来，会发生什么？'},
 chain:{name:'连接机器',title:'先经过 F，再经过 G。',question:'矩阵乘法，是记忆规则，还是两次变换真的接上了？',task:'播放箭头传递，再点“合并两步”。输入、中间、输出的三张网格使用同一坐标比例；最后一步的一步预测与两步结果重合。',next:'沿一条线走，再看一个方向的影子。'},
 projection:{name:'投影找中值',title:'把输出的曲线，投成一条实值函数。',question:'为什么要先选方向 a，才能用普通中值定理？',task:'拖动输入端点 p、y，转动方向 a；点击绿色候选点。下面的切线就与割线平行。再试“没有共同中值点”的反例。',next:'我能自己解释这台机器了吗？'}
};
export const lmProofs={
 local:{title:'导数首先是线性映射，不是偏导清单。',given:'F:U⊂ℝⁿ→ℝᵐ，U 开，p∈U。可微性要求存在一个线性映射 L:ℝⁿ→ℝᵐ。这里的 h 是输入位移，不是位置。',steps:[
 ['从一维的斜率出发','一维中，f(p+h)−f(p)≈f′(p)h。乘以 f′(p) 本身就是一个线性映射。多维输入和输出仍需要线性规则，只是不能再由一个数字包办。','ℝ→ℝ：h ↦ f′(p)h；ℝⁿ→ℝᵐ：h ↦ Lh'],
 ['“越来越接近”还不够','写 F(p+h)−F(p)=Lh+r(h)。只要求 ‖r(h)‖→0 太弱；可微要求误差比位移低一阶，且同时控制所有足够小的 h，而非有限个方向。','lim_{h→0,h≠0} ‖r(h)‖/‖h‖ = 0'],
 ['导数为什么是唯一的？','假设 L 和 M 都满足定义。令 h=t v，固定任意单位向量 v，(L−M)tv 的范数被两个余项范数控制。除以 |t| 再取极限，得到 (L−M)v=0。对每个 v 成立，所以 L=M。','‖(L−M)v‖ ≤ ‖r_L(tv)‖/|t| + ‖r_M(tv)‖/|t| → 0'],
 ['给这个实验一个全方向的保证','对主例 F(u,v)=(u²−v,u³+v)，直接展开 R=(h₁²,3p₁h₁²+h₁³)。用 |h₁|≤ρ=‖h‖ 得到右侧上界。它不依赖方向，所以动画观察之外还有完整的可微性证明。','‖R‖/ρ ≤ ρ√(1+(3|p₁|+ρ)²) → 0']
 ],warning:'h=0 时变化量和余项都为零，但 ‖R‖/‖h‖ 是 0/0，不能显示成“已验证的 0”。导数也不要求可逆：矩阵奇异不代表函数不可微。'},
 columns:{title:'第 j 列，是 DF(p) 对 eⱼ 的作用。',given:'假设 F 已经在 p 可微。使用输入和输出的标准基，向量默认写为列向量；JF 有 m 行、n 列。',steps:[
 ['沿一个坐标方向取差商','在定义中代 h=t eⱼ。除以 t，并让 t 从正负两侧趋零。余项 r(teⱼ)/t 趋零，得到向量差商的极限 L eⱼ。逐分量看，就是各输出分量对输入坐标 j 的偏导。','L eⱼ = lim_{t→0} [F(p+t eⱼ)−F(p)]/t = (∂ⱼF₁,…,∂ⱼFₘ)ᵀ'],
 ['列决定整个线性规则','任意 h=h₁e₁+⋯+hₙeₙ。线性性把它拆成各列的加权和。第 i 行是在看第 i 个输出，第 j 列是在看第 j 个输入方向。','Lh = ∑ⱼ hⱼ L eⱼ = JF(p)h'],
 ['不要把 ρeⱼ 当成 eⱼ','图上的位移是 h=ρeⱼ。线性预测是 ρ 倍的第 j 列。只有除以 ρ 后的真实差商，才与第 j 列这个“每单位输入的输出速度”比较。','JF(p)(ρeⱼ)=ρ·第 j 列；[F(p+ρeⱼ)−F(p)]/ρ → 第 j 列'],
 ['换坐标，不换线性映射','把输入基旋转为 B=[b₁ b₂]，输出基保持不变。同一个物理箭头满足 h=B h_new。新矩阵是 JF(p)B，因而两种坐标算出的物理输出相同。非标准基的列是对应方向导数，不再是原坐标的偏导列。','[DF(p)]_new = JF(p)B；(JF(p)B)h_new = JF(p)h']
 ],warning:'“偏导数组成一个矩阵”不自动保证它是导数。这里的推理以可微为前提；第二个实验中的反例说明仅有偏导不够。'},
 chain:{title:'先线性化两次，还是一次线性化复合？',given:'F:U⊂ℝⁿ→ℝᵐ 在 p 可微；G:V⊂ℝᵐ→ℝᵏ 在 F(p) 可微，F(U)⊂V。令 A=DF(p)、B=DG(F(p))。',steps:[
 ['第一台机器给出中间位移','令 k=F(p+h)−F(p)=Ah+r(h)。因为 r(h)=o(‖h‖)，存在常数 C 使小 h 时 ‖k‖≤C‖h‖；这一步同时保证 k→0。','k = Ah + r(h)，r(h)=o(‖h‖)，k=O(‖h‖)'],
 ['第二台必须在 F(p) 处线性化','G 的输入是中间空间中的 F(p)，不是原空间中的 p。于是 G(F(p)+k)−G(F(p))=Bk+s(k)，其中 s(k)=o(‖k‖)。','B = JG(F(p))，不是 JG(p)'],
 ['把误差也一同传递','代入 k：复合增量为 BAh+Br(h)+s(k)。第一项外的 Br(h)=o(‖h‖)。对 s(k)，用 ‖s(k)‖≤ε‖k‖≤εC‖h‖；即使 k=0 也没有除零问题。','G(F(p+h))−G(F(p)) = BAh + o(‖h‖)'],
 ['乘法次序和尺寸都来自箭头方向','右边先作用 A，左边再作用 B。JF 为 m×n，JG 为 k×m，乘积为 k×n。这是导数线性映射的复合；不是把有限的非线性增量误写成一个恒等式。','J(G∘F)(p) = JG(F(p)) JF(p)；(k×m)(m×n)=k×n']
 ],warning:'图中“两步 = 一步”是线性预测的精确代数关系。真实非线性变化一般仍有余项。即使 2×2 例子中反向乘积也能算，AB 通常不等于 BA。'},
 projection:{title:'沿一条线，再看一个方向的影子。',given:'与教材命题一致：F:U⊂ℝⁿ→ℝᵐ 可微，U 开，p≠y 且闭线段 [p,y]⊂U。先固定任意 a∈ℝᵐ；不需要假设导数连续。',steps:[
 ['把输入压成一个参数','令 γ(λ)=p+λ(y−p)，λ∈[0,1]。输入沿线段匀速走，输出曲线 C(λ)=F(γ(λ)) 通常是弯的。','γ′(λ)=y−p；C′(λ)=JF(γ(λ))(y−p)'],
 ['向量输出再压成实数','只看 a 方向的线性读出 φ(λ)=a·[C(λ)−C(0)]。a 为单位向量时它是有向投影长度；其他非零 a 只是再乘一个尺度，a=0 时等式平凡。','φ(0)=0；φ(1)=a·[F(y)−F(p)]'],
 ['现在才能直接调用一元中值定理','φ 在 [0,1] 连续、在 (0,1) 可微。存在 ξ∈(0,1) 使 φ(1)−φ(0)=φ′(ξ)(1−0)。令 z=γ(ξ)。λ 的区间长度是 1，所以总变化与平均速度数值相同。','a·[F(y)−F(p)] = a·JF(z)(y−p)，z=p+ξ(y−p)'],
 ['方向先选，中值点随后再找','结论是 ∀a ∃z_a。主例限制到 (t,0)，t∈[−1,1]，总位移为 (0,2)，而瞬时速度乘参数长度是 (4t,6t²)。第一坐标要求 t=0，第二坐标要求 t=±1/√3，没有共同解。','(0,2) ≠ (4t,6t²) 对所有 t；但每个固定 a 的投影等式都能分别成立。']
 ],warning:'不要交换 ∀a∃z_a 与 ∃z∀a。二次正例确实可共用中点，但不能推广到所有可微映射。屏幕候选点由多项式方程求根；存在性来自定理而非有限采样。'}
};
export const lmQuestions=[
 {id:'object',q:'F:ℝ³→ℝ² 在 p 的导数，首先是什么？',options:['一个从 ℝ³ 到 ℝ² 的线性映射；标准基矩阵有 2 行 3 列。','一个二维向量，记录两个输出的斜率。','一个 3×2 矩阵，因为有三个输入。'],correct:0,why:'导数把输入位移送成输出位移。输入有三维、输出有二维，所以矩阵是 2×3；矩阵是坐标表示。'},
 {id:'ratio',q:'真实变化与线性预测之差趋于 0，就能断言可微吗？',options:['能，两者最终重合。','不能；要看余项除以 ‖h‖ 后，在所有趋近方向上是否一起趋零。','只需要检查两个坐标轴。'],correct:1,why:'仅有绝对误差趋零不能控制一阶精度。可微定义是 r(h)=o(‖h‖)，而不是 r(h)=o(1)。'},
 {id:'column',q:'第 1 列是 (2,3)ᵀ，位移 h=0.1e₁。线性预测是什么？',options:['(2,3)ᵀ。','(20,30)ᵀ。','(0.2,0.3)ᵀ；单位差商才趋近 (2,3)ᵀ。'],correct:2,why:'线性性给出 DF(p)(0.1e₁)=0.1 DF(p)e₁。列表示每单位输入方向的输出速度，不是任意长度位移的变化。'},
 {id:'chain',q:'F:ℝ²→ℝ³，G:ℝ³→ℝ⁴。哪种导数乘法和取值点都正确？',options:['JG(F(p)) JF(p)，尺寸 (4×3)(3×2)=4×2。','JF(p) JG(F(p))，先 F 所以写左边。','JG(p) JF(p)，都在 p 求值即可。'],correct:0,why:'第二台机器的工作点是 F(p)。矩阵从右向左作用在列向量上，顺序由空间之间的传递决定。'},
 {id:'basis',q:'输入基旋转为 B，输出基不变。同一个物理箭头 h=B h_new，应该怎样算输出？',options:['仍用 JF(p)h_new，因为导数没有改变。','用 (JF(p)B)h_new；等于标准基中的 JF(p)h。','必须重新改变函数本身。'],correct:1,why:'线性映射没有变，但它的矩阵随基改变。坐标向量和矩阵必须一起变化，物理输出才能保持一致。'},
 {id:'quantifier',q:'对任意 a，都存在 z_a 使投影中值等式成立。能消去 a 得到一个向量中值点吗？',options:['能，a 是任意向量。','只有把各坐标分别检查一遍就能。','一般不能，不同 a 找到的点可能不同。'],correct:2,why:'∀a∃z_a 不能交换成 ∃z∀a。F(t,0)=(t²,t³) 的两个坐标分别要求 t=0 和 t=±1/√3。'},
 {id:'zero',q:'在某点 Jacobian 的一列为零，或者行列式为零，说明什么？',options:['函数一定不可微。','没有足够证据否定可微；导数可以把某个方向压成零。','说明函数在这个邻域里一定恒定。'],correct:1,why:'例如 (u²−v,u³+v) 在原点的第一列为零，但仍是处处可微的多项式映射。导数存在与可逆是不同条件。'},
 {id:'projection',q:'为什么书中的中值等式没有再乘线段长度 ‖y−p‖？',options:['线段长度总是 1。','向量值中值定理不需要路径速度。','γ′=y−p 已包含实际位移，参数区间的长度才是 1。'],correct:2,why:'φ′(λ)=a·JF(γ(λ))(y−p)，路径方向与长度已经包含在 y−p 中。普通中值定理还乘 (1−0)，不是再乘 ‖y−p‖。'}
];
function slider(id,label,min,max,step,value){return `<div class="slider-block"><label class="control-label" for="${id}"><span>${label}</span><output id="${id}-value"></output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;}
function journey(s){return `<nav class="lm-journey" aria-label="导数的连续学习路径">${lmSteps.map((k,i)=>`<button data-lm-step="${k}" ${s.step===k?'aria-current="step"':''}><small>0${i+1}</small><strong>${lmStageInfo[k].name}</strong><span>→</span></button>`).join('')}</nav>`;}
function context(s){return `<div class="lm-context"><label><span class="eyebrow">ONE MAP · FOUR VIEWS</span><select id="lm-function" aria-label="选择向量值映射">${Object.values(lmMaps).map(o=>`<option value="${o.id}"${s.map===o.id?' selected':''}>${o.name}</option>`).join('')}</select></label><div><strong id="lm-function-formula">${lmEscape(lmMaps[s.map].formula)}</strong><small id="lm-function-note">${lmEscape(lmMaps[s.map].note)}</small></div><span class="lm-domain">ℝ² → ℝ²<br>预设映射均处处可微</span></div>`;}
function controls(s){const projecting=s.step==='projection';return `<aside class="card lm-controls"><span class="eyebrow">CHANGE IT · WATCH IT</span><h2>${projecting?'先选方向，再找中值点。':'先预测，再拖动。'}</h2>${projecting?`
 <div id="lm-compass"></div>${slider('lm-angle','投影方向 a',0,360,1,s.angle)}${slider('lm-lambda','沿线段的位置 λ',0,1,.001,s.lambda)}<div class="lm-row"><button class="button primary" data-lm-action="play" aria-pressed="false">${icon('play')} 沿线段走</button><button class="button" data-lm-action="snap">找中值点</button></div><div id="lm-roots" class="lm-roots"></div><div class="lm-axis-presets"><button data-lm-angle="0" class="button">a = e₁</button><button data-lm-angle="90" class="button">a = e₂</button><button data-lm-angle="45" class="button">a = (1,1)/√2</button></div><details class="lm-options"><summary>用滑块精确移动输入端点</summary>${slider('lm-px','p₁',-1.5,1.5,.01,s.px)}${slider('lm-py','p₂',-1.5,1.5,.01,s.py)}${slider('lm-yx','y₁',-1.5,1.5,.01,s.yx)}${slider('lm-yy','y₂',-1.5,1.5,.01,s.yy)}</details><p class="lm-small">图上可直接拖动 p、y 和方向 a。绿色候选 ξ∈(0,1) 由解析方程求根，显示为浮点近似。</p>`:`
 ${slider('lm-scale','位移长度 ρ = ‖h‖',-.079181246,4,.01,.15)}<p class="lm-slider-note">向右缩小 → 0.0001</p>${slider('lm-hangle','输入方向',0,360,1,30)}<div class="lm-row"><button class="button primary" data-lm-action="play" aria-pressed="false">${icon('play')} ${s.step==='chain'?'播放两次传递':'自动缩小位移'}</button><button class="button" data-lm-action="half">ρ 减半</button></div><div class="lm-hread" id="lm-hread"></div><label class="lm-check"><input type="checkbox" id="lm-normalized"${s.normalized?' checked':''}> 输出放大 1/ρ，看清一阶误差</label>${s.step==='columns'?`<details class="lm-options"><summary>进阶：换一组输入坐标</summary>${slider('lm-basis','输入基旋转 β',-90,90,1,s.basis)}<p class="lm-small">输出仍用标准基。矩阵变了，不代表线性映射变了。</p><div id="lm-basis-read"></div></details>`:''}${s.step==='chain'?`<label class="lm-select-label" for="lm-outer">第二台机器 G</label><select id="lm-outer">${Object.entries(lmOuters).map(([k,o])=>`<option value="${k}"${s.outer===k?' selected':''}>${o.name}</option>`).join('')}</select><p class="lm-small" id="lm-outer-formula"></p><button class="button full-width" data-lm-action="merge" aria-pressed="${s.merged}">${s.merged?'分开看两步':'合并两步'}</button><label class="lm-check"><input type="checkbox" id="lm-wrong"${s.wrong?' checked':''}> 比较错误顺序 ABh</label>`:''}<details class="lm-options"><summary>工作点 p 与零位移</summary>${slider('lm-px','p₁',-1.5,1.5,.01,s.px)}${slider('lm-py','p₂',-1.5,1.5,.01,s.py)}<button class="button" data-lm-action="zero">把 h 设为 0</button><button class="button" data-lm-action="restore-h">恢复小位移</button></details><p class="lm-small">图线有限；下方的全方向余项上界来自多项式恒等式，不来自采样。</p>`}<div class="lm-control-end"><button class="text-button" data-lm-action="export">${icon('download')} 导出同一方向的误差 CSV</button><button class="text-button" data-lm-screen="proof">为什么成立？ →</button></div></aside>`;}
function panel(id,title,overline){return `<section class="lm-plane"><header><span class="eyebrow">${overline}</span><h3>${title}</h3></header><div id="${id}" class="lm-plot"></div></section>`;}
function localBody(s){return `<section class="card lm-stage"><div class="lm-card-head"><div><span class="eyebrow">INPUT DISPLACEMENT → OUTPUT DISPLACEMENT</span><h2>${s.step==='columns'?'只动一个输入，输出有两个分量。':'弯曲的局部，怎样成为线性的？'}</h2></div><span class="lm-tag" id="lm-scale-tag"></span></div><div class="lm-two-planes">${panel('lm-input','输入：位置 p 与位移 h','INPUT · 可拖动 p 和橙色端点')}${panel('lm-output','输出：真实变化 vs 线性预测','OUTPUT · 原点代表 F(p)')}</div><div class="lm-legend"><span><i class="lm-green"></i>真实变化 / 弯曲网格</span><span><i class="lm-orange dash"></i>线性预测 / 平行四边形</span><span><i class="lm-blue"></i>两者之差</span></div><div id="lm-live" class="lm-live"></div></section><section class="card lm-matrix-section"><div><span class="eyebrow">A LINEAR MAP, WRITTEN IN COORDINATES</span><h2 id="lm-matrix-title">矩阵不是新的规则，只是线性映射的坐标表示。</h2><p class="lm-small">点选一列，让输入只沿对应方向移动。</p></div><div id="lm-matrix"></div><div id="lm-column-read" class="lm-column-read"></div></section><section class="lm-analytic" id="lm-interpretation"></section><section class="card lm-error-card"><div class="lm-card-head"><div><span class="eyebrow">SMALL ERROR IS NOT ENOUGH</span><h2>除以位移长度之后，才是关键。</h2></div><span class="lm-small">当前方向 + 全方向上界</span></div><div id="lm-error-plot"></div><div id="lm-bound" class="lm-bound"></div></section>`;}
function chainBody(){return `<section class="card lm-stage"><div class="lm-card-head"><div><span class="eyebrow">COMPOSE THE LOCAL MACHINES</span><h2>一个箭头，经过两次线性变换。</h2></div><span class="lm-tag" id="lm-chain-phase">h → Ah → BAh</span></div><div class="lm-pipeline" id="lm-pipeline"></div><div class="lm-three-planes">${panel('lm-chain-in','h','INPUT · ℝ²')}${panel('lm-chain-mid','Ah','MIDDLE · ℝ²')}${panel('lm-chain-out','B(Ah) = (BA)h','OUTPUT · ℝ²')}</div><div class="lm-legend"><span><i class="lm-green"></i>当前线性预测</span><span><i class="lm-orange dash"></i>真实非线性变化</span><span>三图坐标比例相同；光点仅指示传递进度，箭头是完整预测</span></div><div id="lm-live" class="lm-live"></div></section><section class="card lm-chain-matrices" id="lm-chain-matrices"></section><div id="lm-interpretation" class="lm-analytic"></div><section class="card lm-error-card"><div class="lm-card-head"><div><span class="eyebrow">THE REMAINDER ALSO PASSES THROUGH</span><h2>预测能合并，非线性误差不会凭空消失。</h2></div></div><div id="lm-error-plot"></div><div id="lm-bound" class="lm-bound"></div></section>`;}
function projectionBody(){return `<section class="card lm-stage"><div class="lm-card-head"><div><span class="eyebrow">A PATH → A CURVE → A SCALAR SHADOW</span><h2>输入是一条线，输出通常是一条曲线。</h2></div><span class="lm-tag">0 ≤ λ ≤ 1</span></div><div class="lm-two-planes">${panel('lm-input','γ(λ) = p + λ(y − p)','INPUT · 拖动 p 和 y')}${panel('lm-curve','C(λ) = F(γ(λ))','OUTPUT · 虚线投向 a 方向')}</div><div class="lm-legend"><span><i class="lm-green"></i>输出曲线</span><span><i class="lm-orange dash"></i>端点总位移</span><span><i class="lm-blue"></i>a 方向的影子</span></div></section><section class="card lm-shadow-card"><div class="lm-card-head"><div><span class="eyebrow">NOW THE ORDINARY MEAN VALUE THEOREM APPLIES</span><h2>φ(λ) = a · [C(λ) − C(0)]</h2></div><span class="lm-small">绿色点：候选中值点 · 切线与割线同斜率</span></div><div id="lm-shadow"></div><div id="lm-live" class="lm-live"></div><div id="lm-projection-read" class="lm-bound"></div></section><section class="lm-analytic" id="lm-interpretation"></section><section class="card lm-quantifier"><div><span class="eyebrow">SAME LETTERS, DIFFERENT ORDER</span><h2>∀a ∃zₐ <span>≠</span> ∃z ∀a</h2><p>每个方向都能找到自己的点，不代表有一个点能同时照顾所有方向。</p></div><button class="button primary" data-lm-action="counter">试试没有共同中值点的例子 →</button><div id="lm-counter-proof"></div></section>`;}
function explore(s){const stage=lmStageInfo[s.step];return `<div class="lm-prompt"><span>0${lmSteps.indexOf(s.step)+1}</span><div><h2>${stage.question}</h2><p>${stage.task}</p></div></div><div class="lm-workbench"><div class="lm-main">${s.step==='projection'?projectionBody():s.step==='chain'?chainBody():localBody(s)}</div>${controls(s)}</div><section class="lm-next"><div><span class="eyebrow">KEEP THE SAME MAP. ASK THE NEXT QUESTION.</span><h3>${stage.next}</h3></div><button class="button primary" data-lm-action="next-step">${s.step==='projection'?'自己判断':'下一步'} →</button></section>`;}
function proof(s){const p=lmProofs[s.step];return `<div class="lm-proof-layout"><aside class="card lm-proof-nav"><span class="eyebrow">FOUR STEPS, ONE ARGUMENT</span><h2>直觉，接到定义上。</h2>${lmSteps.map(k=>`<button data-lm-step="${k}"${s.step===k?' aria-current="step"':''}>${lmStageInfo[k].name} <span>→</span></button>`).join('')}<div id="lm-proof-live" class="lm-small"></div><button class="button full-width" data-lm-screen="explore">带着参数返回实验</button></aside><article class="card lm-proof-article"><span class="eyebrow">WHY IT WORKS · NOT A SAMPLING ARGUMENT</span><h2>${p.title}</h2><div class="lm-given"><strong>先把条件说完整</strong><p>${p.given}</p></div><div class="lm-proof-dots">${p.steps.map((_,i)=>`<button data-lm-proof-step="${i}"${s.proofStep===i?' aria-current="step"':''}>${i+1}</button>`).join('')}</div><div id="lm-proof-current"></div><div class="lm-proof-buttons"><button class="button" data-lm-action="proof-back">← 上一步</button><button class="button primary" data-lm-action="proof-next">下一步 →</button></div><details class="lm-full-proof"><summary>展开完整推导</summary>${p.steps.map((x,i)=>`<section><h3>${i+1}. ${x[0]}</h3><p>${x[1]}</p><div class="lm-equation">${lmEscape(x[2])}</div></section>`).join('')}</details><div class="lm-warning">${p.warning}</div><p class="lm-small lm-proof-source">数学口径：Fréchet 导数、标准基 Jacobian、有限维链式法则与一元 Lagrange 中值定理。多项式例子及余项展开由本项目独立推导。完整条件、坐标约定与计算边界见随包 LINEAR-MATHEMATICS.md。</p></article></div>`;}
function challenge(){return `<section class="card lm-quiz-card"><span class="eyebrow">EXPLAIN THE MACHINE IN YOUR OWN WORDS</span><h2>现在，能不背公式地判断了吗？</h2><p class="lm-small">答案与理由一起检查。可随时回到实验，作答保留在本页内存中，不上传。</p><form id="lm-quiz">${lmQuestions.map((q,i)=>`<fieldset><legend><span>0${i+1}</span>${q.q}</legend>${q.options.map((t,j)=>`<label><input type="radio" name="lm-question-${q.id}" value="${j}" required><span>${lmEscape(t)}</span></label>`).join('')}<div id="lm-feedback-${q.id}" class="lm-feedback" hidden></div></fieldset>`).join('')}<div class="lm-row"><button type="submit" class="button primary">检查理解与理由</button><button type="button" class="button" data-lm-action="clear-quiz">重新判断</button></div><p id="lm-quiz-score" role="status" aria-live="polite"></p></form></section>`;}
export function linearPage(s){return `<header class="page-heading lm-heading"><div><div class="breadcrumb">实验室 / 多元微分 / 一点附近的线性规则</div><span class="eyebrow">EXPERIMENT 08 — DERIVATIVE AS A LINEAR MAP</span><h1>导数，是局部线性机器。</h1><p class="page-subtitle">一个小位移，读懂 Jacobian；两台机器，接上链式法则；一个影子，回到中值定理。</p></div><div class="heading-actions"><button class="button" data-lm-action="reset">${icon('reset')} 重置</button><button class="button" data-action="share">${icon('share')} 分享实验</button></div></header>${pageGuide('linear',{screen:s.screen})}${journey(s)}${context(s)}<div class="lm-views" aria-label="实验、证明与检查理解">${[['explore','动手实验'],['proof','为什么成立'],['challenge','自己判断']].map(([k,t])=>`<button data-lm-screen="${k}"${s.screen===k?' aria-current="page"':''}>${t}</button>`).join('')}<span>几何直觉 → 线性映射 → 坐标表示</span></div>${s.screen==='proof'?proof(s):s.screen==='challenge'?challenge():explore(s)}`;}
