import { seriesDefaults, applySeriesScenario } from './series-state.js';
import { seriesFamilies, seriesMethods, seriesMethodNames, seEvaluate, seNodeHolds, seTruth, seStatusLabels, seReference, seLimits, seComparison, seLeibniz, seIntegral, seB, seSamples, seNum, seEscape, seCSV } from './series-math.js';
import { seEdges, seNodeInfo, seQuestions, seEquation } from './series-content.js';
import { seGraphSVG, seMobileGraph, seRatesSVG, seSumsSVG, seComparisonSVG, seIntegralSVG, seTermsSVG } from './series-plots.js';
const quizMemory={answers:{},graded:false};
export function mountSeriesLab(root,getState,changed,toast){const ac=new AbortController(),opts={signal:ac.signal};let playing=false,frame=null,last=0,paramFamily=null;
 const $=id=>root.querySelector('#'+id),html=(id,v)=>{const el=$(id);if(el)el.innerHTML=v;},text=(id,v)=>{const el=$(id);if(el)el.textContent=v;};
 function stop(){playing=false;if(frame!==null)cancelAnimationFrame(frame);frame=null;last=0;const b=root.querySelector('[data-se-action="play"]');if(b){b.textContent='▶ 逐项累积';b.setAttribute('aria-pressed','false');}}
 function rebuild(){stop();changed(true);root.querySelector('#se-title')?.focus({preventScroll:true});window.scrollTo(0,0);}
 function slider(id,value){const el=$(id);if(!el)return;el.value=value;el.style.setProperty('--fill',`${100*(value-Number(el.min))/(Number(el.max)-Number(el.min)||1)}%`);el.setAttribute('aria-valuetext',String(value));text(id+'-value',seNum(value));}
 function parameter(){const s=getState(),f=seriesFamilies[s.family];if(paramFamily!==s.family){html('se-parameter',f.parameter?`<label class="se-label" for="se-param">${f.parameter==='p'?'幂参数 p':'几何系数 q'} <output id="se-param-value"></output></label><input type="range" id="se-param" min="${f.parameter==='p'?'.25':'.35'}" max="${f.parameter==='p'?'3':'1.2'}" step=".01" value="${s[f.parameter]}"><p class="se-small">${f.parameter==='p'?'特别观察 p=1 的边界。':'特别观察 q=1；齿状系数可能持续局部上升。'}</p>`:'<p class="se-small">这个案例固定通项。改变赋号、参照或观察长度，检验不同路线。</p>');paramFamily=s.family;}if(f.parameter)slider('se-param',s[f.parameter]);}
 function grade(){let score=0;for(const q of seQuestions){const v=quizMemory.answers['se-'+q.id],good=v!==undefined&&Number(v)===q.correct;score+=Number(good);const el=$('se-feedback-'+q.id);el.hidden=false;el.classList.toggle('correct',good);el.textContent=(v===undefined?'尚未作答。':good?'✓ 判断正确。':'再检查条件。')+' '+q.reason;}text('se-quiz-score',`${score} / ${seQuestions.length} 正确。请核对理由与条件，而不仅看选项。`);}
 function update(){const s=getState(),f=seriesFamilies[s.family],ev=seEvaluate(s),truth=seTruth(s),ni=seNodeInfo[s.node];text('se-formula',(s.signed?'aₙ=(−1)ⁿ⁻¹bₙ；':'')+f.formula.replace(s.signed?'aₙ':'∅',s.signed?'bₙ':'∅'));parameter();
 if(s.screen==='proof'){const e=seEdges[s.edge],v=e.steps[s.step];html('se-proof-current',`<span class="eyebrow">STEP 0${s.step+1} / 04</span><h3>${v[0]}</h3><p>${seEscape(v[1])}</p>${seEquation(v[2])}`);root.querySelectorAll('[data-se-step]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.seStep)===s.step?'step':'false'));root.querySelector('[data-se-action="proof-prev"]').disabled=s.step===0;root.querySelector('[data-se-action="proof-next"]').disabled=s.step===3;return;}
 if(s.screen==='challenge'){for(const [name,value] of Object.entries(quizMemory.answers)){const r=root.querySelector(`input[name="${name}"][value="${value}"]`);if(r)r.checked=true;}if(quizMemory.graded)grade();return;}
 if(s.screen==='map'){html('se-graph',seGraphSVG(s)+seMobileGraph(s));html('se-node-detail',`<span class="se-status ${ev[s.node].kind}">${seStatusLabels[ev[s.node].kind]}</span><h3>${ni.title}</h3>${seEquation(ni.formula)}<p>${seEscape(ni.intuition)}</p><p class="se-small">${seEscape(ev[s.node].reason)}</p><button class="text-button" data-se-edge="${ni.route}">检查这一条路线 →</button>`);html('se-counter-routes',Object.entries(seEdges).filter(([,e])=>e.type!=='theorem').map(([id,e])=>`<button class="se-counter-card ${s.edge===id?'active':''}" data-se-edge="${id}"><span>${e.type==='incomparable'?'⇏ ⇍':'⇏'}</span><strong>${e.title}</strong><small>${e.type==='incomparable'?'两方向，两份反例':'反例在哪里'} ↗</small></button>`).join(''));return;}
 const edgeData=seEdges[s.edge],left=seNodeHolds(s,edgeData.from),right=seNodeHolds(s,edgeData.to);let witness;
 if(s.edge==='convergence-not-leib'&&!s.signed)witness='这一关系要在交错序列中找反例：请先启用交错赋号。';
 else if(edgeData.type==='theorem')witness=left?'当前满足前提，定理保证右侧。一般性保证仍来自证明。':'当前未满足左侧前提，不能借这条箭头下结论；不表示右侧一定失败。';
 else if(left&&!right)witness='当前正好是反例：左侧成立，右侧不成立。';
 else if(edgeData.type==='incomparable'&&right&&!left)witness='当前是另一方向的反例：右侧成立，左侧不成立。';
 else witness=left&&right?'两边都成立：这是相容的正例，不是逆推成立的证明。':'尚未构成反例。要找左边成立、右边不成立的例子。';
 html('se-witness',`<span>${seriesMethodNames[edgeData.from]} ${left?'✓':'—'}</span><b>${edgeData.type==='theorem'?'→':'⇏'}</b><span>${seriesMethodNames[edgeData.to]} ${right?'✓':'—'}</span><p>${witness}</p>`);
 slider('se-N',s.N);if($('se-probe'))$('se-probe').max=s.N;slider('se-probe',s.probe);text('se-reference-note',`${seReference(s).label} · 已知${seReference(s).converges?'收敛':'发散'}。${s.ref==='natural'&&s.family==='logarithmic'?'对数例故意与调和项比较，看看小于它是否足够。':''}`);
 const sumView=s.view==='sums'||['leibniz','absolute','convergence','zero'].includes(s.node);let plot,note,title;
 if(sumView){plot=seSumsSVG(s);title='位置趋稳，不等于总路程有限。';note='实线是带符号的部分和 Sₙ；虚线是绝对值部分和 Aₙ。非负项时二者重合。图像只画有限前缀。';}
 else if(['comparison','limit'].includes(s.node)){plot=seComparisonSVG(s);title='先固定参照，再看商怎样变化。';note='纵轴是 log₁₀(bₙ/vₙ)。零项单独标 ×，不取对数。只有全局解析常数界才画作覆盖整段的界线。';}
 else if(s.node==='integral'){plot=seIntegralSVG(s);title='形状条件，把矩形接到积分。';note='只显示当前位置附近的 10 格。曲线由解析函数采样绘制；逐格不等式的保证来自单调性，而非像素。';}
 else{plot=seRatesSVG(s);title='局部跳高，平均速度仍可能变小。';note='橙线为相邻比值，绿虚线为 n 次根。阴影只表示数值小于 1 的区域；有限个点落入阴影不证明最终条件。';}
 html('se-main-plot',plot);text('se-plot-title',title);text('se-plot-note',note);const sample=seSamples(s,s.probe).at(-1);html('se-live',[[`当前 n`,String(s.probe)],['aₙ',seNum(sample.a)],['Sₙ · 位置',seNum(sample.sum)],['Aₙ · 路程',seNum(sample.absoluteSum)]].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join(''));
 let micro='';if(sumView){micro=seTermsSVG(s);const leib=seLeibniz(s);if(leib.valid){const next=seB(s,s.probe+1),lo=sample.sum-(s.probe%2?next:0),hi=sample.sum+(s.probe%2?0:next);micro+=`<div class="se-analytic"><strong>本例满足 Leibniz 条件：有解析尾项界。</strong>${seEquation(`|S−S${s.probe}| ≤ b${s.probe+1} ≈ ${seNum(next)}`)}<p>夹逼区间约为 [${seNum(lo)}, ${seNum(hi)}]。这是上界的浮点显示，不是实际误差，也不是区间算术认证。</p></div>`;}else micro+=`<div class="se-analytic"><strong>不套用 Leibniz 余项界。</strong><p>${seEscape(leib.reason)}</p></div>`;
 }else if(['ratio','root'].includes(s.node)){const l=seLimits(s);micro=`<div class="se-analytic se-two"><div><small>解析结论 · 不是最后一个比值</small><strong>L = ${l.ratio===null?'不存在 / 未定义':seNum(l.ratio)}</strong><p>${seEscape(ev.ratio.reason)}</p></div><div><small>解析结论 · 不是有限窗口最大值</small><strong>ρ = ${seNum(l.root)}</strong><p>${seEscape(ev.root.reason)}${!l.rootOrdinary?' 普通根值极限不存在，上极限仍为 1。':''}</p></div></div>`;
 }else if(['limit','comparison'].includes(s.node)){const c=seComparison(s);micro=`<div class="se-analytic"><small>独立解析比较 · 当前参照不变</small><strong>${seEscape(c.label)}</strong><p>${seEscape(ev.comparison.reason)}</p><p>${seEscape(ev.limit.extra||'有限几项的商不能代替极限；界来自通项公式。')}</p></div>`;
 }else{const i=seIntegral(s);micro=`<div class="se-analytic"><strong>${i.valid?'单调与广义积分分别检查':'形状前提未满足'}</strong>${seEquation(i.formula)}<p>${seEscape(i.reason)}</p></div>`;}
 html('se-microscope',micro);html('se-result',`<div><span class="eyebrow">CATALOGUE RESULT · ANALYTIC, NOT FITTED</span><h3>${truth.label}</h3><p>${seEscape(truth.reason)}</p></div><div class="se-result-category"><span>${s.family==='sparse'?(s.signed?'含零交错赋号；非零项不严格交错':'非负项含零'):s.signed?'交错赋号':'严格正项'}</span><span>Σ|aₙ| ${truth.absolute?'收敛':'发散'}</span><span>${truth.conditional?'两个判断才定义条件收敛':s.signed?'交错形式不决定敛散':'非负项没有“条件收敛”类别'}</span></div>`);
 html('se-methods',seriesMethods.map(id=>{const e=ev[id];return `<button class="se-method-row ${s.node===id?'selected':''}" data-se-method="${id}"><div><strong>${seriesMethodNames[id]}</strong><small>${seNodeInfo[id].short}</small></div><span class="se-status ${e.kind}">${seStatusLabels[e.kind]}</span><p>${seEscape(e.reason)}${e.extra?`<small>${seEscape(e.extra)}</small>`:''}</p><i>↗</i></button>`;}).join(''));
 }
 function play(){if(playing){stop();changed(false);return;}const s=getState();if(s.probe>=s.N)s.probe=1;playing=true;last=0;const b=root.querySelector('[data-se-action="play"]');b.textContent='Ⅱ 暂停';b.setAttribute('aria-pressed','true');const tick=now=>{if(!playing)return;if(!last)last=now;const delay=matchMedia('(prefers-reduced-motion: reduce)').matches?650:140;if(now-last>=delay){s.probe=Math.min(s.N,s.probe+1);last=now;update();changed(false);}if(s.probe>=s.N){stop();toast('已显示全部有限项。结论仍需解析论证。');return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}
 function edge(id){const e=seEdges[id];if(!e)return;const s=getState();s.edge=id;s.node=e.from;s.step=0;s.screen='workshop';s.layer=e.type==='theorem'?'theorems':'questions';rebuild();}
 root.addEventListener('click',event=>{const b=event.target.closest('[data-se-screen],[data-se-node],[data-se-edge],[data-se-layer],[data-se-view],[data-se-method],[data-se-scenario],[data-se-proof-case],[data-se-step],[data-se-action]');if(!b)return;event.preventDefault();const s=getState();
 if(b.dataset.seScreen){s.screen=b.dataset.seScreen;rebuild();return;}
 if(b.dataset.seNode||b.dataset.seMethod){const id=b.dataset.seNode||b.dataset.seMethod;s.node=id;s.edge=seNodeInfo[id].route;s.step=0;s.screen='workshop';rebuild();return;}
 if(b.dataset.seEdge){edge(b.dataset.seEdge);return;}
 if(b.dataset.seLayer){s.layer=b.dataset.seLayer;if(s.layer==='questions'&&seEdges[s.edge].type==='theorem')s.edge='root-not-ratio';update();changed(false);return;}
 if(b.dataset.seView){s.view=b.dataset.seView;rebuild();return;}
 if(b.dataset.seScenario||b.dataset.seProofCase){applySeriesScenario(s,b.dataset.seScenario||b.dataset.seProofCase);if(b.dataset.seProofCase)s.screen='workshop';rebuild();return;}
 if(b.dataset.seStep!==undefined){s.step=Number(b.dataset.seStep);update();changed(false);return;}
 switch(b.dataset.seAction){case 'play':play();break;case 'reset':Object.assign(s,seriesDefaults());quizMemory.answers={};quizMemory.graded=false;rebuild();break;case 'proof-prev':s.step=Math.max(0,s.step-1);update();changed(false);break;case 'proof-next':s.step=Math.min(3,s.step+1);update();changed(false);break;case 'quiz-reset':quizMemory.answers={};quizMemory.graded=false;rebuild();break;case 'export':{const blob=new Blob([seCSV(s)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ma-series-${s.family}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已导出 ${s.N} 项；元数据说明了符号、参照与有限采样范围。`);break;}}
 },opts);
 root.addEventListener('keydown',e=>{const t=e.target.closest('g[role="button"]');if(t&&['Enter',' '].includes(e.key)){e.preventDefault();t.dispatchEvent(new MouseEvent('click',{bubbles:true}));}},opts);
 root.addEventListener('input',e=>{const s=getState();if(e.target.type==='range'){stop();const value=Number(e.target.value);if(e.target.id==='se-param')s[seriesFamilies[s.family].parameter]=value;else if(e.target.id==='se-N'){s.N=value;s.probe=Math.min(s.N,s.probe);}else if(e.target.id==='se-probe')s.probe=value;else return;update();changed(false);}},opts);
 root.addEventListener('change',e=>{const s=getState();if(e.target.id==='se-family'){s.family=e.target.value;rebuild();}else if(e.target.id==='se-signed'){s.signed=e.target.checked;rebuild();}else if(e.target.id==='se-reference'){s.ref=e.target.value;update();changed(false);}else if(e.target.id==='se-route-select'){s.edge=e.target.value;s.node=seEdges[s.edge].from;s.step=0;rebuild();}else if(e.target.matches('#se-quiz input')){quizMemory.answers[e.target.name]=e.target.value;quizMemory.graded=false;root.querySelectorAll('.se-feedback').forEach(el=>el.hidden=true);text('se-quiz-score','答案已修改，请重新检查。');}},opts);
 root.addEventListener('submit',e=>{if(e.target.id==='se-quiz'){e.preventDefault();quizMemory.graded=true;grade();}},opts);
 window.addEventListener('resize',()=>update(),opts);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();},opts);update();return {destroy(){stop();ac.abort();}};
}
