import { seSamples, seLimits, seTruth, seNum, seEscape, seNodeHolds, seriesMethodNames, seIntegral, seContinuous, seComparison, seB, seA } from './series-math.js';
import { seEdges, seNodeInfo } from './series-content.js';
export const sePositions={ratio:[132,91],root:[132,257],limit:[420,91],comparison:[420,257],integral:[757,91],absolute:[420,425],leibniz:[757,425],convergence:[420,595],zero:[757,595]};
const green='#426b46',orange='#bf7640',blue='#697a9c',muted='#8b9680',ink='#344b39';
const text=(x,y,t,extra='')=>`<text x="${x}" y="${y}" ${extra}>${seEscape(t)}</text>`;
function graphNode(s,id){const [x,y]=sePositions[id],d=seNodeInfo[id],yes=seNodeHolds(s,id);return `<g class="se-graph-node ${id===s.node?'selected':''} ${yes?'holds':'not-holds'}" role="button" tabindex="0" data-se-node="${id}" aria-label="${d.title}，当前例子${yes?'满足':'未满足'}图中条件，进入实验" transform="translate(${x-109} ${y-53})"><rect width="218" height="106" rx="12"/><text x="17" y="28" class="se-node-code">${['absolute','convergence','zero'].includes(id)?'PROPERTY':'SUFFICIENT CONDITION'}</text><text x="17" y="55" class="se-node-name">${d.title}</text><text x="17" y="79" class="se-node-detail">${seEscape(d.short)}</text><text x="198" y="28" text-anchor="end" class="se-node-check">${yes?'✓':'—'}</text></g>`;}
const edgePaths={
 'ratio-root':{d:'M132 148 L132 197',x:132,y:176},
 'root-absolute':{d:'M160 314 Q180 425 305 425',x:225,y:388},
 'limit-comparison':{d:'M420 148 L420 197',x:420,y:176},
 'comparison-absolute':{d:'M420 314 L420 365',x:420,y:344},
 'integral-absolute':{d:'M757 148 L757 257 Q757 325 655 334 Q575 340 539 393',x:715,y:307},
 'leib-convergence':{d:'M705 482 C665 515 525 509 475 538',x:615,y:518},
 'absolute-convergence':{d:'M420 482 L420 535',x:420,y:511},
 'convergence-zero':{d:'M534 595 L640 595',x:589,y:595},
 'root-not-ratio':{d:'M173 199 Q250 175 178 145',x:232,y:170},
 'absolute-not-root':{d:'M310 444 Q95 460 126 316',x:136,y:412},
 'comparison-not-limit':{d:'M458 199 Q527 175 464 145',x:514,y:170},
 'convergence-not-absolute':{d:'M464 538 Q535 508 464 482',x:514,y:510},
 'root-integral':{d:'M246 230 L278 230 L278 10 L620 10 L620 100 L645 100',x:450,y:10},
 'leib-absolute':{d:'M643 425 L537 425',x:589,y:425},
 'convergence-not-leib':{d:'M495 538 C585 530 640 510 723 482',x:605,y:526},
 'zero-not-convergence':{d:'M645 621 Q584 665 535 620',x:589,y:647}
};
function edgeSVG(s,id,faint=false){const e=seEdges[id],p=edgePaths[id],dash=e.type!=='theorem',active=s.edge===id;return `<g class="se-graph-edge ${dash?'is-question':''} ${active?'is-active':''} ${faint?'is-faint':''}" role="button" tabindex="0" data-se-edge="${id}" aria-label="${e.title}：${dash?'反例在哪里':'为什么成立'}"><path d="${p.d}" class="se-edge-hit"/><path d="${p.d}" class="se-edge-line" marker-end="url(#se-arrow-${dash?'question':'solid'})"${e.type==='incomparable'?' marker-start="url(#se-arrow-question-back)"':''}/><circle cx="${p.x}" cy="${p.y}" r="15"/><text x="${p.x}" y="${p.y+5}" text-anchor="middle">${dash?'?':'→'}</text><title>${e.title}</title></g>`;}
export function seGraphSVG(s){const q=s.layer==='questions';let active=s.edge;if(q&&seEdges[active].type==='theorem')active='root-not-ratio';return `<svg class="se-graph-desktop" viewBox="0 -16 900 692" role="group" aria-label="级数判别法条件有向图；绿色实线是定理，虚线是待反驳的逆推"><defs><marker id="se-arrow-solid" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 1 L9 5 L0 9" fill="none" stroke="${green}" stroke-width="1.5"/></marker><marker id="se-arrow-question" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 1 L9 5 L0 9" fill="none" stroke="${orange}" stroke-width="1.5"/></marker><marker id="se-arrow-question-back" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 1 L9 5 L0 9" fill="none" stroke="${orange}" stroke-width="1.5"/></marker></defs><rect x="8" y="17" width="864" height="478" rx="20" fill="#f6f8f0"/>${text(652,361,'带符号的抵消路线','class="se-lane-caption"')}${Object.entries(seEdges).filter(([,e])=>e.type==='theorem').map(([id])=>edgeSVG(s,id,q)).join('')}${q?edgeSVG({...s,edge:active},active):''}${Object.keys(sePositions).map(id=>graphNode(s,id)).join('')}</svg>`;}
function mobileNode(s,id){return `<button data-se-node="${id}" class="se-mobile-node ${seNodeHolds(s,id)?'holds':''}"><strong>${seriesMethodNames[id]}</strong><small>${seNodeInfo[id].short}</small><span>${seNodeHolds(s,id)?'✓':'—'}</span></button>`;}
export function seMobileGraph(s){const chains=[['ratio','ratio-root','root','root-absolute','absolute','absolute-convergence','convergence'],['limit','limit-comparison','comparison','comparison-absolute','absolute'],['integral','integral-absolute','absolute'],['leibniz','leib-convergence','convergence','convergence-zero','zero']];return `<div class="se-graph-mobile" aria-label="适合窄屏的同一张关系图，重复节点是同一性质">${chains.map((chain,i)=>`<section><h3>${['指数速度路线','选定参照路线','面积路线','符号抵消路线'][i]}</h3>${chain.map((id,j)=>j%2===0?mobileNode(s,id):`<button class="se-mobile-arrow" data-se-edge="${id}" aria-label="${seEdges[id].title}，为什么成立">↓ <span>为什么成立</span></button>`).join('')}</section>`).join('')}<p>重复出现的“绝对收敛”是同一个节点。下方虚线卡片检验反推，不是新的定理。</p></div>`;}
function chartFrame(label,inner,w=760,h=330){return `<svg class="se-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${seEscape(label)}"><title>${seEscape(label)}</title>${inner}</svg>`;}
function linePath(data,x,y,key){let d='',pen=false;for(const r of data){const v=r[key];if(v===null||!Number.isFinite(v)){pen=false;continue;}d+=`${pen?'L':'M'}${x(r.n).toFixed(2)},${y(v).toFixed(2)} `;pen=true;}return d;}
function grid(N,ymin,ymax,w=760,h=330){const left=62,right=w-30,top=30,bottom=h-43,x=n=>left+(n-1)/Math.max(1,N-1)*(right-left),y=v=>bottom-(v-ymin)/(ymax-ymin||1)*(bottom-top);let content='';for(let i=0;i<=4;i++){let v=ymin+(ymax-ymin)*i/4;content+=`<line x1="${left}" x2="${right}" y1="${y(v)}" y2="${y(v)}" stroke="#e2e8d9"/>`+text(left-12,y(v)+4,seNum(v,3),'text-anchor="end" fill="#8b9680"');}for(const n of [...new Set([1,Math.round(N/2),N])])content+=text(x(n),bottom+23,String(n),'text-anchor="middle" fill="#8b9680"');content+=text(right,bottom+38,'下标 n','text-anchor="end" fill="#8b9680"');return {x,y,left,right,top,bottom,content};}
export function seRatesSVG(s){const all=seSamples(s),rows=all.slice(0,s.probe),max=Math.max(1.25,...all.map(r=>r.ratio??0))*1.12,g=grid(s.N,0,max);let inner=g.content;inner+=`<rect x="${g.left}" y="${g.y(1)}" width="${g.right-g.left}" height="${g.bottom-g.y(1)}" fill="#edf4e0" opacity=".6"/><line x1="${g.left}" x2="${g.right}" y1="${g.y(1)}" y2="${g.y(1)}" stroke="${orange}" stroke-dasharray="6 5"/>`+text(g.right-5,g.y(1)-7,'临界值 1','text-anchor="end" fill="'+orange+'"');for(const [key,c,dash] of [['ratio',orange,''],['root',green,'stroke-dasharray="6 3"']]){inner+=`<path d="${linePath(rows,g.x,g.y,key)}" fill="none" stroke="${c}" stroke-width="2.3" ${dash}/>`;for(const r of rows)if(r[key]!==null&&Number.isFinite(r[key]))inner+=`<circle cx="${g.x(r.n)}" cy="${g.y(r[key])}" r="${r.n===s.probe?4:1.7}" fill="${c}"/>`;}
 inner+=text(g.left,17,'橙：相邻比值 bₙ₊₁/bₙ     绿：n 次根 bₙ^(1/n)','fill="'+muted+'"');return chartFrame('相邻比值和根值的有限序列；横线1不是采样判定器',inner);}
export function seSumsSVG(s){const all=seSamples(s),rows=all.slice(0,s.probe),min=Math.min(0,...all.map(r=>r.sum)),max=Math.max(.1,...all.map(r=>r.absoluteSum)),padding=(max-min)*.09,g=grid(s.N,min-padding,max+padding);let inner=g.content;for(const [key,c,dash] of [['absoluteSum',orange,'stroke-dasharray="6 4"'],['sum',green,'']]){inner+=`<path d="${linePath(rows,g.x,g.y,key)}" fill="none" stroke="${c}" stroke-width="2.5" ${dash}/>`;const r=rows.at(-1);inner+=`<circle cx="${g.x(r.n)}" cy="${g.y(r[key])}" r="5" fill="${c}"/>`;}
 inner+=text(g.left,17,'绿：位置 Sₙ=Σaₖ     橙：总路程 Aₙ=Σ|aₖ|','fill="'+muted+'"');return chartFrame('带符号部分和与绝对值部分和，两本账的有限前缀',inner);}
export function seComparisonSVG(s){const all=seSamples(s).map(r=>({...r,quotient:r.comparison>0?Math.log10(r.comparison):null})),rows=all.slice(0,s.probe),values=all.map(r=>r.quotient).filter(Number.isFinite),lo=Math.min(-.2,...values)-.2,hi=Math.max(.2,...values)+.2,g=grid(s.N,lo,hi),c=seComparison(s);let inner=g.content;inner+=`<line x1="${g.left}" x2="${g.right}" y1="${g.y(0)}" y2="${g.y(0)}" stroke="${blue}" stroke-dasharray="5 5"/>`;for(const [v,label] of [[c.lower,'解析下界'],[c.upper,'解析上界']])if(c.kind==='finite'||c.kind==='oscillates'){if(v>0){inner+=`<line x1="${g.left}" x2="${g.right}" y1="${g.y(Math.log10(v))}" y2="${g.y(Math.log10(v))}" stroke="${green}" stroke-dasharray="3 5"/>`+text(g.right,g.y(Math.log10(v))-7,`${label}：${seNum(v)}`,'text-anchor="end" fill="'+green+'"');}}
 inner+=`<path d="${linePath(rows,g.x,g.y,'quotient')}" fill="none" stroke="${orange}" stroke-width="2.2"/>`;for(const r of rows){if(r.quotient===null)inner+=text(g.x(r.n),g.bottom-4,'×','text-anchor="middle" fill="'+blue+'"');else inner+=`<circle cx="${g.x(r.n)}" cy="${g.y(r.quotient)}" r="2.5" fill="${orange}"/>`;}
 inner+=text(g.left,17,'纵轴 log₁₀(bₙ/vₙ)；0 代表商为 1。× 表示零项，不取 log 0。','fill="'+muted+'"');return chartFrame('固定参照后的商，区分收敛、摆动与单向比较',inner);}
export function seIntegralSVG(s){const valid=seIntegral(s).valid;if(!valid)return chartFrame('当前例子不满足最终单调性，不能画作递减矩形保证',`<rect x="25" y="25" width="710" height="270" rx="15" fill="#faf2e6"/>${text(380,105,'不能先画面积，再悄悄删除前提。','text-anchor="middle" fill="'+orange+'" class="se-svg-lead"')}${text(380,145,'当前幅度在无穷多个位置上升。','text-anchor="middle" fill="'+ink+'"')}${text(380,181,'标准积分判别不适用；去“根值 / 比较”寻找另一条路线。','text-anchor="middle" fill="'+muted+'"')}`);
 const count=10,start=Math.max(1,s.probe-count+1),end=start+count,top=seContinuous(s,start)*1.18,g=grid(count+1,0,top),xx=x=>g.left+(x-start)/count*(g.right-g.left);let inner='';for(let k=0;k<=4;k++)inner+=text(g.left-10,g.y(top*k/4)+4,seNum(top*k/4,3),'text-anchor="end" fill="'+muted+'"');for(let n=start;n<end;n++){const v=seContinuous(s,n),u=seContinuous(s,n+1),width=xx(n+1)-xx(n);inner+=`<rect x="${xx(n)}" y="${g.y(v)}" width="${width}" height="${g.bottom-g.y(v)}" fill="#f2dfc4" stroke="#d8b88d" stroke-width=".6"/><rect x="${xx(n)}" y="${g.y(u)}" width="${width}" height="${g.bottom-g.y(u)}" fill="#d6e5c1" opacity=".8"/>`;if(n===start||n===end-1||n===start+5)inner+=text(xx(n),g.bottom+22,String(n),'text-anchor="middle" fill="'+muted+'"');}let d='';for(let k=0;k<=150;k++){const x=start+count*k/150;d+=`${k?'L':'M'}${xx(x)},${g.y(seContinuous(s,x))} `;}inner+=`<path d="${d}" fill="none" stroke="${green}" stroke-width="2.4"/>`+text(g.left,17,'左端点矩形 ≥ 曲线面积 ≥ 右端点矩形（单位宽）','fill="'+muted+'"');return chartFrame('标准积分条件下的逐格矩形夹逼；这里只显示有限段',inner);}
export function seTermsSVG(s){const start=Math.max(1,s.probe-11),items=Array.from({length:s.probe-start+1},(_,j)=>({n:start+j,a:seA(s,start+j)})),max=Math.max(...items.map(r=>Math.abs(r.a)),1e-300),w=760,h=135,left=62,right=730,mid=64,bar=(right-left)/12;let inner=`<line x1="${left}" x2="${right}" y1="${mid}" y2="${mid}" stroke="#d6dfca"/>`;for(let i=0;i<items.length;i++){const r=items[i],hh=Math.abs(r.a)/max*35,x=left+i*bar+6;inner+=`<rect x="${x}" y="${r.a>=0?mid-hh:mid}" width="${bar-12}" height="${Math.max(hh,.8)}" rx="2" fill="${r.a>=0?green:orange}"/>`+text(x+(bar-12)/2,118,String(r.n),'text-anchor="middle" fill="'+muted+'"');}inner+=text(left,16,'最近 12 项 · 柱高按当前窗口缩放，只展示符号与局部大小','fill="'+muted+'"');return chartFrame('逐项增量：正项向上，负项向下；高度仅作窗口内对比',inner,w,h);}
