import { icon } from './icons.js';
import { seriesFamilies, seriesMethods, seriesMethodNames, seEscape, seNum, seReference, seTruth } from './series-math.js';
import { seScenarios } from './series-state.js';
import { pageGuide } from './page-guide.js';
export const seNodeInfo={
 ratio:{title:'比值条件',short:'普通极限 L < 1',formula:'L = lim bₙ₊₁/bₙ 存在，且 L < 1',given:'bₙ=|aₙ|，从某项起 bₙ>0。这里的节点是“收敛充分条件”，不是所有比值判别版本的总称。',route:'ratio-root',intuition:'每一步最终都按某个固定的 q<1 缩小，便能被几何尾部控制。'},
 root:{title:'根值条件',short:'上极限 ρ < 1',formula:'ρ = limsup bₙ^(1/n) < 1',given:'允许非负项和无穷多个零。上极限不是最后一个点，也不是有限窗口的最大值。',route:'root-absolute',intuition:'不要求每一步都缩小，只要求整体平均的指数衰减速度足够快。'},
 limit:{title:'极限比较',short:'0 < c < ∞ · v 收敛',formula:'bₙ/vₙ → c ∈ (0,∞)，Σvₙ < ∞',given:'vₙ>0 且已知其敛散；图上只画标准双向版的收敛分支。c=0、∞ 的单向扩展在实验里另列。',route:'limit-comparison',intuition:'最终相差一个非零有限倍，就能上下同时夹住。先固定参照再谈逆推。'},
 comparison:{title:'直接比较',short:'尾部上界 · v 收敛',formula:'0 ≤ bₙ ≤ C vₙ（n≥N₀），Σvₙ < ∞',given:'C>0，参照必须已知收敛。换参照会改变当前证据，不会改变原级数的敛散。',route:'comparison-absolute',intuition:'不要求商收敛，只需一张能罩住尾部的可求和上界。'},
 integral:{title:'积分条件',short:'正 · 递减 · 可积',formula:'bₙ=f(n)，f>0 连续、最终不增，∫f < ∞',given:'标准积分判别对 Σbₙ 使用；图中取收敛分支。不能只写一个积分而忽略最终单调性。',route:'integral-absolute',intuition:'递减保证单位宽的矩形与曲线面积能彼此夹住。'},
 leibniz:{title:'Leibniz 条件',short:'交错 · bₙ ↓ 0',formula:'aₙ=(−1)ⁿ⁻¹bₙ，bₙ≥0 最终不增，bₙ→0',given:'有限前缀不影响收敛。这里证明的是带符号的 Σaₙ 收敛，不是自动证明绝对或条件收敛。',route:'leib-convergence',intuition:'向前、向后的小步相互抵消；偶数与奇数部分和夹向同一点。'},
 absolute:{title:'绝对收敛',short:'Σ|aₙ| < ∞',formula:'Σbₙ < ∞，bₙ=|aₙ|',given:'这是性质，不是一种独立的“判别法”。各条绿色路线把不同充分条件送到同一个结论。',route:'absolute-convergence',intuition:'即使把每一步都改成向前，总路程仍有限。'},
 convergence:{title:'原级数收敛',short:'Sₙ 有有限极限',formula:'Sₙ = Σₖ₌₁ⁿ aₖ → S ∈ ℝ',given:'若同时 Σ|aₙ|=∞，才叫条件收敛；正项级数收敛与绝对收敛是同一件事。',route:'convergence-not-absolute',intuition:'到达的位置趋于一个有限终点，不要求走过的总路程有限。'},
 zero:{title:'通项趋零',short:'必要，不充分',formula:'aₙ → 0',given:'通项不趋零可以直接判发散；通项趋零不能直接判收敛。',route:'zero-not-convergence',intuition:'步子越来越小，不代表走过的总距离有上限。'}
};
// Each arrow has an explicit logical scope, witnesses and an authored proof.
export const seEdges={
 'ratio-root':{from:'ratio',to:'root',type:'theorem',title:'逐步缩小 ⇒ 平均指数衰减',question:'比值条件为什么比根值条件更强？',given:'bₙ>0 从某项起成立；普通比值极限 L 存在且 L<1。',examples:['geometric','paired','sparse'],steps:[['挑一个缓冲值','选择 L<r<1。极限定义保证从某个 N 起，每一次 bₙ₊₁/bₙ 都不超过 r。','∀n≥N，bₙ₊₁ ≤ r bₙ'],['连乘，不看某一步','逐次使用同一个界，得到整个尾部的几何包络。有限前缀只形成一个常数。','bₙ ≤ b_N r^(n−N) = C rⁿ'],['取 n 次根','常数的 n 次根趋于 1，因此根值的上极限不超过 r<1。','limsup bₙ^(1/n) ≤ r < 1'],['为什么逆推不行','c奇=1、c偶=4，bₙ=cₙ2⁻ⁿ。根值趋于 1/2，比值却在 2 与 1/8 之间交替。','根值条件成立 ⇏ 普通比值极限存在']],warning:'若用“比值上极限<1”的增强版，它仍能推出根值条件；但“比值上极限>1”本身不能判发散。齿状例子正是反例。'},
 'root-absolute':{from:'root',to:'absolute',type:'theorem',title:'指数包络 ⇒ 绝对收敛',question:'为什么不必要求每一步都缩小？',given:'ρ=limsup bₙ^(1/n)<1，bₙ=|aₙ|≥0。',examples:['paired','square','sparse'],steps:[['不是有限最大值','取 ρ<r<1。由上极限的定义，从某个 N 起所有根值都小于 r。','∀n≥N，bₙ^(1/n)≤r'],['还原大小','两边取 n 次幂。尖峰可以有，只要最终都在这个几何包络内。','0≤bₙ≤rⁿ'],['用一个已知可求和的参照','几何尾部有有限总和，比较判别给出 Σbₙ 收敛。','Σₙ₌_N^∞ bₙ ≤ rᴺ/(1−r)'],['边界 1 留给别的方法','1/n 和 1/n² 的根值都趋于 1，一个发散一个收敛。','ρ=1 ⇒ 本判别法不作决定']],warning:'ρ>1 才能用根值判别直接否定通项趋零；ρ=1 不是“收敛较慢”的保证。'},
 'limit-comparison':{from:'limit',to:'comparison',type:'theorem',title:'非零有限比 ⇒ 双侧比较',question:'“差不多大”如何变成可用的不等式？',given:'同一参照 vₙ>0，bₙ/vₙ→c∈(0,∞)。图上另假设 Σvₙ 收敛。',examples:['square','wavy','smallLimit'],steps:[['留出 c 的一半','用极限定义取误差 c/2。分式从某项起落在固定区间。','c/2 ≤ bₙ/vₙ ≤ 3c/2'],['乘回正参照','分母正，因此不等号方向不变。上下界都能传递信息。','(c/2)vₙ ≤ bₙ ≤ (3c/2)vₙ'],['决定哪一侧有用','参照收敛时用上界；参照发散时用下界。这给出同敛散。','Σvₙ<∞ ⇒ Σbₙ<∞；Σvₙ=∞ ⇒ Σbₙ=∞'],['反向要求太多','固定 vₙ=1/n²。取奇项 vₙ、偶项 3vₙ：始终夹住，但商没有极限。','vₙ≤bₙ≤3vₙ ⇏ bₙ/vₙ 收敛']],warning:'c=0 配收敛参照、c=∞ 配发散参照，仍有单向结论；不是“c不在(0,∞)，所有比较就没用”。'},
 'comparison-absolute':{from:'comparison',to:'absolute',type:'theorem',title:'可求和上界 ⇒ 绝对收敛',question:'为什么不需要求出原级数的和？',given:'尾部有 0≤bₙ≤C vₙ，C>0，Σvₙ 收敛。',examples:['wavy','sparse','wrongDirection'],steps:[['先处理有限前缀','从 N₀ 开始比较就够了。前面有限项不改变收敛。','Σbₙ = 有限前缀 + 尾部'],['管住任意尾块','对任意 m≥n≥N₀，逐项加不等式。','0≤Σₖ₌ₙᵐ bₖ≤C Σₖ₌ₙᵐ vₖ'],['让整个尾块变小','参照收敛意味着其任意足够晚尾块都小，由 Cauchy 准则得到结论。','任给 ε>0，充分大的 n 后，上界 < ε'],['错方向不会传递结论','小于发散级数不能判收敛。1/n² 和 1/(n ln n) 最终都小于 1/n。','bₙ≤vₙ 且 Σvₙ=∞ ⇒ 仍无法判断']],warning:'把比较法理解为“存在任意一个参照”时，可以平凡地选 v=b，因此不能笼统说它严格弱于绝对收敛。本图研究已选定且已知敛散的参照证据。'},
 'integral-absolute':{from:'integral',to:'absolute',type:'theorem',title:'递减矩形 ⇒ 面积控制',question:'单调性为什么不是可删掉的小字？',given:'从某个整数 N 起，f 正、连续、不增，bₙ=f(n)。',examples:['square','logConverges','logDiverges'],steps:[['一格一格地夹','递减使 [n,n+1] 上的曲线夹在右、左端点高度之间。','f(n+1) ≤ ∫ₙⁿ⁺¹ f(x)dx ≤ f(n)'],['累加所有矩形','对任意 M≥N 求和，矩形与面积相差至多一个端点项。','∫_N^(M+1)f ≤ Σₙ₌_N^M bₙ ≤ f(N)+∫_N^M f'],['有界性一起传递','非负项部分和递增。积分有限当且仅当部分和有界，故同敛散。','Σbₙ 收敛 ⇔ ∫_N^∞ f(x)dx 有限'],['不等于指数条件','1/n² 递减可积却根值=1；齿状几何根值<1却无限次上升。','标准积分条件 与 根值条件 互不蕴含']],warning:'若只写 ∫f<∞，却允许在整数处设置窄而高的尖峰，结论会失败。分组后积分或可积包络是新的论证，不是偷删前提。'},
 'leib-convergence':{from:'leibniz',to:'convergence',type:'theorem',title:'交错抵消 ⇒ 原级数收敛',question:'总路程无穷，终点仍能固定吗？',given:'aₙ=(−1)ⁿ⁻¹bₙ，bₙ≥0 最终不增且趋零；可去掉有限前缀。',examples:['altHarmonic','altGeometric','irregular'],steps:[['把两步看成一对','在从正项开始的尾部，S₂ₘ 的下一对增量非负，偶数部分和递增。','S₂ₘ₊₂−S₂ₘ=b₂ₘ₊₁−b₂ₘ₊₂≥0'],['另一边向下靠近','奇数部分和递减，且每个偶数部分和在相应奇数部分和下方。','S₂ₘ ≤ S₂ₘ₊₁；S₂ₘ₊₃≤S₂ₘ₊₁'],['缝隙消失','两边之差就是下一项的幅度，趋于零；单调有界保证夹向同一个极限。','S₂ₘ₊₁−S₂ₘ=b₂ₘ₊₁→0'],['不要多下一个结论','交错调和条件收敛；交错几何绝对收敛。Leibniz 对两者都适用。','Leibniz ⇒ 收敛；不自动 ⇒ 条件收敛']],warning:'交错符号、单调幅度、幅度趋零是三件事。仅有符号交错不够；不满足此充分条件也不等于发散。'},
 'absolute-convergence':{from:'absolute',to:'convergence',type:'theorem',title:'总路程有限 ⇒ 终点存在',question:'为什么绝对收敛是更强的性质？',given:'Σ|aₙ| 收敛。这里不限制符号。',examples:['altGeometric','altHarmonic','altPaired'],steps:[['看任意一段尾部','不必知道各项正负；三角不等式给出统一上界。','|Σₖ₌ₙᵐ aₖ| ≤ Σₖ₌ₙᵐ |aₖ|'],['把已知完备性用进来','绝对值级数收敛，右侧任意足够晚尾块都趋小。','∀ε>0，∃N，m≥n≥N ⇒ |Σₖ₌ₙᵐ aₖ|<ε'],['部分和是 Cauchy 列','实数完备性保证 Sₙ 收敛到有限实数。','Σ|aₙ|<∞ ⇒ Σaₙ 收敛'],['反向留下抵消空间','交错调和部分和收敛，但绝对值是发散的调和级数。','Σaₙ 收敛 ⇏ Σ|aₙ| 收敛']],warning:'若某种正项判别证明 Σ|aₙ| 发散，它仅排除了绝对收敛；除非另有条件，不能据此断言带符号的原级数发散。'},
 'convergence-zero':{from:'convergence',to:'zero',type:'theorem',title:'终点存在 ⇒ 单步消失',question:'通项趋零究竟能告诉我们什么？',given:'Sₙ=Σₖ₌₁ⁿ aₖ 收敛到有限实数 S。',examples:['geometric','harmonic','growing'],steps:[['从位置差找单步','第 n 项正是前后两次部分和的差。','aₙ=Sₙ−Sₙ₋₁'],['两个位置去同一个地方','分别取极限即可。','lim aₙ=S−S=0'],['逆否命题合法','通项不趋零时，原级数一定不收敛；不必再用其他方法。','aₙ 不趋零 ⇒ Σaₙ 发散'],['逆命题不合法','调和项趋零，但每个二进区块都积累至少 1/2。','Σₙ₌_(2ᵏ+1)^(2ᵏ⁺¹) 1/n ≥ 1/2']],warning:'“项越来越小”“部分和几乎不动”“收敛”是三个不同层次。有限图像无法证明无穷尾部。'},
 'root-not-ratio':{from:'root',to:'ratio',type:'counter',title:'根值 ⇏ 比值',question:'整体下降，为什么局部可以持续跳高？',given:'对照普通比值极限版本；b₂ₖ₋₁=2⁻⁽²ᵏ⁻¹⁾，b₂ₖ=4·2⁻²ᵏ。',examples:['paired','geometric'],steps:[['先确认左边','系数始终介于 1 和 4，取 n 次根后趋于 1。','bₙ^(1/n)=cₙ^(1/n)/2 → 1/2'],['再否定右边','从奇到偶乘 2，从偶到奇乘 1/8。这种差异永远不消失。','b₂ₖ/b₂ₖ₋₁=2；b₂ₖ₊₁/b₂ₖ=1/8'],['给出独立收敛证据','不是因为曲线看着下降，而是逐项有一个全局上界。','0≤bₙ≤4·2⁻ⁿ'],['条件集合真包含','有序的一步压缩要求更严；允许有限系数振荡的指数衰减更宽松。','比值收敛条件 ⊊ 根值收敛条件']],warning:'比值上极限=2>1 也不能在这里判发散。发散分支要求普通比值极限>1，或比值下极限>1等足够条件。'},
 'absolute-not-root':{from:'absolute',to:'root',type:'counter',title:'绝对收敛 ⇏ 根值 < 1',question:'收敛必须快得像几何级数吗？',given:'取非负项 bₙ=1/n²。',examples:['square','harmonic','geometric'],steps:[['先判它确实收敛','用递减函数 f(x)=x⁻²；积分有限。','∫₁^∞ x⁻²dx=1'],['根值却卡在边界','取对数后指数趋于零。','bₙ^(1/n)=exp(−2 ln n/n)→1'],['对照相同读数的另一例','调和级数根值也等于 1，但它发散。','1/n² 与 1/n：ρ 都是 1，结论相反'],['读懂强弱方向','根值<1 是充分、非必要条件。满足它更难，但一旦满足就能保证收敛。','根值条件 ⊊ 绝对收敛']],warning:'更强的假设通常覆盖更少的对象，不等于这条判别法对所有题都更有用。'},
 'comparison-not-limit':{from:'comparison',to:'limit',type:'counter',title:'固定参照：比较 ⇏ 极限比较',question:'为什么一张上界可以容忍不停的摆动？',given:'始终固定 vₙ=1/n²；取 b奇=v奇，b偶=3v偶。',examples:['wavy','square','smallLimit'],steps:[['上界完整成立','对每一个 n 都可以逐项核对，而且参照已知收敛。','0≤bₙ≤3vₙ，Σvₙ<∞'],['但商走向两个值','两列下标一直保持不同倍数，无法形成同一个有限极限。','b₂ₖ₋₁/v₂ₖ₋₁=1；b₂ₖ/v₂ₖ=3'],['比较结论不受影响','上界不需要商稳定，Cauchy 尾块的控制仍然有效。','Σbₙ<∞'],['锁住参照再谈逻辑','若改选 v=b，商当然恒为 1，但必须先独立知道 Σv 的敛散。','这里的反例针对“同一已选参照”']],warning:'不能把“固定参照的条件严格较强”，扩大成“极限比较永远不如比较法”。实际选参照的难易是另一回事。'},
 'convergence-not-absolute':{from:'convergence',to:'absolute',type:'counter',title:'收敛 ⇏ 绝对收敛',question:'只看最终位置，会漏掉多少路程？',given:'aₙ=(−1)ⁿ⁻¹/n。',examples:['altHarmonic','altGeometric'],steps:[['带着符号求和','幅度递减到零，Leibniz 给出原级数收敛。','S₂ₘ ↑ S，S₂ₘ₊₁ ↓ S'],['去掉符号重新记账','绝对值级数就是调和级数。','A_N=Σₙ₌₁ᴺ |aₙ|=Σₙ₌₁ᴺ 1/n'],['证明总路程没有上界','每个二进区块的贡献至少 1/2，区块可以无穷多。','A_(2ᵏ) ≥ 1+k/2'],['现在才能叫条件收敛','两个判断都做完，而不是看到交错就命名。','原级数收敛 且 绝对值级数发散']],warning:'蓝图展示有限 S_N、A_N；解析论证才能决定无穷尾部。'},
 'root-integral':{from:'root',to:'integral',type:'incomparable',title:'根值条件 与 积分条件：互不蕴含',question:'两条路线为什么不能排出谁高谁低？',given:'比较“根值上极限<1”与“正连续最终不增延拓且积分有限”这两组充分条件。',examples:['paired','square','geometric'],steps:[['找到第一方向的反例','齿状几何的根值趋于 1/2，但每个奇项后都上升，因此没有最终递减的穿点延拓。','根值条件成立，标准积分条件失败'],['找到反方向的反例','1/n² 有正连续递减可积延拓，但根值趋于 1。','标准积分条件成立，根值<1 失败'],['不要把证明失败误认作发散','两边的反例本身都收敛，失败的是特定条件。','两组条件都能推出绝对收敛'],['保留两条互补路线','一个管指数速度，一个管形状与面积；各自拥有另一边接不住的例子。','根值条件 ⇏ 积分条件；积分条件 ⇏ 根值条件']],warning:'不比较“一切可能的积分技巧”。对齿状几何先用单调上界再积分属于比较法与积分法组合，不是原序列满足标准积分条件。'},
 'leib-absolute':{from:'leibniz',to:'absolute',type:'incomparable',title:'Leibniz 条件 与 绝对收敛：互不蕴含',question:'符号抵消与总路程有限，是同一种信息吗？',given:'比较两个不同充分条件，它们共同推出原级数收敛。',examples:['altHarmonic','altPaired','altGeometric'],steps:[['Leibniz 不保证绝对收敛','交错调和满足全部 Leibniz 条件，绝对值却发散。','Leibniz ⇏ 绝对收敛'],['绝对收敛不保证幅度递减','交错齿状几何绝对值≤4·2⁻ⁿ，但每逢奇到偶，幅度都上升。','绝对收敛 ⇏ Leibniz 条件'],['两者又能同时成立','交错几何幅度递减到零，且绝对值可求和。','两条件有交集，不互相排斥'],['不要混淆分类','“交错”描述符号排列；“条件收敛”描述两种级数的不同结论。','交错 ≠ 条件收敛']],warning:'非正项级数要明确现在判的是 Σaₙ，还是 Σ|aₙ|；页面始终给出两本账。'},
 'convergence-not-leib':{from:'convergence',to:'leibniz',type:'counter',title:'交错收敛 ⇏ Leibniz 条件',question:'幅度不单调，就一定无法靠抵消收敛吗？',given:'a₂ₖ₋₁=1/k，a₂ₖ=−(1/k+1/k²)。',examples:['irregular','altHarmonic'],steps:[['先找到前提失败处','每个负项幅度都比前一个正项更大，所以无限次上升。','b₂ₖ>b₂ₖ₋₁'],['计算偶数部分和','每对留下 −1/k²，因此偶数部分和收敛。','S₂ₘ=−Σₖ₌₁ᵐ 1/k²'],['不能只到分组这一步','奇数部分和比前一个偶数部分和多 1/(m+1)，这个差趋零。','S₂ₘ₊₁−S₂ₘ=1/(m+1)→0'],['最后判断绝对值','每对绝对值至少是 2/k，所以绝对值级数发散。','条件收敛，但标准 Leibniz 条件不满足']],warning:'分组后的级数收敛一般不自动推出原级数收敛；此处必须另证未完成块的余项趋零。'},
 'zero-not-convergence':{from:'zero',to:'convergence',type:'counter',title:'通项趋零 ⇏ 收敛',question:'每一步越来越小，为什么还会走到无穷远？',given:'比较 1/n 与 1/n²：它们的项都趋零。',examples:['harmonic','square','logDiverges'],steps:[['先确认必要条件','1/n 确实趋零，这一关并没有失败。','aₙ→0'],['换一个观察单位','把项分成 2ᵏ 到 2ᵏ⁺¹ 附近的区块，而不只看单项。','每块有 2ᵏ 项，每项至少 1/2ᵏ⁺¹'],['区块贡献不消失','无穷多个至少 1/2 的增量，让部分和没有上界。','每块总和 ≥ 1/2'],['同一必要条件，两种结局','1/n² 则有积分上界而收敛。必要条件不能代替充分条件。','aₙ→0：只能说尚未被这条必要条件排除']],warning:'滑块把 N 调大不会“证明发散”；这里的证明覆盖任意多个区块。'}
};
export const seQuestions=[
 {id:'one',question:'比值极限与根值上极限都等于 1，能判断什么？',options:['必发散','必条件收敛','这两条判别均无法判断，需要换路线'],correct:2,reason:'1/n、1/n²、交错调和提供不同结论，临界读数本身不够。'},
 {id:'spike',question:'比值上极限大于 1，但根值上极限为 1/2，哪个结论正确？',options:['必发散，因为比值超过 1','绝对收敛；比值上极限大于 1 不是充分发散条件','根值上极限不可能为 1/2'],correct:1,reason:'齿状几何的比值在 2 和 1/8 交替，而根值趋于 1/2。'},
 {id:'signed',question:'积分判别证明 Σ|aₙ| 发散，原带符号级数会怎样？',options:['仍需判断，可能条件收敛也可能发散','一定发散','一定满足 Leibniz'],correct:0,reason:'它只排除绝对收敛。比较调和与交错调和即可区分。'},
 {id:'zero',question:'bₙ/vₙ→0，参照 Σvₙ 发散，能判断 Σbₙ 吗？',options:['能，趋零说明小很多，必收敛','能，它们同敛散','不能，仅“小于发散参照”不够'],correct:2,reason:'以 vₙ=1/n：1/n² 收敛，而 1/[(n+1)ln(n+1)] 发散，商都趋零。'},
 {id:'limit',question:'标准双向极限比较要求 0<c<∞。若 c=0 且参照收敛呢？',options:['所有比较都不可用','仍可用单向上界推出绝对值级数收敛','必发散'],correct:1,reason:'最终 bₙ≤vₙ；这是一条有效的单向扩展，不应被“标准版前提不满足”掩盖。'},
 {id:'incomparable',question:'怎样证明根值收敛条件和标准积分收敛条件互不可比？',options:['找两个都不能判断的例子','各找一个只满足其中一组条件的例子','只需一个两者都满足的例子'],correct:1,reason:'齿状几何与 1/n² 分别见证两个方向都不能推出；一个方向的反例不够。'},
 {id:'leib',question:'标准 Leibniz 条件成立，能直接说“条件收敛”吗？',options:['能，符号交错就够','不能；还要检查绝对值级数是否发散','不能，它连原级数收敛也无法保证'],correct:1,reason:'交错几何同时满足 Leibniz 和绝对收敛。交错是形式，条件收敛是分类结论。'},
 {id:'group',question:'不单调抵消例子的偶数部分和收敛，为什么还要检查奇数部分和？',options:['分组收敛并不自动保证整个部分和列收敛','偶数项永远比奇数项重要','只为了让图画得平滑'],correct:0,reason:'必须控制未完成块。这里最后一项 1/(m+1)→0 才能把两个子列接到同一个极限。'}
];
export function seEquation(x){return `<div class="se-equation">${seEscape(x)}</div>`;}
function journey(s){return `<nav class="se-journey" aria-label="级数实验学习路径">${[['map','条件地图'],['workshop','拿级数来试'],['proof','为什么能推出'],['challenge','自己判断']].map(([k,v],i)=>`<button data-se-screen="${k}"${s.screen===k?' aria-current="step"':''}><small>0${i+1}</small>${v}<span>→</span></button>`).join('')}</nav>`;}
function context(s){const f=seriesFamilies[s.family];return `<div class="se-context"><label for="se-family"><small>同一个级数 · 沿着不同路线检验</small><select id="se-family">${Object.entries(seriesFamilies).map(([id,f])=>`<option value="${id}"${id===s.family?' selected':''}>${f.name}</option>`).join('')}</select></label><div class="se-context-formula" id="se-formula">${seEscape(f.formula)}</div><label class="se-sign"><input type="checkbox" id="se-signed"${s.signed?' checked':''}><span>按 (−1)ⁿ⁻¹ 交错赋号</span></label></div>`;}
function routeIntro(s){const e=seEdges[s.edge];return `<section class="se-route-intro"><div><span class="eyebrow">${e.type==='theorem'?'A THEOREM, WITH HYPOTHESES':e.type==='incomparable'?'TWO DIRECTIONS, TWO WITNESSES':'TEST THE REVERSE'}</span><h2>${e.title}</h2><p>${e.question}</p></div><button class="text-button" data-se-screen="proof">${e.type==='theorem'?'为什么成立':'反例在哪里'} →</button><div id="se-witness"></div><div class="se-scenarios">${e.examples.map(key=>`<button class="button" data-se-scenario="${key}">${seScenarios[key].label} ↗</button>`).join('')}</div><p class="se-small">点击案例会替换级数参数；切换页面会保留当前级数。当前一个正例不能证明一般蕴含。</p></section>`;}
function controls(s){return `<aside class="card se-controls"><span class="eyebrow">CHANGE THE EVIDENCE</span><h2>不是换结论，是换条件。</h2><div id="se-parameter"></div><label for="se-reference" class="se-label">比较时，固定哪一个参照？</label><select id="se-reference">${[['natural','匹配参照（对数例用调和项）'],['harmonic','1/n · 已知发散'],['square','1/n² · 已知收敛'],['geometric','2⁻ⁿ · 已知收敛']].map(([k,v])=>`<option value="${k}"${s.ref===k?' selected':''}>${v}</option>`).join('')}</select><p class="se-small" id="se-reference-note"></p><div class="divider"></div><label class="se-label" for="se-N">显示前 N 项 <output id="se-N-value"></output></label><input type="range" id="se-N" min="8" max="256" step="1" value="${s.N}"><label class="se-label" for="se-probe">逐项揭开 <output id="se-probe-value"></output></label><input type="range" id="se-probe" min="1" max="${s.N}" step="1" value="${s.probe}"><button class="button primary full-width" data-se-action="play" aria-pressed="false">▶ 逐项累积</button><button class="button full-width" data-se-action="export">${icon('download')} 导出当前有限数据</button><p class="se-small">“逐项”只改变可见前缀。结论来自公式与证明，不从最后一项、有限上界或看似稳定的部分和推断。</p></aside>`;}
function mapPage(s){return `<section class="se-map-layout"><div class="card se-map-card"><div class="se-card-head"><div><span class="eyebrow">A MAP OF CONDITIONS, NOT A LEADERBOARD</span><h2>通向收敛，不只有一条路。</h2></div><div class="se-toggle"><button data-se-layer="theorems" aria-pressed="${s.layer==='theorems'}">→ 蕴含路线</button><button data-se-layer="questions" aria-pressed="${s.layer==='questions'}">⇏ 反推挑战</button></div></div><p class="se-map-scope">统一记 bₙ=|aₙ|。图中条件均为<strong>收敛分支</strong>；点击节点看前提，点击箭头查证据。</p><div id="se-graph"></div><div class="se-graph-legend"><span><i></i> 实线：条件蕴含</span><span><i class="dash"></i> 虚线：反推不成立／互不蕴含</span><span>节点徽标：当前例子是否满足该条件</span></div></div><aside class="card se-map-aside"><span class="eyebrow">START WITH A QUESTION</span><h2>同一个级数，<br>哪些路线走得通？</h2><div id="se-parameter"></div><p>先看 1/n²：比值与根值卡在 1，但积分与比较仍能给出保证。</p><div id="se-node-detail"></div><button class="button primary full-width" data-se-screen="workshop">带着这个级数去实验 →</button><div class="se-map-note">未满足某个充分条件<br><strong>≠ 原级数发散。</strong></div></aside></section><div id="se-counter-routes" class="se-counter-routes"></div><section class="se-guide-strip"><strong>怎样读“更强”？</strong><p>条件 A ⇒ 条件 B，表示满足 A 的对象更少。判别法的版本、参照与目标结论必须先固定。没画箭头不等于已证明不可比；不可比需要两方向的反例。</p><button class="text-button" data-se-edge="root-integral">看一组真正互不可比的条件 →</button></section>`;}
function workshop(s){return routeIntro(s)+`<div class="se-workbench"><section class="card se-plot-card"><div class="se-card-head"><div><span class="eyebrow">THE SAME SERIES, DIFFERENT EVIDENCE</span><h2 id="se-plot-title">观察条件，而不是猜结论。</h2></div><div class="se-toggle"><button data-se-view="conditions" aria-pressed="${s.view==='conditions'}">条件透镜</button><button data-se-view="sums" aria-pressed="${s.view==='sums'}">两本账</button></div></div><div id="se-main-plot"></div><p class="se-plot-note" id="se-plot-note"></p><div id="se-live" class="se-live"></div><div id="se-microscope"></div></section>${controls(s)}</div><div id="se-result" class="se-result" role="status" aria-live="polite"></div><section class="card se-dashboard"><div class="se-card-head"><div><span class="eyebrow">AVAILABLE / INCONCLUSIVE / NOT APPLICABLE</span><h2>同一个级数，各条路线怎样回答？</h2></div></div><div id="se-methods"></div><p class="se-small">“前提未满足”针对这里明确写出的版本；“无法判断”是判别法的回答，不是原级数的第四种敛散类型。根值/比值的 >1 分支证明通项不趋零，与仅证明 Σ|aₙ| 发散不同。</p></section><div class="se-next"><div><strong>动画提供线索，哪一步才是保证？</strong><p>保持当前级数与参照，继续拆解这条论证。</p></div><button class="button primary" data-se-screen="proof">检查条件与证明 →</button></div>`;}
function proofPage(s){const e=seEdges[s.edge];return `<div class="se-proof-layout"><aside class="card se-proof-nav"><span class="eyebrow">TRACE THE LOGIC</span><h2>一条箭头，一份论证。</h2><label for="se-route-select" class="se-label">选择要核对的关系</label><select id="se-route-select">${Object.entries(seEdges).map(([k,e])=>`<option value="${k}"${k===s.edge?' selected':''}>${e.title}</option>`).join('')}</select><p class="se-small">这里讨论一般命题；当前级数用于对照，是否构成反例要核对前提与结论，不会改变定理本身。</p><button class="button full-width" data-se-screen="workshop">带着参数回实验 →</button><button class="text-button" data-se-screen="map">回到条件地图 ↗</button><div class="se-formal-note">ℝ 的 Cauchy 完备性连接“任意尾部都小”与“存在有限和”。可在实验 04 继续追问这个基础。</div></aside><article class="card se-proof-article"><span class="eyebrow">${e.type==='theorem'?'HYPOTHESIS → ESTIMATE → CONCLUSION':'ASSERTION → WITNESS → FAILED HYPOTHESIS'}</span><h2>${e.title}</h2><div class="se-proof-given">${seEscape(e.given)}</div><nav class="se-steps" aria-label="证明步骤">${e.steps.map((_,i)=>`<button data-se-step="${i}"${s.step===i?' aria-current="step"':''}>0${i+1}</button>`).join('')}</nav><div id="se-proof-current"></div><div class="se-proof-buttons"><button class="button" data-se-action="proof-prev">← 上一步</button><button class="button" data-se-action="proof-next">下一步 →</button></div><div class="se-warning">${seEscape(e.warning)}</div><details class="se-full-proof"><summary>展开完整四步</summary>${e.steps.map((v,i)=>`<section><h3>${i+1}. ${v[0]}</h3><p>${seEscape(v[1])}</p>${seEquation(v[2])}</section>`).join('')}</details><div class="se-scenarios">${e.examples.map(key=>`<button class="button" data-se-proof-case="${key}">${seScenarios[key].label} ↗</button>`).join('')}</div><div class="se-sources">定理参考：<a href="https://www.jirka.org/ra/html/sec_moreonseries.html" target="_blank" rel="noopener noreferrer">Jiří Lebl · Basic Analysis（根值上极限）</a>；<a href="https://openstax.org/books/calculus-volume-2/pages/5-4-comparison-tests" target="_blank" rel="noopener noreferrer">OpenStax · Comparison Tests</a>。推导在本地完整提供，链接不是运行依赖。</div></article></div>`;}
function challenge(){return `<section class="card se-quiz-card"><span class="eyebrow">EXPLAIN THE VERDICT</span><h2>会选路线，比记住名字更重要。</h2><p>先选择判断，再核对理由。遇到“无法判断”，要分清是哪个方法不知道。</p><form id="se-quiz">${seQuestions.map((q,i)=>`<fieldset><legend><span>0${i+1}</span>${q.question}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="se-${q.id}" value="${j}"><span>${seEscape(o)}</span></label>`).join('')}<div id="se-feedback-${q.id}" class="se-feedback" hidden></div></fieldset>`).join('')}<button class="button primary" type="submit">检查判断与理由 →</button><button class="button" type="button" data-se-action="quiz-reset">重新判断</button><div id="se-quiz-score" role="status" aria-live="polite"></div></form><button class="text-button" data-se-screen="workshop">带着疑问回实验 →</button></section>`;}
export function seriesPage(s){return `<section class="page-heading se-heading"><div><div class="breadcrumb">实验室 <span>/</span> 无穷级数 <span>/</span> 条件与边界</div><span class="eyebrow">EXPERIMENT 06 <span>—</span> MORE THAN ONE WAY TO CONVERGE</span><h1 id="se-title" tabindex="-1">不是谁更强，而是谁够用。</h1><p class="page-subtitle">把条件放回箭头，把符号放回级数。看清它能保证什么，也看清它没有说什么。</p></div><div class="heading-actions"><button class="button subtle" data-se-action="reset">${icon('reset')} 重置</button><button class="button subtle" data-action="share">${icon('share')} 分享实验</button></div></section>${pageGuide('series',{screen:s.screen})}${journey(s)}${context(s)}${s.screen==='map'?mapPage(s):s.screen==='workshop'?workshop(s):s.screen==='proof'?proofPage(s):challenge()}`;}
