import { tf, taylorFunctions, tNum, TAYLOR_MAX } from './taylor-math.js';
import { taylorScenarios } from './taylor-state.js';
import { icon } from './icons.js';
import { pageGuide } from './page-guide.js';
export function tyEscape(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export const tyFormula='<math display="block" aria-label="T n 等于从 k 等于零到 n 的和，f 在 a 的 k 阶导数除以 k 阶乘，乘以 x 减 a 的 k 次方"><mrow><msub><mi>T</mi><mi>n</mi></msub><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><munderover><mo>∑</mo><mrow><mi>k</mi><mo>=</mo><mn>0</mn></mrow><mi>n</mi></munderover><mfrac><mrow><msup><mi>f</mi><mrow><mo>(</mo><mi>k</mi><mo>)</mo></mrow></msup><mo>(</mo><mi>a</mi><mo>)</mo></mrow><mrow><mi>k</mi><mo>!</mo></mrow></mfrac><msup><mrow><mo>(</mo><mi>x</mi><mo>−</mo><mi>a</mi><mo>)</mo></mrow><mi>k</mi></msup></mrow></math>';
export const tyProofs = {
 coefficients:{title:'为什么偏偏是 f⁽ᵏ⁾(a)/k!？',given:'只讨论次数不超过 n 的多项式。假设 f 在 a 的前 n 阶导数存在。匹配导数不需要先假定无穷级数收敛。',steps:[
 ['从未知系数开始','以 h=x−a 为坐标。先不背公式，写 P(a+h)=c₀+c₁h+⋯+cₙhⁿ。代入 h=0，只剩 c₀，因此必须选 c₀=f(a)。','P(a)=c₀=f(a)'],
 ['为什么不会弄坏已经匹配的部分？','新项 cₖhᵏ 的前 k−1 阶导数在 h=0 都是 0。它不会改变此前的函数值、斜率和低阶导数。其第 k 阶导数恰好是 k!cₖ。','j<k ⇒ (cₖhᵏ)⁽ʲ⁾(0)=0；j=k ⇒ (cₖhᵏ)⁽ᵏ⁾(0)=k!cₖ'],
 ['依次匹配，就得到每个系数','要求 P⁽ᵏ⁾(a)=f⁽ᵏ⁾(a)，因此 k!cₖ=f⁽ᵏ⁾(a)。高于 k 的项在 a 的 k 阶导数仍为 0，故这些方程互不打架。','cₖ=f⁽ᵏ⁾(a)/k!，k=0,…,n'],
 ['唯一性，和二次项的意义','每个系数都被唯一确定，所以这是次数不超过 n 的唯一匹配多项式。二阶导数描述斜率怎样变化；平面曲线的几何曲率是 |f″|/(1+f′²)^(3/2)。匹配一、二阶导数后，才同时匹配曲率。','Tₙ⁽ʲ⁾(a)=f⁽ʲ⁾(a)，0≤j≤n；某个系数为零时，次数可以小于 n。']
 ],warning:'动画的过渡曲线 Q=Tₖ₋₁+λcₖhᵏ，在 0<λ<1 时一般还没有匹配第 k 阶导数。如果 cₖ=0，这一阶本来就无须修正。'},
 remainder:{title:'相同的局部信息，怎样给出误差？',given:'采用清楚而充分的假设：f 在包含 a 和 x 的开区间上属于 Cⁿ⁺¹。令 Rₙ=f−Tₙ。不可跨过原函数的奇点。',steps:[
 ['从基本定理开始','n=0 时，f(x)=f(a)+∫ₐˣ f′(t)dt。连续积分、分部积分 n 次得到有限 Taylor 公式；x<a 时积分方向同时改变，公式仍成立。','Rₙ(x)=1/n! ∫ₐˣ f⁽ⁿ⁺¹⁾(t)(x−t)ⁿdt'],
 ['把未知函数夹住','在连接 a 与 x 的整个闭区间上，若 |f⁽ⁿ⁺¹⁾(t)|≤M，则对积分取绝对值，再积分 |x−t|ⁿ。这里的 M 不是 |f⁽ⁿ⁺¹⁾(a)|，也不是有限采样最大值。','|Rₙ(x)|≤M|x−a|ⁿ⁺¹/(n+1)!'],
 ['固定 n，让 x 靠近 a','在固定的小邻域内 M 有界。于是 Rₙ/|x−a|ⁿ 的绝对值不超过 M|x−a|/(n+1)!，随 x→a 趋零。这是固定阶数的局部逼近。','固定 n：Rₙ(x)=o(|x−a|ⁿ)，x→a'],
 ['不要偷换成 n→∞','当 x 固定而阶数变化时，M 一般也随 n 变化，不能忽略它。“每个 n 都有局部小余项”，不等于“固定 x 时余项随 n 趋零”。连续导数下的积分中值定理还给出某个未知 ξ 的 Lagrange 形式。','Rₙ(x)=f⁽ⁿ⁺¹⁾(ξ)(x−a)ⁿ⁺¹/(n+1)!，ξ 在 a 与 x 之间']
 ],warning:'界太大，只说明这条充分估计不够精细，不证明实际逼近很差。误差读数接近浮点分辨率时，也不证明 Rₙ=0。'},
 convergence:{title:'什么时候无穷级数真的等于函数？',given:'对每个固定的 x 分别研究 n→∞。解析证明与屏幕最多 12 阶的数值轨迹是两种不同证据。',steps:[
 ['真正要控制的是余项','f(x)−Tₙ(x)=Rₙ(x)。所以 Tₙ(x)→f(x) 当且仅当 Rₙ(x)→0。eˣ 的连接区间上可以取 M=e^max(a,x)，正弦与余弦可以取 M=1，这些界与 n 无关。','|x−a|ⁿ⁺¹/(n+1)!→0 ⇒ 指数、正弦、余弦对每个实数 x 都收敛到 f(x)'],
 ['几何级数：用有限恒等式看半径','对 1/(1−x)，令 u=(x−a)/(1−a)。有限求和直接给出余项；它在 x≠1 时成立，即使 x 在收敛区间外。|u|<1 时余项趋零；|u|≥1 时级数项不趋零。','Rₙ(x)=uⁿ⁺¹/(1−x)；收敛并等于 f ⇔ |x−a|<|1−a|'],
 ['对数：不要把两个端点一刀切','a>−1，令 u=(x−a)/(1+a)。有限几何恒等式积分给出 ln(1+u) 的展开。|u|<1 时余项可界为 |u|ⁿ⁺¹/((n+1)(1−|u|))。u=1 时交错调和级数收敛到 ln 2；u=−1 时原函数无定义，级数也发散。','ln(1+x)=ln(1+a)+∑ₖ₌₁∞(−1)ᵏ⁻¹uᵏ/k，−1<u≤1'],
 ['域、半径、固定阶误差，是三件事','对数在整个 x>−1 上都有定义，但以 a 展开的级数只在 −1<x≤1+2a 等于它。有限 n 时也不能保证每加一阶误差变小。例如 eˣ 在 a=0,x=−2：T₀=1，T₁=−1，后者误差更大。','|e⁻²−1|=1−e⁻² < 1+e⁻²=|e⁻²−(−1)|']
 ],warning:'收敛半径不是“这一阶的准确半径”。半径描述 n→∞；有限阶达到某个误差阈值的区域，取决于 n、阈值以及余项估计。'},
 flat:{title:'所有阶导数都知道，仍然不够？',given:'定义 g(0)=0；x≠0 时 g(x)=exp(−1/x²)。此实验只在 a=0 展开。',steps:[
 ['指数衰减快过任意幂','对任意整数 m≥0，令 t=1/x²→∞。利用 eᵗ≥tᵖ/p!，选整数 p>m/2，可得 |x|⁻ᵐe⁻¹⁄ˣ²≤p! t^(m/2−p)→0。','∀m≥0：|x|⁻ᵐ exp(−1/x²)→0'],
 ['逐阶求导仍有同一种形状','在 x≠0 时，第 k 阶导数是 Pₖ(1/x)exp(−1/x²)，Pₖ 是多项式。求导之后仍是这一形式。假设在 0 的第 k 阶导数为 0，差商再除以 x，仍趋零，因此下一阶导数也存在且为 0。','g⁽ᵏ⁾(0)=0，对每个 k 成立；各阶导数在 0 连续'],
 ['每个有限阶，都局部逼近得极好','全部系数为零，所以 Tₙ≡0，余项就是 g。对固定 n，有 g(x)/|x|ⁿ→0；这完全符合有限阶 Taylor 的局部结论。','固定 n：Rₙ(x)=o(|x|ⁿ)，x→0'],
 ['但固定 x≠0，增加阶数什么也没改变','对固定非零 x，Tₙ(x)=0 对所有 n 成立，Rₙ(x)=exp(−1/x²)>0。Taylor 级数收敛半径是 ∞，和函数在非零点却不同。错的不是收敛，而是“收敛的和一定是原函数”的推断。','n→∞：Tₙ(x)→0≠g(x)，x≠0']
 ],warning:'“无限可微”与“解析”不同。不要把这个例子的收敛半径写成 0；零级数在所有实数处都收敛。'}
};
export const tyQuestions=[
 {id:'factorial',question:'想加入 c₃(x−a)³，只改变第 3 阶导数而不破坏前两阶，应选什么？',options:['c₃=f‴(a)。','c₃=f‴(a)/3!，因为三次求导带来 3!。','必须重新拟合原来的 c₀、c₁、c₂。'],correct:1,reason:'(x−a)³ 的前两阶导数在 a 为零，第 3 阶为 3!。这是逐层构造不会相互破坏的原因。'},
 {id:'zero',question:'sin x 在 a=0 从 T₁ 升到 T₂，曲线没有变化。这是程序出错了吗？',options:['是，升一阶必须产生非零项。','不是，sin″(0)=0；二阶导数本来已经匹配。','说明 sin x 是一次多项式。'],correct:1,reason:'T₁=T₂=x。第 3 阶才加入 −x³/6。“n 阶 Taylor 多项式”的次数可以小于 n。'},
 {id:'growth',question:'动画停在 T₂+0.4c₃(x−a)³，这条曲线应怎样理解？',options:['它已经是 T₃。','前 0、1、2 阶匹配；第 3 阶一般只完成了修正的 40%。','所有导数都只匹配 40%。'],correct:1,reason:'新项的低阶导数在 a 全为零。过渡曲线不是完整的 T₃，不能直接套用 T₃ 的余项界。'},
 {id:'bound',question:'用 M|x−a|ⁿ⁺¹/(n+1)! 控制误差时，M 必须来自哪里？',options:['只取展开点 a 处的第 n+1 阶导数。','整个连接区间上 |f⁽ⁿ⁺¹⁾| 的一个上界，且不能跨越奇点。','在图上取 20 个点的最大值即可严格保证。'],correct:1,reason:'Taylor 余项里的 ξ 是未知的，可能在连接区间任意位置。解析上界不能被有限采样最大值替代。'},
 {id:'radius',question:'ln(1+x) 在 a=0 展开，x=1 是否收敛到原函数？',options:['不收敛，因为端点都必须排除。','收敛；交错调和级数趋于 ln 2，端点应单独检查。','函数有定义的 x 都收敛。'],correct:1,reason:'开半径内必收敛；右端点由交错级数单独判断。x>1 虽有定义，级数项却不趋零。'},
 {id:'higher',question:'固定 x、固定 a，从 Tₙ 升到 Tₙ₊₁，哪句话普遍正确？',options:['绝对误差必然严格减小。','多匹配了一阶局部导数，但这个 x 的误差未必减小。','保证误差在所有 x 处都减半。'],correct:1,reason:'eˣ 在 a=0,x=−2 时，T₁ 比 T₀ 误差更大；sin x 在原点还会出现零项。逐阶匹配与误差单调下降不是一回事。'},
 {id:'flat',question:'g(x)=e⁻¹⁄ˣ²（原点补 0）的原点 Taylor 级数，哪句正确？',options:['收敛半径是 0。','级数处处收敛到 0，但只在原点等于 g；每个有限阶仍是有效局部逼近。','不符合 Taylor 定理。'],correct:1,reason:'全体系数为零，零级数半径为 ∞。固定 n 让 x→0，与固定 x≠0 让 n→∞，结论可以不同。'},
 {id:'rounding',question:'图中 |f(x)−T₁₂(x)| 显示“接近浮点分辨率”，可以断言函数与多项式恒等吗？',options:['可以，误差读数已经是零。','不可以；需要解析恒等式或严格误差论证，不能用舍入结果证明。','再多采样几个点就能证明恒等。'],correct:1,reason:'有限精度和绘图下限会掩盖非零余项。代码明确分开解析恒等式、浮点差与无限过程证明。'}
].map((q,i)=>{const target=[1,0,2,1,0,2,1,0][i],options=[...q.options];[options[q.correct],options[target]]=[options[target],options[q.correct]];return {...q,options,correct:target};});
function journey(s){const names=[['grow','逐层生长'],['error','检查误差'],['boundary','试探边界'],['proof','为什么成立'],['challenge','自己判断']];return `<nav class="ty-journey" aria-label="Taylor 学习路径">${names.map(([id,t],i)=>`<button data-ty-screen="${id}"${s.screen===id?' aria-current="step"':''}><span>0${i+1}</span><strong>${t}</strong><i>${i===4?'✓':'→'}</i></button>`).join('')}</nav>`;}
function context(s){return `<div class="ty-context"><label for="ty-function"><span class="eyebrow">YOUR FUNCTION</span><select id="ty-function" aria-label="选择 Taylor 函数">${Object.values(taylorFunctions).map(o=>`<option value="${o.id}"${o.id===s.fn?' selected':''}>${o.label} · ${o.name}</option>`).join('')}</select></label><p id="ty-function-note">${tf(s.fn).note}</p><span class="ty-domain" id="ty-domain">${tf(s.fn).domain}</span></div>`;}
function slider(id,label,min,max,step,value,desc=''){return `<div class="slider-block"><label class="control-label" for="${id}"><span>${label}</span><output id="${id}-value">${value}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><div class="slider-endpoints"><span>${min}</span><span>${desc}</span><span>${max}</span></div></div>`;}
function controls(s){return `<aside class="card ty-controls"><span class="eyebrow">CHANGE ONE THING AT A TIME</span><h2>从这里，控制生长。</h2>${slider('ty-a','展开点 a',...tf(s.fn).range,.01,s.a,'拖动绿色 a 也可移动')}<p class="ty-small" id="ty-a-note">${s.fn==='flat'?'此反例只在原点展开，a 固定为 0。':'移动 a 时保持相对位移 h；观察点 x 随之移动。'}</p>${slider('ty-n','目标阶数 n',0,TAYLOR_MAX,1,s.n,'动画生长到此阶')}${slider('ty-h','观察位移 h = x − a',-s.span,s.span,.01,s.h,'橙色 x 可以直接拖动')}<div class="ty-probe-position" id="ty-probe-position"></div><div class="divider"></div>${slider('ty-span','窗口半宽',.25,5,.05,s.span,'缩小窗口，看清局部')}<label class="ty-check"><input type="checkbox" id="ty-ghost"${s.ghost?' checked':''}> 保留上一阶虚线</label><details class="ty-options"><summary>误差阈值与导出</summary>${slider('ty-epsilon','容许误差 ε = 10⁻ᵉ',1,8,1,s.epsilon,'只用绝对误差')}<button class="button full-width" data-ty-action="export">${icon('download')} 导出逐阶数值 CSV</button></details><p class="ty-small">预设函数使用解析导数；没有数值差分。图线只负责显示，不负责证明。</p></aside>`;}
function plotCard(s){return `<section class="card ty-plot-card"><div class="ty-card-head"><div><span class="eyebrow">ONE POINT → A LOCAL MODEL</span><h2 id="ty-plot-title">不是拟合散点，而是匹配局部信息。</h2></div><div class="ty-legend"><span><i></i> 原函数 f</span><span><i class="orange"></i> <b id="ty-curve-name">Tₙ</b></span></div></div><div id="ty-main-plot"></div><div class="ty-chart-note"><span>拖动 a / x · 方向键微调</span><span>纵轴只依据 f 定标；越界部分会裁切</span></div><div class="ty-animation"><button class="button primary" data-ty-action="play" aria-pressed="false">${icon('play')} 从 0 逐层生长</button><button class="button" data-ty-action="back" aria-label="回到上一完整阶">−</button><button class="button" data-ty-action="next" aria-label="加入下一完整阶">＋</button><span id="ty-animation-status" role="status" aria-live="polite"></span></div><div id="ty-layer-rail" class="ty-layer-rail" aria-label="选择生长层数"></div><div class="ty-progress-control">${slider('ty-progress','逐层生长进度',0,s.n,.01,s.p,'可暂停在一项的中途')}</div></section>`;}
function termPanel(){return `<section class="card ty-term-card"><div><span class="eyebrow">WHAT DID THIS LAYER ADD?</span><h2>新增一项，修正一层信息。</h2><div id="ty-current-term"></div><button class="text-button" data-ty-proof="coefficients">为什么不会破坏前面几阶？ →</button></div><div id="ty-term-contribution"></div></section>`;}
function matching(){return `<section class="card ty-matching"><div class="ty-card-head"><div><span class="eyebrow">SAME POINT, SAME DERIVATIVES</span><h2>在 a 处，逐行核对。</h2></div><span class="ty-small">绿色：由构造保证 · 浅色：尚未要求</span></div><div class="ty-scroll" id="ty-jet-table"></div><div id="ty-curvature" class="ty-curvature"></div><details class="ty-options"><summary>展开全部系数与多项式</summary>${tyFormula}<div id="ty-polynomial-text" class="ty-equation"></div><div id="ty-coefficients" class="ty-scroll"></div><p class="ty-small">表中系数是解析公式的浮点显示，省略的小数位不是重新拟合后的系数。</p></details></section>`;}
function readout(){return `<div class="ty-live" id="ty-live" aria-label="观察点的函数值、多项式值和余项"></div><div class="ty-observation" id="ty-observation"></div>`;}
function errorPanels(){return `<div class="ty-error-grid"><section class="card ty-error-card"><span class="eyebrow">FIX ORDER · MOVE AWAY</span><h2>固定阶数，离 a 越来越远。</h2><p>移动观察点，看同一条近似在哪些地方可靠。</p><div id="ty-error-plot"></div></section><section class="card ty-error-card"><span class="eyebrow">FIX POINT · ADD ORDERS</span><h2>固定 x，多加几阶就够了吗？</h2><p>点击某一阶返回它；完整 T₀ 到 T₁₂ 独立计算。</p><div id="ty-order-plot"></div></section></div><p class="ty-small ty-axis-note">两个误差图的纵轴均为 log₁₀；底部 10⁻¹⁴ 是显示下限，落在底部不表示精确为零。未定义点断开，不补零。</p><section class="card ty-bound-card"><div><span class="eyebrow">A BOUND IS NOT A SAMPLE</span><h2>图上看着近，还能给出怎样的保证？</h2><div id="ty-bound"></div></div><div id="ty-tolerance"></div><button class="text-button" data-ty-proof="remainder">检查余项定理的条件与证明 →</button></section>`;}
function boundaryPanels(s){return `<section class="card ty-boundary"><div class="ty-card-head"><div><span class="eyebrow">WHERE THE INTUITION BREAKS</span><h2>近似、收敛、相等，不是同一句话。</h2></div></div><div class="ty-scenarios">${['nonmonotone','outside','edge','flat'].map(id=>`<button class="button" data-ty-scenario="${id}">${taylorScenarios[id].label} ↗</button>`).join('')}</div><div id="ty-support"></div><div id="ty-convergence"></div><div class="ty-two-limits"><div><small>固定阶数 n，靠近展开点</small><strong>x → a</strong><p>问：局部余项是不是比指定的幂更小？</p></div><span>≠</span><div><small>固定观察点 x，增加阶数</small><strong>n → ∞</strong><p>问：多项式的极限是不是原函数？</p></div></div><button class="text-button" data-ty-proof="convergence">半径与端点怎样得出？ →</button><button class="text-button" data-ty-proof="flat">所有导数都为零，为什么函数还能非零？ →</button></section>`;}
function proofPage(s){const p=tyProofs[s.proof];return `<div class="ty-proof-layout"><aside class="card ty-proof-nav"><span class="eyebrow">FOLLOW THE ARGUMENT</span><h2>把动画，变成推导。</h2>${Object.entries(tyProofs).map(([id,o])=>`<button data-ty-proof="${id}"${id===s.proof?' aria-current="page"':''}>${o.title}</button>`).join('')}<div class="divider"></div><button class="button full-width" data-ty-screen="grow">带着当前参数回实验 →</button><p class="ty-small">函数、展开点、阶数、观察点与动画进度均保留。证明讨论一般命题，不以当前一个正例作证。</p></aside><article class="card ty-proof-article"><span class="eyebrow">DEFINITION → CONSTRUCTION → PROOF</span><h2>${p.title}</h2><div class="ty-proof-given">${p.given}</div><nav class="ty-proof-steps" aria-label="证明步骤">${p.steps.map((_,i)=>`<button data-ty-step="${i}"${s.step===i?' aria-current="step"':''}>0${i+1}</button>`).join('')}</nav><div id="ty-proof-current"></div><div class="ty-proof-buttons"><button class="button" data-ty-action="proof-prev">← 上一步</button><button class="button" data-ty-action="proof-next">下一步 →</button></div><div class="ty-proof-warning">${p.warning}</div><details class="ty-proof-full"><summary>展开这条论证的完整四步</summary>${p.steps.map((step,i)=>`<section><h3>${i+1}. ${step[0]}</h3><p>${tyEscape(step[1])}</p><div class="ty-equation">${tyEscape(step[2])}</div></section>`).join('')}</details><div class="ty-source-note">定理参考：<a href="https://openstax.org/books/calculus-volume-2/pages/6-3-taylor-and-maclaurin-series" target="_blank" rel="noopener noreferrer">OpenStax · Taylor and Maclaurin Series ↗</a>。页面推导独立编排，离线时无需访问链接。</div></article></div>`;}
function quizPage(){return `<section class="card ty-quiz-card"><span class="eyebrow">TRANSFER, NOT RECALL</span><h2>先说判断，再检查自己的理由。</h2><p>不必背下五个展开式。更重要的是：知道每一阶保证了什么，以及它没有保证什么。</p><form id="ty-quiz">${tyQuestions.map((q,i)=>`<fieldset><legend><span>0${i+1}</span>${q.question}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="ty-${q.id}" value="${j}" required><span>${tyEscape(o)}</span></label>`).join('')}<div id="ty-feedback-${q.id}" class="ty-feedback" hidden></div></fieldset>`).join('')}<button class="button primary" type="submit">检查判断与理由 →</button><button class="button" type="button" data-ty-action="quiz-reset">重新判断</button><div id="ty-quiz-score" role="status" aria-live="polite"></div></form><button class="text-button" data-ty-screen="grow">回到实验，重新检验自己的直觉 →</button></section>`;}
export function taylorPage(s){const subtitles={grow:'一阶一阶加入，不是越画越像，而是一层一层匹配。',error:'不要只问画得像不像：固定阶数与固定观察点，分别做一次实验。',boundary:'函数有定义、级数收敛、和等于函数，需要分别判断。',proof:'动画给出线索；系数、余项与收敛，都有各自的论证。',challenge:'把你的理解迁移到新问题，而不是只记住一张漂亮的曲线。'};const head=`<section class="page-heading ty-heading"><div><div class="breadcrumb">实验室 <span>/</span> 一元局部分析 <span>/</span> Taylor 展开</div><span class="eyebrow">EXPERIMENT 05 <span>—</span> A CURVE, ONE DERIVATIVE AT A TIME</span><h1 id="ty-title" tabindex="-1">从一个点，长出一条曲线。</h1><p class="page-subtitle">${subtitles[s.screen]}</p></div><div class="heading-actions"><button class="button subtle" data-ty-action="reset">${icon('reset')} 重置</button><button class="button subtle" data-action="share">${icon('share')} 分享实验</button></div></section>${pageGuide('taylor',{screen:s.screen})}${journey(s)}${context(s)}`;
 if(s.screen==='proof')return head+proofPage(s);if(s.screen==='challenge')return head+quizPage();
 return head+`${s.screen==='boundary'?boundaryPanels(s):''}<div class="ty-workbench">${plotCard(s)}${controls(s)}</div>${readout()}${s.screen==='grow'?termPanel()+matching():errorPanels()}<div class="ty-next"><div><strong>${s.screen==='grow'?'局部信息匹配了，误差就一定变小吗？':s.screen==='error'?'阶数无限增加，就一定回到原函数吗？':'现在，轮到你判断。'}</strong><p>${s.screen==='grow'?'保持同一个函数与观察点，继续检查余项。':'保留当前参数，沿这条学习路径继续。'}</p></div><button class="button primary" data-ty-screen="${s.screen==='grow'?'error':s.screen==='error'?'boundary':'challenge'}">${s.screen==='grow'?'看误差 →':s.screen==='error'?'试探边界 →':'自己判断 →'}</button></div>`;
}
