import { uniformDefaults, applyUniformScenario } from './uniform-state.js';
import { ufFamilies, ufNodes, ufNodeNames, ufDomain, ufPartial, ufLimit, ufError, ufNorm, ufProbe, ufTruth, ufReasons, ufMajorant, ufIntegral, ufDerivative, ufLimitDerivative, ufDerivativeBound, ufCertificate, ufCSV, ufNum, ufEscape } from './uniform-math.js';
import { ufEdges, ufNodeInfo, ufQuestions, ufEquation } from './uniform-content.js';
import { ufGraphSVG, ufMobileGraph, ufMainSVG, ufErrorSVG, ufHistorySVG, ufDerivativeSVG, ufBudgetSVG, ufMiniSVG, ufXWindow, ufGeometry } from './uniform-plots.js';
const memory={answers:{},graded:false};
export function mountUniformLab(root,getState,changed,toast){const ac=new AbortController(),opts={signal:ac.signal};let playing=false,frame=null,last=0,drag=false;
const $=id=>root.querySelector('#'+id),html=(id,v)=>{const e=$(id);if(e)e.innerHTML=v;},text=(id,v)=>{const e=$(id);if(e)e.textContent=v;};
function stop(){playing=false;if(frame!==null)cancelAnimationFrame(frame);frame=null;last=0;const b=root.querySelector('[data-uf-action="play"]');if(b){b.textContent='▶ 增加部分和';b.setAttribute('aria-pressed','false');}}
function rebuild(){stop();changed(true);root.querySelector('#uf-title')?.focus({preventScroll:true});window.scrollTo(0,0);}
function slider(id,value,display=value){const el=$(id);if(!el)return;el.value=value;el.style.setProperty('--fill',`${100*(value-Number(el.min))/(Number(el.max)-Number(el.min)||1)}%`);el.setAttribute('aria-valuetext',String(display));text(id+'-value',display);}
function grade(){let score=0;for(const q of ufQuestions){const v=memory.answers['uf-'+q.id],good=v!==undefined&&Number(v)===q.correct;score+=Number(good);const el=$('uf-feedback-'+q.id);el.hidden=false;el.classList.toggle('correct',good);el.textContent=(v===undefined?'尚未作答。':good?'✓ 判断正确。':'再检查量词与条件。')+' '+q.reason;}text('uf-quiz-score',`${score} / ${ufQuestions.length} 正确。请核对解释，而不仅是答案。`);}
function witness(s){const e=ufEdges[s.edge],t=ufTruth(s),a=t[e.from],b=t[e.to];let msg;
if(s.edge==='missing-anchor')msg=s.family==='drift'?'本例反驳的是“删去锚点”的弱化版本。联合前提未满足，不是绿色定理的反例。':'请用“常数漂移”专门检查锚点条件；不能把联合前提偷换成仅导数收敛。';
else if(e.type==='theorem'){let extra=true;if(s.edge==='uniform-integral')extra=ufDomain(s).compact;if(a===true&&extra)msg='当前满足这条定理的前提。全域结论来自证明，不是图中的有限点。';else msg='当前未满足这条箭头的全部前提。定理没有失效；只是此处不能靠它下结论。';}
else if(a===true&&b===false)msg='当前构成反例：左侧成立，右侧不成立。';else if(a===true&&b===true)msg='两侧同时成立：这是相容正例，不是逆推的证明。';else msg='当前尚未构成这条关系的反例。需要左侧成立、右侧不成立；试试上方对照案例。';
return `<span>${ufNodeNames[e.from]} ${a===true?'✓':a===false?'×':'—'}</span><b>${e.type==='theorem'?'→':'⇏'}</b><span>${ufNodeNames[e.to]} ${b===true?'✓':b===false?'×':'—'}</span><p>${msg}</p>`;}
function certificate(s){const x=ufProbe(s),single=ufCertificate(s,x),whole=ufCertificate(s),norm=ufNorm(s);const card=(label,c)=>`<div><span class="eyebrow">${label}</span><h3>${c.N===null?'找不到这样的 N':c.N===Infinity?'所需 N 超出可安全显示的整数范围':`N ≥ ${ufNum(c.N)}`}</h3><p>${ufEscape(c.formula||c.reason)}</p><small>${ufEscape(c.reason)}</small></div>`;
const current=norm.value===null?'本域上没有有限极限 S，整体误差 E_N 未定义。':norm.value<s.eps?'当前阶的全域误差已经小于 ε。能否控制全部后续项，仍使用下面的解析尾界。':'当前阶不能让所有点同时进入 ε 带；全域判断用解析上确界，不看有限网格最大值。';
html('uf-certificate',`<div class="uf-certificate-top"><span class="eyebrow">TAIL CERTIFICATE · ALL m ≥ N</span><p>${current}</p></div><div class="uf-certificate-grid">${card(`先固定当前 x=${ufNum(x)}`,single)}${card('先选 N，之后允许任意 x',whole)}</div><p class="uf-small">${s.track==='follow'?'探针每一步都换了 x；左侧的 N(x,ε) 只对当下冻结的这个 x 有效，不能把这条移动轨迹当成逐点序列。':'左侧固定点，右侧整个 E。两种证书都控制全部后续项，而不是只计算当前 N。'}${whole.N>512?' 统一证书超过动画上限 512；显示上限不改变数学结论。':''}</p>`);}
function update(){const s=getState(),d=ufDomain(s),norm=ufNorm(s);text('uf-formula',ufFamilies[s.family].formula);text('uf-series-type',`${ufFamilies[s.family].kind} · ${ufFamilies[s.family].series}`);slider('uf-r',s.r,ufNum(s.r));if(!ufFamilies[s.family].domains&&$('uf-domain'))$('uf-domain').value='closed';
if(s.screen==='proof'){const e=ufEdges[s.edge],v=e.steps[s.step];html('uf-proof-current',`<span class="eyebrow">STEP 0${s.step+1} / 04</span><h3>${v.title}</h3><p>${ufEscape(v.text)}</p>${ufEquation(v.formula)}`);root.querySelectorAll('[data-uf-step]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.ufStep)===s.step?'step':'false'));root.querySelector('[data-uf-action="proof-prev"]').disabled=s.step===0;root.querySelector('[data-uf-action="proof-next"]').disabled=s.step===3;return;}
if(s.screen==='challenge'){for(const [name,value]of Object.entries(memory.answers)){const r=root.querySelector(`input[name="${name}"][value="${value}"]`);if(r)r.checked=true;}if(memory.graded)grade();return;}
if(s.screen==='map'){html('uf-graph',ufGraphSVG(s)+ufMobileGraph(s));html('uf-mini',ufMiniSVG(s));html('uf-map-norm',`<small>解析上确界，不是采样最大值</small><strong>${ufEscape(norm.formula)}</strong><p>${ufEscape(norm.note)}</p>`);const ni=ufNodeInfo[s.node];html('uf-node-info',`<h3>${ufNodeNames[s.node]}</h3><p>${ni.text}</p><p class="uf-small">${ufReasons(s)[s.node]}</p><button class="text-button" data-uf-edge="${ni.route}">沿这条关系探索 →</button>`);return;}
html('uf-witness',witness(s));slider('uf-N',s.N,String(s.N));slider('uf-eps',s.eps,ufNum(s.eps));if($('uf-x')){$('uf-x').max=d.mode==='open'?1-1e-9:d.end;$('uf-x').disabled=s.track==='follow';slider('uf-x',s.track==='follow'?ufProbe(s):Math.min(s.x*d.end,Number($('uf-x').max)),ufNum(ufProbe(s)));}
root.querySelectorAll('[data-uf-track]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.ufTrack===s.track?'true':'false'));text('uf-track-note',s.track==='fixed'?'先固定一个 x，让 N 增长。观察这个数值序列能否最终进入误差带。':'N 每增长一步，就重新选择一个点：有最大值时追踪最大误差，否则展示解析坏点。');
text('uf-plot-title',s.view==='integral'?'高度可以换位置，面积不会自动消失。':s.view==='derivative'?'曲线越来越矮，斜率可能毫不退让。':s.view==='majorant'?'先替每一项做一个全域预算。':s.track==='follow'?'你给 N，我再找一个没有等到的点。':'先让这个点收敛，再问其他点。');
html('uf-main-plot',ufMainSVG(s));text('uf-plot-note',`橙线 S_N，绿虚线 S，绿色误差带 S±ε。所有图形为有限采样；边界与极值额外按公式取点。${s.family==='wave'?'高频波形每周期至少约 12 个采样点，不把采样与证明混同。':''} 浮点显示可能把极小非零值舍为0，不表示解析误差精确等于0。`);
const x=ufProbe(s),err=ufError(s,s.N,x);html('uf-live',[[s.track==='follow'?'移动点 x_N':'固定点 x',ufNum(x)],['S_N(x)',ufNum(ufPartial(s,s.N,x))],['点上误差 |S_N−S|',ufNum(err)],['全域 E_N · 解析式',ufNum(norm.value)]].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join(''));
let secondary='';if(s.view==='integral'){const i=ufIntegral(s);secondary=`<div class="uf-analytic"><span class="eyebrow">AREA LEDGER · INDEPENDENT FORMULAS</span><div class="uf-two-readings"><div><small>∫_E S_N</small><strong>${ufNum(i.partial)}</strong></div><div><small>∫_E S</small><strong>${ufNum(i.limit)}</strong></div></div><p>${ufEscape(i.reason)}</p>${i.bound!==null&&i.bound!==undefined?ufEquation(`面积差 ≤ |E|·E_N ≈ ${ufNum(i.bound)}`):''}<p class="uf-small">积分数值由原函数／几何公式计算，不由填色像素或求积采样计算。</p></div>`;}
else if(s.view==='derivative'){const b=ufDerivativeBound(s);secondary=ufDerivativeSVG(s)+`<div class="uf-analytic"><div class="uf-two-readings"><div><small>当前 x 处 S_N′</small><strong>${ufNum(ufDerivative(s,s.N,x))}</strong></div><div><small>当前 x 处 S′</small><strong>${ufNum(ufLimitDerivative(s,x))}</strong></div></div>${ufEquation(b.formula)}<p>${ufEscape(ufReasons(s).derivativeHyp)}</p><p class="uf-small">边界仅作单侧读数；定理保证的逐项求导结论在区间内部。波纹反例用内点 1/2。</p></div>`;}
else if(s.view==='majorant'){const m=ufMajorant(s);secondary=ufBudgetSVG(s)+`<div class="uf-analytic"><span class="eyebrow">${m.valid?'SUMMABLE BUDGET':'WHY THIS IS NOT NORMAL'}</span><h3>${m.title}</h3>${ufEquation(m.formula)}<p>${ufEscape(m.note)}</p>${m.tail!==undefined?`<p>当前 M 尾和约 ${ufNum(m.tail)}；实际 E_N 约 ${ufNum(norm.value)}。上界与实际误差分开。</p>`:''}</div>`;}
else secondary=ufErrorSVG(s)+`<div class="uf-analytic"><span class="eyebrow">EXACT EXPRESSION · NOT A GRID MAXIMUM</span>${ufEquation(norm.formula)}<p>${ufEscape(norm.note)}</p><small>${norm.attained?'此处可以取到最大误差。':'没有最大点或没有有限上确界，不妨碍作出上确界／不收敛的解析判断。'}</small></div>`;
html('uf-secondary',secondary);certificate(s);html('uf-history',ufHistorySVG(s));const truths=ufTruth(s),reasons=ufReasons(s);html('uf-statuses',ufNodes.map(id=>`<button class="uf-status-row" data-uf-node="${id}"><strong>${ufNodeNames[id]}</strong><span class="uf-status ${truths[id]===true?'yes':truths[id]===false?'no':'na'}">${truths[id]===true?'✓ 本例成立':truths[id]===false?'× 本例不成立':'— 不适用'}</span><p>${ufEscape(reasons[id])}</p><i>↗</i></button>`).join(''));
}
function play(){if(playing){stop();changed(false);return;}const s=getState();if(s.N>=512)s.N=1;playing=true;last=0;const b=root.querySelector('[data-uf-action="play"]');b.textContent='Ⅱ 暂停';b.setAttribute('aria-pressed','true');const tick=now=>{if(!playing)return;if(!last)last=now;const delay=matchMedia('(prefers-reduced-motion: reduce)').matches?700:220;if(now-last>=delay){s.N=Math.min(512,s.N+1);last=now;update();changed(false);}if(s.N>=512){stop();toast('已到有限显示上限 512。无限过程由解析证明判断。');return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}
function route(id){if(!ufEdges[id])return;const s=getState(),e=ufEdges[id];Object.assign(s,{edge:id,node:e.from,step:0,screen:'workshop',view:e.view});rebuild();}
root.addEventListener('click',event=>{const b=event.target.closest('[data-uf-screen],[data-uf-node],[data-uf-edge],[data-uf-layer],[data-uf-scenario],[data-uf-view],[data-uf-track],[data-uf-step],[data-uf-action]');if(!b)return;event.preventDefault();const s=getState();
if(b.dataset.ufScreen){s.screen=b.dataset.ufScreen;rebuild();return;}if(b.dataset.ufNode){s.node=b.dataset.ufNode;s.edge=ufNodeInfo[s.node].route;s.view=ufEdges[s.edge].view;s.step=0;s.screen='workshop';rebuild();return;}if(b.dataset.ufEdge){route(b.dataset.ufEdge);return;}if(b.dataset.ufLayer){s.layer=b.dataset.ufLayer;update();changed(false);root.querySelector(`[data-uf-layer="${s.layer}"]`)?.focus();root.querySelectorAll('[data-uf-layer]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.ufLayer===s.layer?'true':'false'));return;}
if(b.dataset.ufScenario){applyUniformScenario(s,b.dataset.ufScenario);s.screen='workshop';rebuild();return;}if(b.dataset.ufView){s.view=b.dataset.ufView;rebuild();return;}if(b.dataset.ufTrack){stop();s.track=b.dataset.ufTrack;update();changed(false);return;}if(b.dataset.ufStep!==undefined){s.step=Number(b.dataset.ufStep);update();changed(false);return;}
switch(b.dataset.ufAction){case 'start':s.screen='workshop';s.edge='pointwise-not-uniform';s.view='quantifiers';rebuild();break;case 'play':play();break;case 'next':case 'previous':stop();s.N=Math.max(1,Math.min(512,s.N+(b.dataset.ufAction==='next'?1:-1)));update();changed(false);break;case 'reset':Object.assign(s,uniformDefaults());memory.answers={};memory.graded=false;rebuild();break;case 'proof-next':s.step=Math.min(3,s.step+1);update();changed(false);break;case 'proof-prev':s.step=Math.max(0,s.step-1);update();changed(false);break;case 'certificate':{stop();const c=ufCertificate(s);if(c.N===null){s.track='follow';toast('没有统一 N。改为追踪解析坏点；证据见下方，不靠网格搜索。');}else if(c.N<=512){s.N=c.N;toast('已跳到一个有解析保证的统一 N；保证覆盖所有点和所有后续项。');}else toast('所需证书 N 超出动画上限，数学上界已在下方保留。');update();changed(false);$('uf-certificate')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});break;}case 'quiz-reset':memory.answers={};memory.graded=false;rebuild();break;case 'export':{const blob=new Blob([ufCSV(s)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ma-uniform-${s.family}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出有限切片与解析上确界说明；开放端点不采样。');break;}}
},opts);
root.addEventListener('input',e=>{const s=getState(),el=e.target;if(!['uf-N','uf-eps','uf-x','uf-r'].includes(el.id))return;stop();const v=Number(el.value);if(el.id==='uf-N')s.N=Math.round(v);else if(el.id==='uf-eps')s.eps=v;else if(el.id==='uf-x'){s.x=v/ufDomain(s).end;s.track='fixed';}else s.r=v;update();changed(false);},opts);
root.addEventListener('change',e=>{const s=getState();if(e.target.id==='uf-family'){s.family=e.target.value;if(!ufFamilies[s.family].domains)s.domain='closed';if(s.family==='geometric')s.domain='restricted';s.zoom=false;rebuild();}else if(e.target.id==='uf-domain'){s.domain=e.target.value;s.zoom=false;rebuild();}else if(e.target.id==='uf-zoom'){s.zoom=e.target.checked;update();changed(false);}else if(e.target.id==='uf-route-select'){s.edge=e.target.value;s.node=ufEdges[s.edge].from;s.step=0;rebuild();}else if(e.target.matches('#uf-quiz input')){memory.answers[e.target.name]=e.target.value;memory.graded=false;root.querySelectorAll('.uf-feedback').forEach(el=>el.hidden=true);text('uf-quiz-score','答案已修改，请重新检查。');}},opts);
root.addEventListener('submit',e=>{if(e.target.id==='uf-quiz'){e.preventDefault();memory.graded=true;grade();}},opts);
root.addEventListener('keydown',e=>{const t=e.target.closest('g[role="button"]');if(t&&['Enter',' '].includes(e.key)){e.preventDefault();t.dispatchEvent(new MouseEvent('click',{bubbles:true}));return;}if(e.target.closest('[data-uf-probe]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();stop();const s=getState();s.track='fixed';s.x=e.key==='Home'?0:e.key==='End'?1:Math.min(1,Math.max(0,s.x+(e.key==='ArrowRight'?.01:-.01)));update();changed(false);root.querySelector('[data-uf-probe]')?.focus();}},opts);
function pointer(e){const svg=$('uf-main-svg');if(!svg)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),s=getState(),range=ufXWindow(s);const fraction=(point.x-ufGeometry.l)/(ufGeometry.w-ufGeometry.l-ufGeometry.r);const x=range[0]+Math.max(0,Math.min(1,fraction))*(range[1]-range[0]);s.x=x/ufDomain(s).end;s.track='fixed';update();changed(false);}
root.addEventListener('pointerdown',e=>{if(!e.target.closest('[data-uf-probe]'))return;e.preventDefault();stop();drag=true;root.setPointerCapture(e.pointerId);pointer(e);},opts);root.addEventListener('pointermove',e=>{if(drag)pointer(e);},opts);root.addEventListener('pointerup',e=>{if(drag){drag=false;if(root.hasPointerCapture(e.pointerId))root.releasePointerCapture(e.pointerId);}},opts);root.addEventListener('pointercancel',()=>drag=false,opts);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();},opts);update();return {destroy(){stop();ac.abort();}};
}

