import { ufFamilies, ufNodeNames, ufDomain, ufEscape } from './uniform-math.js';
import { ufScenarios } from './uniform-state.js';
import { pageGuide } from './page-guide.js';
export function ufEquation(t){return `<div class="uf-equation" role="math">${ufEscape(t)}</div>`;}
export const ufNodeInfo={
normal:{short:'∑ ||uₙ||∞ < ∞',route:'normal-uniform',text:'先给每一项一个不依赖 x 的上界，再把这些上界求和。这里的“正规”是固定 E 上的全局概念，不是只在每个紧子集上成立。'},
absolute:{short:'每个 x 的 ∑|uₙ(x)| < ∞',route:'absolute-not-uniform',text:'绝对值阻止符号抵消，但不同点可以使用不同的数值上界；它并没有交换 ∀x 与 ∃N。'},
uniform:{short:'一个 N，控制全部 x 与后续项',route:'uniform-pointwise',text:'先给误差 ε，再选 N；之后不管对方选哪个 x、哪个 m≥N，都不能逃出误差带。'},
pointwise:{short:'每个 x 可以有自己的 N',route:'pointwise-not-uniform',text:'先锁住 x，再等到足够靠后。换一个点，等待时间可以重新开始。'},
continuous:{short:'+ 每项连续',route:'uniform-continuous',text:'一致误差在所有位置都小，才能把某一条连续部分和当成极限曲线的共同中介。'},
integral:{short:'+ 闭区间、每项 Riemann 可积',route:'uniform-integral',text:'有限长度乘以统一高度误差，控制整个面积差。这个版本不覆盖广义积分或无界区间。'},
derivativeHyp:{short:'C¹ 项；导数列一致；锚点收敛',route:'derivative-rule',text:'控制的是导数列 S_N′，还必须固定一个点的函数值，才能恢复丢掉的加法常数。'},
derivative:{short:'S′ = lim S_N′（区间内部）',route:'uniform-not-derivative',text:'高度很小仍然可以剧烈摆动。一致收敛本身不控制斜率；逐项求导要单独检查。'}
};
const step=(title,text,formula)=>({title,text,formula});
export const ufEdges={
'normal-uniform':{from:'normal',to:'uniform',type:'theorem',title:'正规收敛 → 一致收敛',condition:'固定集合 E；实值项；存在 Mₙ≥sup_E|uₙ|，且 ∑Mₙ<∞。',question:'先把每项的最高点加起来，能替所有点统一安排一个 N 吗？',presets:['geoCompact','alternating','geoOpen'],view:'majorant',steps:[step('先做一个不依赖 x 的预算','Mₙ 不能在不同 x 下临时更换。正规性等价于存在可求和的统一 M 序列；若随意选的 M 不可求和，单凭这一点不能断言不正规。','|uₙ(x)| ≤ Mₙ（∀x∈E）；∑Mₙ < ∞'),step('先由完备性得到逐点的和','对固定 x，数值级数由比较判别绝对收敛。定义它的和为 S(x)，不把图上的极限猜测当成 S。','∑|uₙ(x)| ≤ ∑Mₙ < ∞'),step('给全部点同一条尾和界','三角不等式给出不依赖 x 的尾项界。把 N 取到数值尾和小于 ε 即可，同时控制每个 m≥N。','|S(x)−S_m(x)| ≤ ∑ₙ₌ₘ₊₁^∞ Mₙ ≤ ∑ₙ₌ᴺ₊₁^∞ Mₙ < ε'),step('读出量词顺序','这个 N 只依赖 ε，不依赖 x。Weierstrass M 判别是充分条件，不是所有一致收敛都需要绝对可求和的项范数。','∀ε>0 ∃N ∀x∈E ∀m≥N：|S_m(x)−S(x)|<ε')]},
'normal-absolute':{from:'normal',to:'absolute',type:'theorem',title:'正规收敛 → 逐点绝对收敛',condition:'与 M 判别相同的固定域和可求和上界。',question:'同一份预算，为什么也足够支付任意一个点的绝对值总和？',presets:['geoCompact','powerClosed'],view:'majorant',steps:[step('固定一个点','共同上界当然也能用于任何指定的 x。','|uₙ(x)|≤Mₙ'),step('先比较有限部分和','比较不依赖无限交换操作。','∑ₙ₌₁ᴺ |uₙ(x)| ≤ ∑ₙ₌₁ᴺ Mₙ'),step('用单调有界收敛','左侧非负项部分和递增且有界，因而收敛。','∑|uₙ(x)| ≤ ∑Mₙ < ∞'),step('注意反向的缺口','逐点的总预算可以随 x 改变；把求和与上确界交换通常会增大结果。','sup_x ∑ₙ |uₙ(x)| ≤ ∑ₙ sup_x |uₙ(x)|')]},
'uniform-pointwise':{from:'uniform',to:'pointwise',type:'theorem',title:'一致收敛 → 逐点收敛',condition:'同一个 E、同一个极限 S；一致收敛先于选 x。',question:'已经能保护所有点，还需要为一个点另找 N 吗？',presets:['powerCompact','powerClosed'],view:'quantifiers',steps:[step('一致收敛允许 x 最后出场','N 选择之后，所有点都被包含。','∀ε>0 ∃N ∀x∈E ∀m≥N：|S_m(x)−S(x)|<ε'),step('现在锁住任意 x₀','统一的 N 对这个点自然有效。','|S_m(x₀)−S(x₀)|<ε（m≥N）'),step('这就是数值序列收敛','固定点的数值列 S_m(x₀) 收敛到 S(x₀)。','∀x₀∈E：S_m(x₀)→S(x₀)'),step('逆向不能随便交换量词','每个点有各自等待时间，不等于存在所有等待时间的共同有限上界。','∀x ∃N(x,ε)  ⇏  ∃N(ε) ∀x')]},
'absolute-pointwise':{from:'absolute',to:'pointwise',type:'theorem',title:'逐点绝对收敛 → 逐点收敛',condition:'对每个固定 x，数值级数 ∑|uₙ(x)| 收敛。',question:'绝对值的尾部很小，原来带符号的尾部会更大吗？',presets:['powerClosed','alternating'],view:'majorant',steps:[step('固定 x 后回到数值级数','这里没有一致性信息。','∑|uₙ(x)|<∞'),step('用绝对值控制带符号的尾部','比较发生在同一个固定点。','|∑ₙ₌ₚ^q uₙ(x)| ≤ ∑ₙ₌ₚ^q |uₙ(x)|'),step('Cauchy 判据完成收敛','实数完备性保证 Cauchy 部分和有极限。','S_N(x)→S(x)'),step('所得 N 仍可能依赖 x','没有一个统一 M 序列，不能从这一步跨到一致收敛。','N=N(x,ε)，不一定是 N(ε)')]},
'uniform-continuous':{from:'uniform',to:'continuous',type:'theorem',title:'一致收敛 + 连续项 → 连续极限',condition:'每个 uₙ 在 E 上连续（相对拓扑）；S_N 在 E 上一致趋于 S。',question:'怎样用一条已经连续的 S_N，把极限曲线的两点连接起来？',presets:['powerCompact','powerClosed','powerOpen'],view:'quantifiers',steps:[step('先付出两份统一误差','给定 x₀ 和 ε，先取一个 N，让全域误差小于 ε/3。','||S_N−S||∞<ε/3'),step('把中间问题交给一条连续曲线','有限和 S_N 连续，因此可以再选 δ。','|x−x₀|<δ ⇒ |S_N(x)−S_N(x₀)|<ε/3'),step('搭三段桥','两端各用统一误差，中间用固定 S_N 的连续性。','|S(x)−S(x₀)| ≤ |S−S_N|(x)+|S_N(x)−S_N(x₀)|+|S_N−S|(x₀) < ε'),step('说明逐点为何不够','逐点时，为靠近 x₀ 的每个 x 可能需要重新选 N，不能先固定一条中间曲线。条件不满足只是不保证；极限仍可能连续。','一致 + 连续项 ⇒ 连续；逐点 + 连续项 ⇏ 连续')]},
'uniform-integral':{from:'uniform',to:'integral',type:'theorem',title:'一致收敛 + 可积项 → 逐项积分',condition:'E=[a,b] 有限闭区间；每个 uₙ Riemann 可积；S_N 一致收敛。',question:'把“所有位置的高度都小”换算成面积，代价是什么？',presets:['geoCompact','spike','powerClosed'],view:'integral',steps:[step('先保证极限可积','固定一条 S_N，设统一误差为 η。任意分割 P 的上下和差满足下面的不等式。先令 η 很小，再用 S_N 可积选择 P，得到 S 可积。','U(S,P)−L(S,P) ≤ U(S_N,P)−L(S_N,P)+2(b−a)η'),step('有限区间把高度误差换成面积误差','长度 b−a 有限，这正是不能直接推广到无界区间的地方。','|∫ₐᵇ S_N−∫ₐᵇ S| ≤ (b−a)||S_N−S||∞ → 0'),step('只在有限和内使用线性','有限和积分的交换不需要收敛假设。','∫ₐᵇ S_N = ∑ₙ₌₁ᴺ ∫ₐᵇ uₙ'),step('现在才取 N→∞','由前两步完成无穷交换。非一致时，本等式可能成立，也可能失败；请对照幂函数与移动尖峰。','∫ₐᵇ ∑ₙ₌₁^∞uₙ = ∑ₙ₌₁^∞∫ₐᵇuₙ')]},
'derivative-uniform':{from:'derivativeHyp',to:'uniform',type:'theorem',title:'导数一致 + 一点收敛 → 函数列一致',condition:'E=[a,b]；每个 S_N∈C¹；S_N′ 一致趋于 g；S_N(x₀) 收敛。',question:'控制斜率，再钉住一个点，能否控制整条曲线？',presets:['geoCompact','drift','wave'],view:'derivative',steps:[step('由微积分基本定理恢复高度','如果忘了锚点，就允许整条曲线不断上下平移。','S_N(x)=S_N(x₀)+∫ₓ₀ˣ S_N′(t)dt'),step('先构造候选极限','g 是连续函数列的一致极限，所以连续；c 是锚点处的有限极限。','S(x)=c+∫ₓ₀ˣg(t)dt；c=lim S_N(x₀)'),step('误差拆成高度与斜率两笔','右侧完全不依赖 x。','||S_N−S||∞ ≤ |S_N(x₀)−c|+(b−a)||S_N′−g||∞'),step('两个误差同时趋零','因此 S_N 一致收敛。例子 S_N=N 说明导数列一致本身不够。','锚点收敛 + 导数一致 ⇒ 高度一致')]},
'derivative-rule':{from:'derivativeHyp',to:'derivative',type:'theorem',title:'控制导数列，才能保证逐项求导',condition:'有限闭区间；C¹ 各项；导数部分和 S_N′ 一致收敛；一点 S_N(x₀) 收敛。导数结论在内部。',question:'为什么积分交换之后，才轮到求导交换？',presets:['geoCompact','wave','drift'],view:'derivative',steps:[step('先用另一条箭头恢复和函数','不能从原级数一致收敛反推出导数列一致。','S(x)=c+∫ₓ₀ˣ g(t)dt'),step('g 连续，才能使用基本定理','因为 S_N′ 连续并且一致收敛，g 连续。','S′(x)=g(x)（a<x<b）'),step('有限和的导数就是导数的部分和','求导的无穷交换由 g 的定义完成。','S_N′=∑ₙ₌₁ᴺ uₙ′；g=lim S_N′'),step('写出结论，也保留条件','几何级数在 [0,r] 上导数尾项也能统一控制；小波纹则是缺少该控制的反例。','(∑ₙ₌₁^∞uₙ)′=∑ₙ₌₁^∞uₙ′（区间内部）')]},
'pointwise-not-uniform':{from:'pointwise',to:'uniform',type:'question',title:'每个点都等得到 ⇏ 所有点一起等到',condition:'S_N=xᴺ，先在 [0,1] 上，再切到 [0,1) 或 [0,r]。',question:'你先报一个 N，我能不能再找出一个仍未合格的点？',presets:['powerClosed','powerOpen','powerCompact'],view:'quantifiers',steps:[step('固定点之后确实收敛','x<1 时 xᴺ→0；x=1 时恒为1。先选 x，N 可以跟着 x 改。','S(x)=0（x<1）；S(1)=1'),step('统一误差不是网格最大值','任意有限 N，令 x 从左侧趋近1，误差趋近1；但在端点误差又是0。','sup_[0,1]|S_N−S|=1（不取到）'),step('构造永远逃出的点','固定 ε₀=1/4。无论 N 多大都选 x_N=2^(−1/N)<1；这不是逐点收敛中的固定 x。','|S_N(x_N)−S(x_N)|=1/2>ε₀'),step('只改定义域就能修复','在 [0,r] 且 r<1 上，最高误差为 rᴺ→0。去掉端点得到 [0,1) 则仍然不一致。','∀r<1：sup_[0,r]|S_N|=rᴺ→0；sup_[0,1)|S_N|=1')]},
'pointwise-not-continuous':{from:'pointwise',to:'continuous',type:'question',title:'逐点收敛 + 连续项 ⇏ 连续极限',condition:'使用 [0,1] 上的 S_N=xᴺ，每条曲线均连续。',question:'所有曲线都没有断裂，最后的曲线为什么可能跳一下？',presets:['powerClosed','powerOpen','powerCompact'],view:'quantifiers',steps:[step('逐项都连续','每个 S_N 是多项式，对应的望远镜项也连续。','u₁=x；uₙ=xⁿ−xⁿ⁻¹'),step('先固定 x，再取极限','函数值的极限要逐点判断，端点不能自动接上左极限。','S(x)=0（0≤x<1）；S(1)=1'),step('再检查 S 的连续性','原先两种取极限的顺序产生了不同结果。','lim_{x→1⁻} S(x)=0 ≠ S(1)=1'),step('不把非一致误读成必然不连续','在 [0,1) 上极限恒为0并连续，却仍不一致。一致是保证连续性的一条充分路线。','非一致 ⇏ 极限不连续')]},
'pointwise-not-integral':{from:'pointwise',to:'integral',type:'question',title:'逐点趋零 ⇏ 面积趋零',condition:'[0,1] 上的连续三角尖峰；对应项由 S_N 望远镜拆分。',question:'每个点最终都回到零，整块面积是不是也应该消失？',presets:['spike','powerClosed','geoCompact'],view:'integral',steps:[step('宽度越来越窄，高度越来越高','S_N 在 [0,1/N] 上为三角形，峰顶位于 1/(2N)，高度2N。','S_N(x)=2N·max(1−|2Nx−1|,0)'),step('逐点收敛确实成立','固定 x>0，取 N>1/x 后所有后续尖峰都离开 x；x=0 处始终为0。','∀x：S_N(x)→0'),step('面积却一直不变','图中的填色只解释几何；等式由三角形面积精确推出。','∫₀¹S_N=(1/2)(1/N)(2N)=1；∫₀¹S=0'),step('翻译回逐项积分','u₁ 的积分为1，以后 uₙ 的积分为0；和函数恒0。这是实实在在的无穷交换失败。','∑∫uₙ=1 ≠ 0=∫∑uₙ')]},
'uniform-not-derivative':{from:'uniform',to:'derivative',type:'question',title:'高度一致趋零 ⇏ 可以逐项求导',condition:'[0,1] 上 S_N(x)=sin(2πNx)/(2πN)，每项 C∞。',question:'波纹越来越矮，为什么斜率仍然不停摆动？',presets:['wave','geoCompact'],view:'derivative',steps:[step('最高高度统一趋零','1/(2πN) 控制所有 x，所以 S_N 一致收敛到0。','||S_N||∞=1/(2πN)→0'),step('求导把频率乘了回来','小的幅度乘以大的频率，斜率仍可达到1。','S_N′(x)=cos(2πNx)'),step('在一个固定内点检查失败','使用 x=1/2，而不是把端点单侧导数偷换成内部结论。','S_N′(1/2)=(−1)ᴺ；S′(1/2)=0'),step('缺少的是导数一致，不是画得不够细','高度的一致误差没有导数的信息。正确充分条件是导数列一致，加一点函数值收敛。','||S_N′−0||∞=1（对每个 N）')]},
'uniform-not-normal':{from:'uniform',to:'normal',type:'question',title:'一致收敛 ⇏ 正规收敛',condition:'[0,1] 上 uₙ(x)=(−1)ⁿ⁻¹x/n。',question:'所有点能统一抵消尾部，是否就有可求和的绝对预算？',presets:['alternating','geoCompact'],view:'majorant',steps:[step('每个点都是交错调和的倍数','和函数 S=x ln2 连续。','S_N=xH_N^(alt)；S=x ln2'),step('尾项界独立于 x','可以对所有 x 共用一个 N。','|S_N(x)−S(x)|≤x/(N+1)≤1/(N+1)'),step('但项的最高绝对值不可求和','不只是某个粗糙 M 失败：最小统一上界本身就是1/n。','||uₙ||∞=1/n；∑||uₙ||∞=∞'),step('量词统一与绝对可加是不同要求','x>0 处也非绝对收敛。正规 ⇒ 一致且逐点绝对，反向需要另证，不能自动补齐。','一致收敛 ≠ 逐点绝对收敛 ≠ 正规收敛')]},
'absolute-not-uniform':{from:'absolute',to:'uniform',type:'question',title:'逐点绝对收敛 ⇏ 一致收敛',condition:'[0,1] 上用 xᴺ 的望远镜项，而不是将 xⁿ 误作几何级数的和。',question:'每个点的绝对总和有限，为什么仍然找不到统一的尾部？',presets:['powerClosed','powerCompact','spike'],view:'majorant',steps:[step('先明确讨论哪一个级数','从第二项起，xⁿ−xⁿ⁻¹≤0，因此其绝对值可以望远镜求和。','u₁=x；uₙ=xⁿ−xⁿ⁻¹'),step('每个点的绝对和有限','对 x<1，绝对和为2x；x=1 时除第一项外均为0。','∑|uₙ(x)|=2x（x<1）；=1（x=1）'),step('部分和仍然是 xᴺ','绝对性并没有改变之前的坏点构造。','sup_E|S_N−S|=1'),step('不要偷换两种“绝对”','逐点绝对仅对每点求和；正规要求先对每项取全域上确界，再求和。','∀x ∑|uₙ(x)|<∞  ⇏  ∑sup_x|uₙ(x)|<∞')]},
'continuous-not-uniform':{from:'continuous',to:'uniform',type:'question',title:'极限连续 ⇏ 一致收敛',condition:'先用 [0,1) 上的 xᴺ，再看 [0,1] 上的移动尖峰。',question:'不再出现跳跃，是否就证明了所有点同时趋近？',presets:['powerOpen','spike','powerCompact'],view:'quantifiers',steps:[step('去掉端点后极限连续','[0,1) 上 S≡0，无跳跃。','S_N=xᴺ→0（逐点）'),step('但是坏点仍能逼近1','没有最大误差点，不等于最高误差为0。','sup_[0,1)|S_N|=1'),step('闭区间也有反例','移动尖峰的极限同样恒0，而最高误差为2N。','[0,1]：S_N(x)→0；||S_N||∞=2N'),step('单调等额外条件可以改变结论','不能遗漏假设，例如 Dini 定理还需要紧致与关于 N 的单调性；本图不把这些未添加的条件自动补上。','极限连续是一种结论，不是一般的一致收敛判别')]},
'missing-anchor':{from:'derivativeHyp',to:'uniform',type:'question',title:'只留导数一致，删掉锚点会怎样？',condition:'这是“删除前提”问题，不是 derivativeHyp ⇒ uniform 这条定理的反例。',question:'所有曲线的斜率都是零，为什么整条曲线还可以跑掉？',presets:['drift','geoCompact'],view:'derivative',steps:[step('取越来越高的水平线','S_N(x)=N，每一条均 C∞。','S_N′(x)=0'),step('导数确实一致收敛','所有点的导数误差都为0。','S_N′→0（一致）'),step('锚点却没有有限极限','任何固定点处函数值均为N，所以函数列甚至不逐点收敛。','S_N(x₀)=N→+∞'),step('正确条件不能被误判为失败','当前未满足“导数一致 + 一点收敛”这个联合节点；失败的是删去锚点的弱化命题。','求导丢掉的加法常数，需要一个锚点恢复')]} 
};
export const ufQuestions=[
{id:'order',title:'一致收敛中，N 必须在什么时候选好？',options:['选好 x 后，再根据 x 选 N','给定 ε 后、任意 x 出场前选 N，并控制所有 m≥N','看完有限网格的最大误差后选 N'],correct:1,reason:'关键是 ∃N 在 ∀x 之前，而且还要覆盖所有后续项，不只当前这一项。'},
{id:'sup',title:'xᴺ 在 [0,1] 的误差上确界为什么是1？',options:['因为在 x=1 处误差恰为1','因为端点不重要，可以忽略它','从左侧接近1时误差趋近1；在1处误差为0，上确界不取到'],correct:2,reason:'逐点极限在1处也是1，故那里误差为0。sup 不一定是最大值；有限网格最大值也不等于 sup。'},
{id:'domain',title:'几何级数在 [0,1) 逐点收敛，可以用 Mₙ=rⁿ⁻¹ (r<1) 控制整个区间吗？',options:['可以，每个 x 都小于1','不可以；必须先把域固定为 [0,r] 才有这个共同上界','可以，只要 N 大于显示上限'],correct:1,reason:'不能让 r 随 x 改变却仍称其为共同 M 序列。这里每个固定 [0,r] 正规收敛，但整个 [0,1) 不一致。'},
{id:'normal',title:'∑(−1)ⁿ⁻¹x/n 在 [0,1] 上属于哪一种？',options:['一致收敛，但不正规，且不是逐点绝对收敛','正规收敛，因为可以用 Leibniz','仅在 x=0 收敛'],correct:0,reason:'统一尾项界是1/(N+1)，而 ∑||uₙ||∞=∑1/n 发散；x>0 的绝对值级数发散。'},
{id:'spike',title:'移动三角尖峰逐点趋零，但积分恒1。哪一步不能做？',options:['计算每个有限 S_N 的积分','把有限和的积分写成积分的有限和','没有额外保证就把无限求和与积分交换'],correct:2,reason:'有限线性始终有效；无限交换是极限问题。这里 ∑∫uₙ=1，而 ∫∑uₙ=0。'},
{id:'slope',title:'S_N=sin(2πNx)/(2πN) 一致趋零，为什么不能直接逐项求导？',options:['和函数0不可微','S_N 不是连续函数','导数 S_N′ 在内点1/2为(−1)ᴺ，不收敛到 S′=0'],correct:2,reason:'曲线高度一致很小不控制频率；求导乘回2πN。'},
{id:'anchor',title:'各项 C¹，导数列一致收敛，就一定有函数列一致收敛吗？',options:['是，因为导数决定函数','不一定，还需要某个点的函数值收敛','只有导数极限等于0才成立'],correct:1,reason:'S_N=N 的导数恒0，但函数值处处发散。定理中的一点收敛不能省掉。'},
{id:'necessary',title:'没有一致收敛，就一定不能交换积分或保持连续吗？',options:['是，这是定理的逆否命题','不是；不满足充分条件不等于结论失败，xᴺ 的积分仍能取极限','只要数值图看起来平滑就可以交换'],correct:1,reason:'xᴺ 在 [0,1] 不一致，但积分1/(N+1)→0=∫S；在 [0,1) 极限也连续。条件不足只意味着这条定理不给保证。'}
];
const screens=[['map','条件地图'],['workshop','同一个 N 挑战'],['proof','为什么能交换'],['challenge','自己判断']];
function header(s){return `<div class="breadcrumb">实验室 <span>/</span> 函数项级数 <span>/</span> 量词与交换</div><header class="lab-heading uf-heading"><div><div class="eyebrow">EXPERIMENT 07 &nbsp; — &nbsp; ONE N, EVERYWHERE</div><h1 id="uf-title" tabindex="-1">每个点，都等到。<br class="uf-mobile-break">还是一起等到？</h1><p>先锁住一个点，再追踪逃跑的点。用同一个误差要求，连接收敛与极限交换。</p></div><div class="heading-actions"><button class="button" data-uf-action="reset">↶ 重置</button><button class="button" data-action="share">↥ 分享实验</button></div></header><nav class="uf-journey" aria-label="一致收敛学习路径">${screens.map(([id,n],i)=>`<button data-uf-screen="${id}" ${s.screen===id?'aria-current="step"':''}><small>0${i+1}</small>${n}<span>→</span></button>`).join('')}</nav>`;}
function context(s){return `<section class="uf-context"><label for="uf-family"><small>同一个部分和，在不同条件下检验</small><select id="uf-family">${Object.entries(ufFamilies).map(([id,f])=>`<option value="${id}" ${s.family===id?'selected':''}>${f.name}</option>`).join('')}</select></label><div class="uf-context-formula"><strong id="uf-formula"></strong><small id="uf-series-type"></small></div><label for="uf-domain"><small>先固定讨论的集合 E</small><select id="uf-domain" ${!ufFamilies[s.family].domains?'disabled':''}><option value="closed" ${s.domain==='closed'?'selected':''}>[0, 1] · 包含端点</option><option value="open" ${s.domain==='open'?'selected':''}>[0, 1) · 接近但不取到</option><option value="restricted" ${s.domain==='restricted'?'selected':''}>[0, r] · 留出余地</option></select></label><div id="uf-r-control" ${s.domain!=='restricted'||!ufFamilies[s.family].domains?'hidden':''}><label for="uf-r">右端点 r <output id="uf-r-value"></output></label><input id="uf-r" type="range" min=".2" max=".98" step=".01" value="${s.r}"></div></section>`;}
function presets(s){return `<div class="uf-presets" aria-label="当前关系的正反例">${ufEdges[s.edge].presets.map(k=>`<button class="button" data-uf-scenario="${k}">${ufScenarios[k].label} ↗</button>`).join('')}</div>`;}
function map(s){return `<div class="uf-map-layout"><section class="card uf-map-card"><div class="uf-card-head"><div><span class="eyebrow">CONDITIONS BEFORE CONCLUSIONS</span><h2>同一个 N，是一条分界线。</h2></div><div class="uf-toggle"><button data-uf-layer="theorems" aria-pressed="${s.layer==='theorems'}">→ 定理路线</button><button data-uf-layer="questions" aria-pressed="${s.layer==='questions'}">⇏ 逆推挑战</button></div></div><p class="uf-small">节点标记当前例子是否满足性质；箭头表示一般定理。箭头上的附加条件不能省去。</p><div id="uf-graph"></div><div class="uf-legend"><span class="uf-green">━━ → 有条件的蕴含</span><span class="uf-orange">┄┄ ⇏ 反例／删去条件</span><span>✓ 成立　× 不成立　— 不适用</span></div></section><aside class="card uf-map-aside"><span class="eyebrow">A SINGLE SHARED DEADLINE</span><h2>ε 一样，<br>N 能共用吗？</h2><div id="uf-mini"></div><div id="uf-map-norm"></div><div id="uf-node-info"></div><button class="button primary full-width" data-uf-action="start">锁住一个点，开始实验 →</button><p class="uf-small">先把 S_N 看作函数列。下面的望远镜拆分，让函数列与函数项级数用同一套部分和语言对话。</p></aside></div><section class="uf-questions-grid" aria-label="寻找错误逆推">${Object.entries(ufEdges).filter(([,e])=>e.type==='question').map(([id,e])=>`<button data-uf-edge="${id}"><b>⇏</b><strong>${e.title}</strong><small>${id==='missing-anchor'?'删去一个前提':'反例在哪里'} ↗</small></button>`).join('')}</section><div class="uf-note"><strong>函数列不是“把它的每一项再加一次”。</strong><p>xᴺ 是本例的部分和 S_N；对应的项是 u₁=x、uₙ=xⁿ−xⁿ⁻¹。它不是几何级数 ∑xⁿ。切换到“几何级数”，S_N 才是 1+x+⋯+xᴺ⁻¹。</p></div>`;}
function controls(s){return `<aside class="card uf-controls"><span class="eyebrow">SAME ε · DIFFERENT RULES</span><h2>谁先出场？</h2><div class="uf-toggle uf-track"><button data-uf-track="fixed" aria-pressed="${s.track==='fixed'}">① 锁住 x</button><button data-uf-track="follow" aria-pressed="${s.track==='follow'}">② 追踪 x_N</button></div><p id="uf-track-note" class="uf-small"></p><label for="uf-N">部分和 N <output id="uf-N-value"></output></label><input type="range" id="uf-N" min="1" max="512" step="1" value="${s.N}"><div class="uf-play-row"><button class="button" data-uf-action="previous" aria-label="上一部分和">−1</button><button class="button primary" data-uf-action="play" aria-pressed="false">▶ 增加部分和</button><button class="button" data-uf-action="next" aria-label="下一部分和">+1</button></div><label for="uf-eps">允许误差 ε <output id="uf-eps-value"></output></label><input type="range" id="uf-eps" min=".01" max=".45" step=".01" value="${s.eps}"><label for="uf-x">固定点 x <output id="uf-x-value"></output></label><input type="range" id="uf-x" min="0" max="1" step=".001" value="${s.x}"><p class="uf-small">可以直接拖动图中的探针。开放端点不作为可选点；“追踪”时 x 随 N 改变，不是逐点极限的固定 x。</p><label class="uf-check"><input id="uf-zoom" type="checkbox" ${s.zoom?'checked':''}> 放大探针附近（不改变 E）</label><div class="uf-control-separator"></div><button class="button full-width" data-uf-action="certificate">找一个统一 N →</button><button class="text-button" data-uf-action="export">导出当前切片 CSV ↗</button></aside>`;}
function workshop(s){const e=ufEdges[s.edge];return `<section class="uf-route-intro"><div><span class="eyebrow">${e.type==='theorem'?'THEOREM ROUTE':'TEST THE CONVERSE'}</span><h2>${e.title}</h2><p>${e.question}</p></div><button class="button" data-uf-screen="proof">${e.type==='theorem'?'为什么成立':'为什么失败'} →</button><div id="uf-witness"></div></section>${presets(s)}<section class="uf-quantifiers" aria-label="比较量词的顺序"><div><span>逐点</span><strong>∀ε&gt;0　<b class="uf-qx">∀x∈E</b>　<b class="uf-qn">∃N(x,ε)</b>　∀m≥N</strong><small>先锁住点，再决定等多久。</small></div><div><span>一致</span><strong>∀ε&gt;0　<b class="uf-qn">∃N(ε)</b>　<b class="uf-qx">∀x∈E</b>　∀m≥N</strong><small>先报一个 N，再接受任何点的检查。</small></div><p>两行最后都要求 |S_m(x)−S(x)|&lt;ε。差别不是误差要求，而是 N 能不能依赖 x。</p></section><div class="uf-workbench"><section class="card uf-stage"><div class="uf-card-head"><div><span class="eyebrow">WATCH THE SAME PARTIAL SUM</span><h2 id="uf-plot-title"></h2></div><div class="uf-toggle uf-view-toggle">${[['quantifiers','高度与误差'],['integral','整体面积'],['derivative','局部斜率'],['majorant','M 的预算']].map(([v,t])=>`<button data-uf-view="${v}" aria-pressed="${s.view===v}">${t}</button>`).join('')}</div></div><div id="uf-main-plot"></div><p id="uf-plot-note" class="uf-plot-note"></p><div class="uf-live" id="uf-live"></div><div id="uf-secondary"></div></section>${controls(s)}</div><section id="uf-certificate" class="uf-certificate" aria-live="polite"></section><section class="card uf-history-card"><div class="uf-card-head"><div><span class="eyebrow">A POINT VS THE WHOLE DOMAIN</span><h2>同一个误差带，两种等待时间。</h2></div><span class="uf-small">当前项与所有后续项，分开检查</span></div><div id="uf-history"></div><p class="uf-plot-note">橙线是一个固定点的误差；绿色虚线是解析 E_m，不是对网格取最大值。若显示上界，会明确写出 ≤。有限曲线不代替 m→∞ 的论证。</p></section><section class="card uf-dashboard"><div class="uf-card-head"><div><span class="eyebrow">ANALYTIC CHECKLIST</span><h2>当前例子，究竟满足什么？</h2></div></div><div id="uf-statuses"></div></section><div class="uf-next"><div><strong>观察到了，还要问“为什么对全部点有效”。</strong><p>沿当前箭头，把误差带翻译成真正的量词和证明。</p></div><button class="button primary" data-uf-screen="proof">继续：拆开这条证明 →</button></div>`;}
function proof(s){const e=ufEdges[s.edge];return `<div class="uf-proof-layout"><aside class="card uf-proof-nav"><span class="eyebrow">ONE ARROW AT A TIME</span><h2>不要省掉条件。</h2><label for="uf-route-select">选择关系</label><select id="uf-route-select">${Object.entries(ufEdges).map(([id,v])=>`<option value="${id}" ${id===s.edge?'selected':''}>${v.title}</option>`).join('')}</select><p class="uf-small">当前函数、区间、N、ε 会保留。箭头是一般命题；某个例子满足结论，不等于证明了箭头。</p><button class="button full-width" data-uf-screen="workshop">← 带着条件回实验</button><button class="text-button" data-uf-screen="map">回到整张关系图 ↗</button></aside><article class="card uf-proof-article"><span class="eyebrow">${e.type==='theorem'?'SUFFICIENT CONDITION':'COUNTEREXAMPLE / BOUNDARY'}</span><h2>${e.title}</h2><div class="uf-proof-given"><strong>先读前提</strong><p>${e.condition}</p></div><nav class="uf-steps" aria-label="证明步骤">${e.steps.map((v,i)=>`<button data-uf-step="${i}" aria-label="步骤${i+1}：${v.title}" ${i===s.step?'aria-current="step"':''}>0${i+1}</button>`).join('')}</nav><div id="uf-proof-current"></div><div class="uf-proof-buttons"><button class="button" data-uf-action="proof-prev">← 上一步</button><button class="button primary" data-uf-action="proof-next">下一步 →</button></div><details class="uf-full-proof"><summary>展开完整论证与所有条件</summary>${e.steps.map((v,i)=>`<section><h3>${i+1}. ${v.title}</h3><p>${ufEscape(v.text)}</p>${ufEquation(v.formula)}</section>`).join('')}</details><div class="uf-warning">数值只用于观察。这里的上确界、尾部估计、收敛类别与反例来自解析公式；有限采样未找到坏点，不是证明。</div>${presets(s)}<p class="uf-sources">定义与定理核对：Jiří Lebl, Basic Analysis, §§6.1–6.2；Weierstrass M 判别。仓库 docs/UNIFORM-MATHEMATICS.md 包含独立推导、术语约定与来源。所有内容内置，不需要联网读取。</p></article></div>`;}
function challenge(){return `<section class="card uf-quiz-card"><span class="eyebrow">NOW YOU DECIDE</span><h2>先判断量词，再判断结论。</h2><p class="uf-small">可以带着问题返回实验；本页作答会保留。每题都有理由，不用背节点颜色。</p><form id="uf-quiz">${ufQuestions.map((q,i)=>`<fieldset><legend><span>0${i+1}</span>${q.title}</legend>${q.options.map((v,j)=>`<label><input type="radio" name="uf-${q.id}" value="${j}"><span>${v}</span></label>`).join('')}<p id="uf-feedback-${q.id}" class="uf-feedback" hidden></p></fieldset>`).join('')}<button class="button primary" type="submit">检查判断与理由 →</button><button class="button" type="button" data-uf-action="quiz-reset">重新作答</button><p id="uf-quiz-score" role="status"></p></form></section>`;}
export function uniformPage(s){return header(s)+pageGuide('uniform',{screen:s.screen})+context(s)+({map,workshop,proof,challenge}[s.screen])(s);}
