import { ufDomain, ufPartial, ufLimit, ufError, ufNorm, ufProbe, ufNum, ufEscape, ufTruth, ufNodeNames, ufDerivative, ufLimitDerivative, ufTerm, ufMajorant } from './uniform-math.js';
import { ufNodeInfo, ufEdges } from './uniform-content.js';
export const ufNodeBoxes={normal:[265,20,210,88],absolute:[15,190,210,82],uniform:[265,190,210,82],pointwise:[15,360,210,82],continuous:[265,360,210,82],integral:[515,360,210,82],derivativeHyp:[515,20,210,88],derivative:[515,190,210,82]};
export const ufGraphPaths={
 'normal-uniform':{d:'M370 108 L370 190',x:370,y:149},
 'normal-absolute':{d:'M265 64 H120 V190',x:120,y:142},
 'uniform-pointwise':{d:'M310 272 Q275 325 185 360',x:249,y:320},
 'absolute-pointwise':{d:'M120 272 V360',x:120,y:316},
 'uniform-continuous':{d:'M370 272 V360',x:370,y:316,label:'连续项'},
 'uniform-integral':{d:'M475 249 L490 300 H620 V360',x:620,y:319,label:'闭区间 · 可积项'},
 'derivative-uniform':{d:'M515 64 H495 V145 H438 V190',x:467,y:145},
 'derivative-rule':{d:'M620 108 V190',x:620,y:149}
};
export function ufGraphSVG(s){const truth=ufTruth(s);let lines='';for(const [id,p]of Object.entries(ufGraphPaths)){const e=ufEdges[id];lines+=`<g class="uf-graph-edge" role="button" tabindex="0" data-uf-edge="${id}" aria-label="${e.title}，${e.condition}"><title>${e.condition}</title><path class="uf-edge-hit" d="${p.d}"/><path class="uf-edge-line" d="${p.d}" marker-end="url(#uf-arrow)"/><circle cx="${p.x}" cy="${p.y}" r="13"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle">→</text>${p.label?`<text class="uf-edge-label" x="${p.x+18}" y="${p.y-13}" text-anchor="${p.x>500?'end':'start'}">${p.label}</text>`:''}</g>`;}
let question='';if(s.layer==='questions'){const e=ufEdges[s.edge].type==='question'?ufEdges[s.edge]:ufEdges['pointwise-not-uniform'];question=`<g class="uf-question-link" role="button" tabindex="0" data-uf-edge="${ufEdges[s.edge].type==='question'?s.edge:'pointwise-not-uniform'}" aria-label="${e.title}，查看反例"><rect x="15" y="476" width="710" height="57" rx="10"/><text x="36" y="511">⇏　${e.title}　↗</text></g>`;}
const nodes=Object.entries(ufNodeBoxes).map(([id,[x,y,w,h]])=>`<g role="button" tabindex="0" data-uf-node="${id}" class="uf-graph-node ${truth[id]===true?'holds':truth[id]===false?'fails':'na'} ${s.node===id?'selected':''}" aria-label="${ufNodeNames[id]}，${truth[id]===true?'当前成立':truth[id]===false?'当前不成立':'不适用'}，打开实验"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="10"/><text class="uf-node-tag" x="${x+14}" y="${y+19}">${id==='derivativeHyp'?'A DIFFERENT KIND OF CONTROL':id==='normal'?'SUFFICIENT BUDGET':'PROPERTY / CONDITION'}</text><text class="uf-node-name" x="${x+14}" y="${y+45}">${ufNodeNames[id]}</text><text class="uf-node-small" x="${x+14}" y="${y+66}">${ufNodeInfo[id].short}</text><text class="uf-node-state" x="${x+w-17}" y="${y+19}" text-anchor="end">${truth[id]===true?'✓':truth[id]===false?'×':'—'}</text></g>`).join('');return `<svg class="uf-graph-desktop" viewBox="0 0 740 ${s.layer==='questions'?548:467}" aria-label="函数项级数收敛条件有向关系图"><defs><marker id="uf-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7Z" fill="#739462"/></marker></defs>${lines}${nodes}${question}</svg>`;}
export function ufMobileGraph(s){const truth=ufTruth(s);const node=id=>`<button class="uf-mobile-node ${truth[id]===true?'holds':''}" data-uf-node="${id}"><strong>${ufNodeNames[id]}</strong><small>${ufNodeInfo[id].short}</small><span>${truth[id]===true?'✓':truth[id]===false?'×':'—'}</span></button>`;const arrow=id=>`<button class="uf-mobile-arrow" data-uf-edge="${id}">↓ <span>${ufEdges[id].type==='theorem'?'为什么成立':'反例在哪里'}${id==='uniform-continuous'?' · 连续项':id==='uniform-integral'?' · 闭区间可积项':''}</span></button>`;return `<div class="uf-graph-mobile"><section><h3>统一控制的主线</h3>${node('normal')}${arrow('normal-uniform')}${node('uniform')}${arrow('uniform-pointwise')}${node('pointwise')}</section><section><h3>不是同一种“绝对”</h3>${node('normal')}${arrow('normal-absolute')}${node('absolute')}${arrow('absolute-pointwise')}${node('pointwise')}</section><section><h3>额外条件，换取极限交换</h3>${node('uniform')}<div class="uf-mobile-branches"><div>${arrow('uniform-continuous')}${node('continuous')}</div><div>${arrow('uniform-integral')}${node('integral')}</div></div></section><section><h3>求导走另一条路线</h3>${node('derivativeHyp')}<div class="uf-mobile-branches"><div>${arrow('derivative-uniform')}${node('uniform')}</div><div>${arrow('derivative-rule')}${node('derivative')}</div></div></section></div>`;}
// Explicit chart geometry supports pointer mapping and avoids canvas-only controls.
export const ufGeometry={w:760,h:310,l:62,r:20,t:24,b:44};
export function ufXWindow(s){const d=ufDomain(s);if(!s.zoom)return [0,d.end];const p=ufProbe(s);let width=s.family==='spike'?Math.min(d.end,2.5/s.N):s.family==='wave'?Math.min(d.end,3/s.N):Math.min(d.end,Math.max(.02,3/s.N));let lo=Math.max(0,p-width/2),hi=Math.min(d.end,lo+width);lo=Math.max(0,hi-width);return [lo,hi];}
function setup(xrange,yrange,h=310){const {w,l,r,t,b}=ufGeometry;const ymax=yrange[1]===yrange[0]?yrange[0]+1:yrange[1];const X=x=>l+(x-xrange[0])/(xrange[1]-xrange[0])*(w-l-r);const Y=y=>t+(ymax-y)/(ymax-yrange[0])*(h-t-b);return {w,h,l,r,t,b,X,Y,xrange,yrange:[yrange[0],ymax]};}
function axes(c,xlabel='x',ylabel='值'){let grid='';for(let i=0;i<=4;i++){const v=c.yrange[0]+(c.yrange[1]-c.yrange[0])*i/4,y=c.Y(v);grid+=`<line x1="${c.l}" y1="${y}" x2="${c.w-c.r}" y2="${y}" stroke="#e8ecdf"/><text x="${c.l-10}" y="${y+4}" text-anchor="end">${ufNum(v)}</text>`;}for(let i=0;i<=4;i++){const x=c.xrange[0]+(c.xrange[1]-c.xrange[0])*i/4;grid+=`<text x="${c.X(x)}" y="${c.h-22}" text-anchor="middle">${ufNum(x)}</text>`;}return `<g class="uf-axes">${grid}<text x="${c.l}" y="14">${ylabel}</text><text x="${c.w-12}" y="${c.h-8}" text-anchor="end">${xlabel}</text></g>`;}
function path(c,points){let d='',active=false;for(const [x,y]of points){if(y===null||!Number.isFinite(y)){active=false;continue;}const yy=Math.max(-c.h,Math.min(c.h*2,c.Y(y)));d+=`${active?'L':'M'}${c.X(x).toFixed(2)},${yy.toFixed(2)} `;active=true;}return d;}
function stroke(c,points,color,extra=''){return `<path d="${path(c,points)}" fill="none" stroke="${color}" stroke-width="2.4" ${extra}/>`;}
function svg(c,inner,title,id='uf-chart'){return `<svg id="${id}" class="uf-plot" viewBox="0 0 ${c.w} ${c.h}" role="img" aria-label="${title}"><title>${title}</title><defs><clipPath id="${id}-clip"><rect x="${c.l}" y="${c.t}" width="${c.w-c.r-c.l}" height="${c.h-c.t-c.b}"/></clipPath></defs>${axes(c)}${inner}</svg>`;}
function xSamples(s,range,N=s.N){const d=ufDomain(s);const count=s.family==='wave'?Math.min(6200,Math.max(260,Math.ceil(12*N*(range[1]-range[0])))):300;const xs=Array.from({length:count+1},(_,i)=>range[0]+(range[1]-range[0])*i/count);xs.push(ufProbe(s));if(s.family==='spike')xs.push(0,1/(2*N),1/N);if(s.family==='power'||s.family==='geometric'){for(const v of [.0001,.001,.01,.05,.1,.25,.5,.75,.9,.99,.999])xs.push(Math.pow(v,1/N));}return [...new Set(xs.filter(x=>x>=range[0]&&x<=range[1]&&(d.mode!=='open'||x<1)))].sort((a,b)=>a-b);}
export function ufMainSVG(s){const range=ufXWindow(s),xs=xSamples(s,range),d=ufDomain(s);let ymax=s.family==='geometric'?Math.min(12,Math.max(2,1/(1-Math.min(d.end,.99)))):s.family==='spike'?2*s.N*1.08:s.family==='drift'?s.N*1.15:1.15;const ymin=s.family==='wave'?-.22:-.14;const c=setup(range,[ymin,ymax]);const clip='clip-path="url(#uf-main-svg-clip)"';const points=xs.map(x=>[x,ufPartial(s,s.N,x)]),limits=xs.map(x=>[x,ufLimit(s,x)]);
// Never join the discontinuity at x=1 to the zero branch.
const broken=limits.map(([x,y])=>[x,s.family==='power'&&x===1?null:y]);let inner='';const upper=broken.map(([x,y])=>[x,y===null?null:y+s.eps]),lower=[...broken].reverse().map(([x,y])=>[x,y===null?null:y-s.eps]);if(s.family!=='drift')inner+=`<path d="${path(c,upper)} ${path(c,lower).replace(/^M/,'L')} Z" fill="#e7efda" opacity=".75" ${clip}/>`;
if(s.view==='integral'&&d.compact){inner+=`<path d="${path(c,[[range[0],0],...points,[range[1],0]])}Z" fill="#dfa479" opacity=".28" ${clip}/>`;}
inner+=`<g ${clip}>${stroke(c,broken,'#4b785b','stroke-dasharray="7 5"')}${stroke(c,points,'#c67b47')}</g>`;
if(s.family==='power'&&d.mode==='closed'&&range[1]===1)inner+=`<circle cx="${c.X(1)}" cy="${c.Y(0)}" r="4.5" fill="#fff" stroke="#4b785b" stroke-width="2"/><circle cx="${c.X(1)}" cy="${c.Y(1)}" r="4.5" fill="#4b785b"/>`;
if(d.mode==='open'&&range[1]===1){inner+=`<line x1="${c.X(1)}" y1="${c.t}" x2="${c.X(1)}" y2="${c.h-c.b}" stroke="#b39165" stroke-dasharray="4 4"/><text x="${c.X(1)-6}" y="${c.t+14}" text-anchor="end" class="uf-svg-note">1 ∉ E</text>`;}
const probe=ufProbe(s),v=ufPartial(s,s.N,probe),lim=ufLimit(s,probe);inner+=`<g ${clip}><line x1="${c.X(probe)}" y1="${c.t}" x2="${c.X(probe)}" y2="${c.h-c.b}" stroke="#ae8b67" stroke-dasharray="3 4"/>${lim!==null?`<line x1="${c.X(probe)}" x2="${c.X(probe)}" y1="${c.Y(v)}" y2="${c.Y(lim)}" stroke="#bc784a" stroke-width="4"/>`:''}<circle cx="${c.X(probe)}" cy="${c.Y(v)}" r="5" fill="#c67b47" stroke="#fff" stroke-width="2"/></g><g class="uf-probe-handle" role="slider" tabindex="0" data-uf-probe="1" aria-label="观察点 x，左右方向键移动" aria-valuemin="0" aria-valuemax="${d.end}" aria-valuenow="${probe}"><rect x="${c.X(probe)-16}" y="${c.h-c.b-12}" width="32" height="30" rx="8" fill="#174d43"/><text x="${c.X(probe)}" y="${c.h-c.b+8}" fill="#fff" text-anchor="middle" font-size="13">x</text></g>`;
inner+=`<text x="${c.l+10}" y="${c.t+15}" class="uf-svg-note">N=${s.N}　绿带：S±ε　${s.zoom?'局部放大，E 不变':''}</text>`;
if(s.family==='geometric'&&d.mode!=='restricted')inner+=`<text x="${c.l+10}" y="${c.t+32}" class="uf-svg-note">超出高度 ${ufNum(ymax)} 的曲线裁切，不等于函数终止</text>`;
return svg(c,inner,'原函数部分和 S_N（橙）与极限 S（绿虚线），绿色带为允许误差，探针可拖动。','uf-main-svg');}
export function ufErrorSVG(s){const range=ufXWindow(s),norm=ufNorm(s),xs=xSamples(s,range);let ymax=norm.value===null||norm.value===Infinity?Math.max(1,s.eps*2):Math.max(norm.value*1.1,s.eps*1.7,.01);if(s.family==='geometric'&&norm.value===Infinity)ymax=4;const c=setup(range,[0,ymax],235);const points=xs.map(x=>[x,ufError(s,s.N,x)]);if(s.family==='power'&&ufDomain(s).mode==='closed')points.forEach(p=>{if(p[0]===1)p[1]=null;});let inner=`<g clip-path="url(#uf-error-svg-clip)"><rect x="${c.l}" y="${c.Y(s.eps)}" width="${c.w-c.l-c.r}" height="${c.Y(0)-c.Y(s.eps)}" fill="#edf3e1"/>${stroke(c,points,'#c67b47')}<line x1="${c.l}" x2="${c.w-c.r}" y1="${c.Y(s.eps)}" y2="${c.Y(s.eps)}" stroke="#729450" stroke-dasharray="5 4"/></g><text x="${c.l+8}" y="${Math.max(38,c.Y(s.eps)-7)}" class="uf-svg-note">ε=${s.eps}　|S_N−S|</text>`;if(s.family==='power'&&ufDomain(s).mode==='closed'&&range[1]===1)inner+=`<circle cx="${c.X(1)}" cy="${c.Y(1)}" r="4" fill="white" stroke="#c67b47"/><circle cx="${c.X(1)}" cy="${c.Y(0)}" r="4" fill="#c67b47"/>`;return svg(c,inner,'误差切片；上确界单独由公式给出，不由网格估计。','uf-error-svg');}
export function ufHistorySVG(s){const end=Math.min(512,Math.max(64,s.N*2)),d=ufDomain(s),x=Math.min(s.x*d.end,d.mode==='open'?1-1e-9:d.end);const rows=Array.from({length:end},(_,i)=>{const m=i+1;return[m,ufError(s,m,x),ufNorm(s,m).value];});const finite=rows.flatMap(v=>v.slice(1)).filter(v=>v!==null&&Number.isFinite(v)&&v>0);const hi=Math.max(0,Math.ceil(Math.log10(Math.max(1,...finite))));const lo=-6;const c=setup([1,end],[lo,hi+.2],245);const log=v=>v===null||v===Infinity?null:Math.log10(Math.max(1e-6,v));let inner=`<g clip-path="url(#uf-history-svg-clip)">${stroke(c,rows.map(r=>[r[0],log(r[1])]),'#c67b47')}${stroke(c,rows.map(r=>[r[0],log(r[2])]),'#477f62','stroke-dasharray="6 4"')}<line x1="${c.l}" x2="${c.w-c.r}" y1="${c.Y(Math.log10(s.eps))}" y2="${c.Y(Math.log10(s.eps))}" stroke="#97a782" stroke-dasharray="2 4"/><line x1="${c.X(s.N)}" x2="${c.X(s.N)}" y1="${c.t}" y2="${c.h-c.b}" stroke="#b89a7b"/></g><text x="${c.l+8}" y="${c.t+16}" class="uf-svg-note">log₁₀ 误差；低于 10⁻⁶（含 0）贴底，不代表误差相等</text><text x="${c.l+8}" y="${c.t+33}" class="uf-svg-note">固定 x=${ufNum(x)}；${ufNorm(s).value===Infinity?'解析 E_m=+∞，不在有限纵轴内':ufNorm(s).value===null?'没有整个 E 上的 S，E_m 不定义':'虚线 E_m 来自解析式'}</text>`;return svg(c,inner,'固定点误差与全域误差的对数比较。零和低于显示下限的值贴底，解析读数另列。','uf-history-svg').replace('>x</text>','>m</text>');}
export function ufDerivativeSVG(s){const range=ufXWindow(s),xs=xSamples(s,range),ys=xs.map(x=>ufDerivative(s,s.N,x)),gs=xs.map(x=>ufLimitDerivative(s,x));let max=s.family==='geometric'?Math.min(40,Math.max(2,1/(1-Math.min(ufDomain(s).end,.99))**2)):s.family==='power'?Math.min(20,Math.max(2,s.N*range[1]**(s.N-1))):s.family==='spike'?4*s.N*s.N:1.25;const c=setup(range,[s.family==='wave'||s.family==='spike'?-max:-.15,max],245);const inner=`<g clip-path="url(#uf-derivative-svg-clip)">${stroke(c,xs.map((x,i)=>[x,gs[i]]),'#477f62','stroke-dasharray="6 4"')}${stroke(c,xs.map((x,i)=>[x,ys[i]]),'#7b759b')}</g><text x="${c.l+8}" y="${c.t+16}" class="uf-svg-note">紫：S_N′　绿虚线：S′；域内折点不定义导数，不连成结论</text>${['power','geometric'].includes(s.family)?`<text x="${c.l+8}" y="${c.t+32}" class="uf-svg-note">超出纵轴会裁切；导数读数与结论使用公式</text>`:''}`;return svg(c,inner,'局部斜率：导数部分和与极限函数的导数分开计算。','uf-derivative-svg');}
export function ufBudgetSVG(s){const d=ufDomain(s),x=ufProbe(s),N=Math.min(s.N,24),m=ufMajorant(s);const rows=Array.from({length:N},(_,i)=>{let n=i+1,M=null;if(s.family==='geometric')M=d.mode==='restricted'?d.end**(n-1):1;else if(s.family==='alternating')M=1/n;else if(s.family==='power'){M=d.mode==='restricted'?(n===1?d.end:d.end**(n-1)):(n===1?1:(1-1/n)**(n-1)/n);}return {n,M,v:Math.abs(ufTerm(s,n,x))};});const max=Math.max(.1,...rows.flatMap(r=>[r.M??0,r.v]));const c=setup([.4,N+.6],[0,max*1.3],230);let bars='';for(const row of rows){if(row.M!==null)bars+=`<rect x="${c.X(row.n)-7}" y="${c.Y(row.M)}" width="14" height="${c.Y(0)-c.Y(row.M)}" fill="#e6efd8" stroke="#9db383"/>`;bars+=`<rect x="${c.X(row.n)-3}" y="${c.Y(row.v)}" width="6" height="${c.Y(0)-c.Y(row.v)}" fill="#c98453"/>`;}
bars+=`<text x="${c.l+8}" y="${c.t+14}" class="uf-svg-note">前 ${N} 项；橙：当前点 |uₙ(x)|；绿：${m.valid?'可求和的 Mₙ':'项的统一范数（如已知）'}</text>`;return svg(c,bars,'每项的统一上界与某个固定点的绝对值。有限柱形不证明可求和。','uf-budget-svg').replace('>x</text>','>n</text>');}
export function ufMiniSVG(s){const w=250,h=130,range=[0,ufDomain(s).end],c=setup(range,[-.15,s.family==='spike'?2*s.N*1.1:s.family==='drift'?s.N*1.1:s.family==='geometric'?4:1.2],h);c.l=8;c.r=8;const X=x=>10+x/range[1]*230,Y=y=>h-15-(y-c.yrange[0])/(c.yrange[1]-c.yrange[0])*(h-25);let ds='';for(const x of xSamples(s,range)){const y=ufPartial(s,s.N,x);if(y===null)continue;ds+=`${ds?'L':'M'}${X(x)},${Math.max(-100,Math.min(h+100,Y(y)))}`;}return `<svg viewBox="0 0 ${w} ${h}" class="uf-mini-svg" aria-label="当前 S_N 的缩略图，完整探针在实验页"><line x1="10" x2="240" y1="${Y(0)}" y2="${Y(0)}" stroke="#bfcab4"/><path d="${ds}" fill="none" stroke="#c6804f" stroke-width="2.5"/><text x="14" y="18" class="uf-svg-note">S_${s.N} · E=${ufDomain(s).label}</text></svg>`;}

